!                           DISCLAIMER
! 
!   This file was generated by TAF version 5.9.12
! 
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
! 
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
! 
module     fluxmod
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use pumamod

implicit none

!==============================================
! declare parameters
!==============================================
real, parameter :: vonkarman = 0.4

!==============================================
! declare local variables
!==============================================
real :: dtransh(nhor)
real :: dtransh_ad(nhor)
real :: dtransm(nhor)
real :: dtransm_ad(nhor)
integer :: nevap = 1
integer :: nshfl = 1
integer :: nstress = 1
integer :: ntsa = 2
integer :: nvdiff = 1
real :: time4ev = 0.
real :: time4fl = 0.
real :: time4sf = 0.
real :: time4sh = 0.
real :: time4st = 0.
real :: time4tr = 0.
real :: time4vd = 0.
real :: vdiff_b = 5.
real :: vdiff_c = 5.
real :: vdiff_d = 5.
real :: vdiff_lamm = 160.
character(len=80) :: version = '22.11.2002 by Larry'
real :: zumin = 1.

contains
subroutine fluxmod_constructor_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
implicit none

!----------------------------------------------
! RESET ADJOINT MODULE VARIABLES
!----------------------------------------------
dtransh_ad(:) = 0.
dtransm_ad(:) = 0.

end subroutine fluxmod_constructor_ad
end module     fluxmod

subroutine fluxini()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare namelists
!==============================================
namelist /fluxmod_nl/ nvdiff,nshfl,nevap,nstress,ntsa,zumin,vdiff_lamm,vdiff_b,vdiff_c,vdiff_d

if (mypid == nroot) then
  open(unit=11,file=fluxmod_namelist)
  read(unit=11,nml=fluxmod_nl)
  close(unit=11)
  write(unit=nud,fmt='(/," ***********************************************")')
  write(unit=nud,fmt='(" * FLUXMOD ",a35," *")') trim(version)
  write(unit=nud,fmt='(" ***********************************************")')
  write(unit=nud,fmt='(" * Namelist FLUXMOD_NL from <fluxmod_namelist> *")')
  write(unit=nud,fmt='(" ***********************************************")')
  write(unit=nud,nml=fluxmod_nl)
endif
alpha1g(1:nugp) = 1.
beta1g(1:nugp) = 1.
gamma1g(1:nugp) = 1.
call mpscgp( alpha1g,alpha1m,1 )
call mpscgp( beta1g,beta1m,1 )
call mpscgp( gamma1g,gamma1m,1 )
call mpbci( nvdiff )
call mpbci( nshfl )
call mpbci( nevap )
call mpbci( nstress )
call mpbci( ntsa )
call mpbcr( zumin )
call mpbcr( vdiff_lamm )
call mpbcr( vdiff_b )
call mpbcr( vdiff_c )
call mpbcr( vdiff_d )
end subroutine fluxini

subroutine fluxstep_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: dtsah(lbound(dtsa,1):ubound(dtsa,1))

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
dtsah(:) = dtsa

call surflx
if (nvdiff > 0) then
  call vdiff_ad
endif
dtsa = dtsah(:)
call surflx_ad

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine fluxstep_ad

subroutine fluxstep()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zsec
real :: zsec1

if (ntime == 1) then
  call mksecond( zsec,0. )
endif
call surflx
if (ntime == 1) then
  call mksecond( zsec1,zsec )
  time4sf = time4sf+zsec1
  call mksecond( zsec1,0. )
endif
if (nvdiff > 0) then
  call vdiff
endif
if (ntime == 1) then
  call mksecond( zsec1,zsec1 )
  time4vd = time4vd+zsec1
  call mksecond( zsec,zsec )
  time4fl = time4fl+zsec
endif
end subroutine fluxstep

subroutine fluxstop()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

if (mypid == nroot .and. ntime == 1) then
  write(unit=nud,fmt=*) '*********************************************'
  write(unit=nud,fmt=*) ' CPU usage in FLUXSTEP (ROOT process only):  '
  write(unit=nud,fmt=*) '    All routines      : ',time4fl,' s'
  write(unit=nud,fmt=*) '    All surface fluxes: ',time4sf,' s'
  write(unit=nud,fmt=*) '    Vertical diffusion: ',time4vd,' s'
  write(unit=nud,fmt=*) '    Transfere coeff   : ',time4tr,' s'
  write(unit=nud,fmt=*) '    Sensible heat flux: ',time4sh,' s'
  write(unit=nud,fmt=*) '    Evaporation       : ',time4ev,' s'
  write(unit=nud,fmt=*) '    Wind stress       : ',time4st,' s'
  write(unit=nud,fmt=*) '*********************************************'
endif
end subroutine fluxstop

subroutine mkevap_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zkdiff(nhor)
real :: zkdiff_ad(nhor)
real :: zkonst1
real :: zkonst2
real :: zqn(nhor)
real :: zqn_ad(nhor)

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zkdiff_ad(:) = 0.
zqn_ad(:) = 0.

zkonst1 = ga*deltsec2/(gascon*dsigma(nlev))
zkonst2 = dsigma(nlev)/deltsec2/ga
zkdiff(:) = drhs(:)*zkonst1*beta1m(:)*dtransh(:)/dt(:,nlep)
zqn(:) = amax1(dq(:,nlev),(dq(:,nlev)+zkdiff(:)*dq(:,nlep))/(1.+zkdiff(:)))
where (dt(:,nlep) > tmelt .or. dls(:) < 0.5)
  devap_ad(:) = devap_ad(:)+1000.*dlhfl_ad(:)*alv
  dlhfl_ad(:) = 0.
end where
where ( .not. (dt(:,nlep) > tmelt .or. dls(:) < 0.5))
  devap_ad(:) = devap_ad(:)+1000.*dlhfl_ad(:)*als
  dlhfl_ad(:) = 0.
end where
dp_ad(:) = dp_ad(:)-devap_ad(:)*(zkonst2/1000.)*(zqn(:)-dq(:,nlev))
dq_ad(:,nlev) = dq_ad(:,nlev)+devap_ad(:)*(dp(:)*zkonst2/1000.)
zqn_ad(:) = zqn_ad(:)-devap_ad(:)*(dp(:)*zkonst2/1000.)
devap_ad(:) = 0.
dq_ad(:,nlev) = dq_ad(:,nlev)-dqdt_ad(:,nlev)/deltsec2
zqn_ad(:) = zqn_ad(:)+dqdt_ad(:,nlev)/deltsec2
dq_ad(:,nlep) = dq_ad(:,nlep)+zqn_ad(:)*(0.5-sign(0.5,dq(:,nlev)-(dq(:,nlev)+zkdiff(:)*dq(:,nlep))/(1.+zkdiff(:))))*(zkdiff(:)/(1.+&
&zkdiff(:)))
dq_ad(:,nlev) = dq_ad(:,nlev)+zqn_ad(:)*(0.5+(0.5-sign(0.5,dq(:,nlev)-(dq(:,nlev)+zkdiff(:)*dq(:,nlep))/(1.+zkdiff(:))))/(1.+&
&zkdiff(:))+sign(0.5,dq(:,nlev)-(dq(:,nlev)+zkdiff(:)*dq(:,nlep))/(1.+zkdiff(:))))
zkdiff_ad(:) = zkdiff_ad(:)+zqn_ad(:)*(0.5-sign(0.5,dq(:,nlev)-(dq(:,nlev)+zkdiff(:)*dq(:,nlep))/(1.+zkdiff(:))))*((dq(:,nlep)-&
&(dq(:,nlev)+zkdiff(:)*dq(:,nlep))/(1.+zkdiff(:)))/(1.+zkdiff(:)))
zqn_ad(:) = 0.
beta1m_ad(:) = beta1m_ad(:)+zkdiff_ad(:)*(drhs(:)*zkonst1*dtransh(:)/dt(:,nlep))
drhs_ad(:) = drhs_ad(:)+zkdiff_ad(:)*(zkonst1*beta1m(:)*dtransh(:)/dt(:,nlep))
dt_ad(:,nlep) = dt_ad(:,nlep)-zkdiff_ad(:)*(drhs(:)*zkonst1*beta1m(:)*dtransh(:)/dt(:,nlep)/dt(:,nlep))
dtransh_ad(:) = dtransh_ad(:)+zkdiff_ad(:)*(drhs(:)*zkonst1*beta1m(:)/dt(:,nlep))
zkdiff_ad(:) = 0.

end subroutine mkevap_ad

subroutine mkevap()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zkdiff(nhor)
real :: zkonst1
real :: zkonst2
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real, allocatable :: zprf5(:)
real :: zqn(nhor)

zkonst1 = ga*deltsec2/(gascon*dsigma(nlev))
zkonst2 = dsigma(nlev)/deltsec2/ga
zkdiff(:) = drhs(:)*zkonst1*beta1m(:)*dtransh(:)/dt(:,nlep)
zqn(:) = amax1(dq(:,nlev),(dq(:,nlev)+zkdiff(:)*dq(:,nlep))/(1.+zkdiff(:)))
dqdt(:,nlev) = dqdt(:,nlev)+(zqn(:)-dq(:,nlev))/deltsec2
devap(:) = -(dp(:)*zkonst2/1000.*(zqn(:)-dq(:,nlev)))
where (dt(:,nlep) > tmelt .or. dls(:) < 0.5)
  dlhfl(:) = devap(:)*alv*1000.
  dlhdt(:) = -(1.*alv*zkdiff(:)*zkonst2*dp(:)*ra2*(tmelt-ra4)*dq(:,nlep)/(dt(:,nlep)-ra4)**2)
elsewhere
  dlhfl(:) = devap(:)*als*1000.
  dlhdt(:) = -(1.*als*zkdiff(:)*zkonst2*dp(:)*ra2*(tmelt-ra4)*dq(:,nlep)/(dt(:,nlep)-ra4)**2)
end where
where (dlhfl(:) == 0.)
  dlhdt(:) = 0.
end where
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  allocate( zprf5(nlon*nlat) )
  call mpgagp( zprf1,zqn,1 )
  call mpgagp( zprf2,dq(1,nlev),1 )
  call mpgagp( zprf3,devap,1 )
  call mpgagp( zprf4,dlhfl,1 )
  call mpgagp( zprf5,dlhdt,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In mkevap:'
    write(unit=nud,fmt=*) 'q-new= ',zprf1(nprhor),' dq/dt (1/s)= ',(zprf1(nprhor)-zprf2(nprhor))/deltsec2
    write(unit=nud,fmt=*) 'lhfl= ',zprf4(nprhor),' dlhdt= ',zprf5(nprhor)
    write(unit=nud,fmt=*) 'evap (mm/day)= ',1000.*ntspd*0.5*deltsec2*zprf3(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
  deallocate( zprf5 )
endif
if (ndiaggp == 1) then
  dgp3d(:,1:nlem,13) = 0.
  dgp3d(:,nlev,13) = (zqn(:)-dq(:,nlev))/deltsec2*dp(:)*dsigma(nlev)/ga/1000.
endif
if (nentropy > 0) then
  dentropy(:,15) = dlhfl(:)/dt(:,nlep)
endif
end subroutine mkevap

subroutine mkshfl_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: dshflh(nhor)
real :: dshflh_ad(nhor)
real :: dshfli(nhor)
real :: zexp
real :: zfac(nhor)
real :: zkdiff(nhor)
real :: zkdiff_ad(nhor)
real :: zkonst1
real :: zkonst2
real :: ztn(nhor)
real :: ztn_ad(nhor)

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zkdiff_ad(:) = 0.
ztn_ad(:) = 0.

zexp = -akap
zkonst1 = ga*deltsec2/(gascon*dsigma(nlev))
zkonst2 = dsigma(nlev)/deltsec2/ga
zfac(:) = sigma(nlev)**zexp
zkdiff(:) = zkonst1*alpha1m(:)*dtransh(:)/dt(:,nlep)
ztn(:) = (dt(:,nlev)+zkdiff(:)*dt(:,nlep))/(1.+zkdiff(:)*zfac(:))
ztn_ad(:) = ztn_ad(:)+dtsa_ad(:)*zfac(:)
dtsa_ad(:) = 0.
dshflh = 1.+adv*dq(:,nlev)
dshfli = amax1(1.,dshflh)
dshflh_ad(:) = 0._8
dp_ad(:) = dp_ad(:)+dshfl_ad(:)*zkonst2*zkdiff(:)*acpd*dshfli*(ztn(:)*zfac(:)-dt(:,nlep))
dt_ad(:,nlep) = dt_ad(:,nlep)-dshfl_ad(:)*zkonst2*zkdiff(:)*dp(:)*acpd*dshfli
zkdiff_ad(:) = zkdiff_ad(:)+dshfl_ad(:)*zkonst2*dp(:)*acpd*dshfli*(ztn(:)*zfac(:)-dt(:,nlep))
ztn_ad(:) = ztn_ad(:)+dshfl_ad(:)*zkonst2*zkdiff(:)*dp(:)*acpd*dshfli*zfac(:)
dshflh_ad = dshfl_ad(:)*zkonst2*zkdiff(:)*dp(:)*acpd*(ztn(:)*zfac(:)-dt(:,nlep))*(0.5-sign(0.5,1.-dshflh))
dq_ad(:,nlev) = dq_ad(:,nlev)+dshflh_ad*adv
dshfl_ad(:) = 0.
dt_ad(:,nlev) = dt_ad(:,nlev)-dtdt_ad(:,nlev)/deltsec2
ztn_ad(:) = ztn_ad(:)+dtdt_ad(:,nlev)/deltsec2
dt_ad(:,nlep) = dt_ad(:,nlep)+ztn_ad(:)*(zkdiff(:)/(1.+zkdiff(:)*zfac(:)))
dt_ad(:,nlev) = dt_ad(:,nlev)+ztn_ad(:)/(1.+zkdiff(:)*zfac(:))
zkdiff_ad(:) = zkdiff_ad(:)+ztn_ad(:)*((dt(:,nlep)-(dt(:,nlev)+zkdiff(:)*dt(:,nlep))*zfac(:)/(1.+zkdiff(:)*zfac(:)))/(1.+zkdiff(:)*&
&zfac(:)))
ztn_ad(:) = 0.
alpha1m_ad(:) = alpha1m_ad(:)+zkdiff_ad(:)*(zkonst1*dtransh(:)/dt(:,nlep))
dt_ad(:,nlep) = dt_ad(:,nlep)-zkdiff_ad(:)*(zkonst1*alpha1m(:)*dtransh(:)/dt(:,nlep)/dt(:,nlep))
dtransh_ad(:) = dtransh_ad(:)+zkdiff_ad(:)*(zkonst1*alpha1m(:)/dt(:,nlep))
zkdiff_ad(:) = 0.

end subroutine mkshfl_ad

subroutine mkshfl()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zexp
real :: zfac(nhor)
real :: zkdiff(nhor)
real :: zkonst1
real :: zkonst2
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real, allocatable :: zprf5(:)
real :: ztn(nhor)
real :: zzts
real :: zztsn

zexp = -akap
zkonst1 = ga*deltsec2/(gascon*dsigma(nlev))
zkonst2 = dsigma(nlev)/deltsec2/ga
zfac(:) = sigma(nlev)**zexp
zkdiff(:) = zkonst1*alpha1m(:)*dtransh(:)/dt(:,nlep)
ztn(:) = (dt(:,nlev)+zkdiff(:)*dt(:,nlep))/(1.+zkdiff(:)*zfac(:))
dtdt(:,nlev) = dtdt(:,nlev)+(ztn(:)-dt(:,nlev))/deltsec2
dshfl(:) = zkonst2*zkdiff(:)*dp(:)*acpd*amax1(1.,1.+adv*dq(:,nlev))*(ztn(:)*zfac(:)-dt(:,nlep))
dshdt(:) = -(1.*zkonst2*zkdiff(:)*dp(:)*acpd*amax1(1.,1.+adv*dq(:,nlev)))
dtsa(:) = ztn(:)*zfac(:)
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  allocate( zprf5(nlon*nlat) )
  call mpgagp( zprf1,ztn,1 )
  call mpgagp( zprf2,dt(1,nlev),1 )
  call mpgagp( zprf3,zfac,1 )
  call mpgagp( zprf4,dshfl,1 )
  call mpgagp( zprf5,dshdt,1 )
  if (mypid == nroot) then
    zzts = zprf2(nprhor)*zprf3(nprhor)
    zztsn = zprf1(nprhor)*zprf3(nprhor)
    write(unit=nud,fmt=*) 'In mkshfl:'
    write(unit=nud,fmt=*) 't-new= ',zprf1(nprhor),' tsa(old)= ',zzts,' tsa(new)= ',zztsn
    write(unit=nud,fmt=*) 'dt/dt (K/s)= ',(zprf1(nprhor)-zprf2(nprhor))/deltsec2
    write(unit=nud,fmt=*) 'shfl= ',zprf4(nprhor),' dshdt= ',zprf5(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
  deallocate( zprf5 )
endif
if (ndiaggp == 1) then
  dgp3d(:,1:nlem,3) = 0.
  dgp3d(:,nlev,3) = (ztn(:)-dt(:,nlev))/deltsec2
endif
if (nentropy > 0) then
  if (nentropy > 2) then
    dentropy(:,7) = (ztn(:)-dt(:,nlev))/deltsec2/dt(:,nlev)*acpd*(1.+adv*dq(:,nlev))*dp(:)/ga*dsigma(nlev)
    dentropy(:,14) = dshfl(:)/dt(:,nlep)
  else
    dentropy(:,7) = (ztn(:)-dt(:,nlev))/deltsec2/dentrot(:,nlev)*acpd*(1.+adv*dentroq(:,nlev))*dentrop(:)/ga*dsigma(nlev)
    dentropy(:,14) = dshfl(:)/dt(:,nlep)
  endif
endif
if (nenergy > 0) then
  denergy(:,7) = (ztn(:)-dt(:,nlev))/deltsec2*acpd*(1.+adv*dq(:,nlev))*dp(:)/ga*dsigma(nlev)
endif
end subroutine mkshfl

subroutine mkstress_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: dust3h(nhor)
real :: dust3h_ad(nhor)
real :: zdtdt_ad(nhor)
real :: zkdiff(nhor)
real :: zkdiff_ad(nhor)
real :: zkonst1
real :: zkonst2
real :: zun(nhor)
real :: zun_ad(nhor)
real :: zvn(nhor)
real :: zvn_ad(nhor)

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zdtdt_ad(:) = 0.
zkdiff_ad(:) = 0.
zun_ad(:) = 0.
zvn_ad(:) = 0.

zkonst1 = ga*deltsec2/(gascon*dsigma(nlev))
zkonst2 = dsigma(nlev)/deltsec2/ga
zkdiff(:) = zkonst1*gamma1m(:)*dtransm(:)/dt(:,nlep)
zun(:) = du(:,nlev)/(1.+zkdiff(:))
zvn(:) = dv(:,nlev)/(1.+zkdiff(:))
dtaux(:) = dp(:)*zkonst2*zkdiff(:)*zun(:)
dtauy(:) = dp(:)*zkonst2*zkdiff(:)*zvn(:)
dust3(:) = sqrt(dtaux(:)**2+dtauy(:)**2)*gascon*dt(:,nlep)/dp(:)
dust3(:) = sqrt(dust3(:))
dust3_ad(:) = 3*dust3_ad(:)*dust3(:)**2
dust3(:) = sqrt(dtaux(:)**2+dtauy(:)**2)*gascon*dt(:,nlep)/dp(:)
dust3_ad(:) = dust3_ad(:)*(1./(2.*sqrt(dust3(:))))
dust3h = dtaux(:)**2+dtauy(:)**2
dp_ad(:) = dp_ad(:)-dust3_ad(:)*(gascon*dt(:,nlep)*sqrt(dust3h)/dp(:)/dp(:))
dt_ad(:,nlep) = dt_ad(:,nlep)+dust3_ad(:)*(gascon*sqrt(dust3h)/dp(:))
dust3h_ad = dust3_ad(:)*(1./(2.*sqrt(dust3h))*gascon*dt(:,nlep)/dp(:))
dtaux_ad(:) = dtaux_ad(:)+2*dust3h_ad*dtaux(:)
dtauy_ad(:) = dtauy_ad(:)+2*dust3h_ad*dtauy(:)
dust3_ad(:) = 0.
dp_ad(:) = dp_ad(:)+dtauy_ad(:)*zkonst2*zkdiff(:)*zvn(:)
zkdiff_ad(:) = zkdiff_ad(:)+dtauy_ad(:)*dp(:)*zkonst2*zvn(:)
zvn_ad(:) = zvn_ad(:)+dtauy_ad(:)*dp(:)*zkonst2*zkdiff(:)
dtauy_ad(:) = 0.
dp_ad(:) = dp_ad(:)+dtaux_ad(:)*zkonst2*zkdiff(:)*zun(:)
zkdiff_ad(:) = zkdiff_ad(:)+dtaux_ad(:)*dp(:)*zkonst2*zun(:)
zun_ad(:) = zun_ad(:)+dtaux_ad(:)*dp(:)*zkonst2*zkdiff(:)
dtaux_ad(:) = 0.
if (ndheat > 0) then
  zdtdt_ad(:) = zdtdt_ad(:)+dtdt_ad(:,nlev)
  dq_ad(:,nlev) = dq_ad(:,nlev)+zdtdt_ad(:)*(0.5*((zun(:)*zun(:)-du(:,nlev)*du(:,nlev)+zvn(:)*zvn(:)-dv(:,nlev)*dv(:,nlev))/&
&deltsec2)/acpd*adv/(1.+adv*dq(:,nlev))/(1.+adv*dq(:,nlev)))
  du_ad(:,nlev) = du_ad(:,nlev)+zdtdt_ad(:)*(0.5*(2*du(:,nlev)/deltsec2)/acpd/(1.+adv*dq(:,nlev)))
  dv_ad(:,nlev) = dv_ad(:,nlev)+zdtdt_ad(:)*(0.5*(2*dv(:,nlev)/deltsec2)/acpd/(1.+adv*dq(:,nlev)))
  zun_ad(:) = zun_ad(:)-zdtdt_ad(:)*(0.5*(2*zun(:)/deltsec2)/acpd/(1.+adv*dq(:,nlev)))
  zvn_ad(:) = zvn_ad(:)-zdtdt_ad(:)*(0.5*(2*zvn(:)/deltsec2)/acpd/(1.+adv*dq(:,nlev)))
  zdtdt_ad(:) = 0.
endif
dv_ad(:,nlev) = dv_ad(:,nlev)-dvdt_ad(:,nlev)/deltsec2
zvn_ad(:) = zvn_ad(:)+dvdt_ad(:,nlev)/deltsec2
du_ad(:,nlev) = du_ad(:,nlev)-dudt_ad(:,nlev)/deltsec2
zun_ad(:) = zun_ad(:)+dudt_ad(:,nlev)/deltsec2
dv_ad(:,nlev) = dv_ad(:,nlev)+zvn_ad(:)/(1.+zkdiff(:))
zkdiff_ad(:) = zkdiff_ad(:)-zvn_ad(:)*(dv(:,nlev)/(1.+zkdiff(:))/(1.+zkdiff(:)))
zvn_ad(:) = 0.
du_ad(:,nlev) = du_ad(:,nlev)+zun_ad(:)/(1.+zkdiff(:))
zkdiff_ad(:) = zkdiff_ad(:)-zun_ad(:)*(du(:,nlev)/(1.+zkdiff(:))/(1.+zkdiff(:)))
zun_ad(:) = 0.
dt_ad(:,nlep) = dt_ad(:,nlep)-zkdiff_ad(:)*(zkonst1*gamma1m(:)*dtransm(:)/dt(:,nlep)/dt(:,nlep))
dtransm_ad(:) = dtransm_ad(:)+zkdiff_ad(:)*(zkonst1*gamma1m(:)/dt(:,nlep))
gamma1m_ad(:) = gamma1m_ad(:)+zkdiff_ad(:)*(zkonst1*dtransm(:)/dt(:,nlep))
zkdiff_ad(:) = 0.

end subroutine mkstress_ad

subroutine mkstress()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zdtdt(nhor)
real :: zkdiff(nhor)
real :: zkonst1
real :: zkonst2
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real, allocatable :: zprf5(:)
real, allocatable :: zprf6(:)
real, allocatable :: zprf7(:)
real :: zun(nhor)
real :: zvn(nhor)

zkonst1 = ga*deltsec2/(gascon*dsigma(nlev))
zkonst2 = dsigma(nlev)/deltsec2/ga
zkdiff(:) = zkonst1*gamma1m(:)*dtransm(:)/dt(:,nlep)
zun(:) = du(:,nlev)/(1.+zkdiff(:))
zvn(:) = dv(:,nlev)/(1.+zkdiff(:))
dudt(:,nlev) = dudt(:,nlev)+(zun(:)-du(:,nlev))/deltsec2
dvdt(:,nlev) = dvdt(:,nlev)+(zvn(:)-dv(:,nlev))/deltsec2
if (ndheat > 0) then
  zdtdt(:) = -((zun(:)*zun(:)-du(:,nlev)*du(:,nlev)+zvn(:)*zvn(:)-dv(:,nlev)*dv(:,nlev))/deltsec2*0.5/acpd/(1.+adv*dq(:,nlev)))
  dtdt(:,nlev) = dtdt(:,nlev)+zdtdt(:)
endif
dtaux(:) = dp(:)*zkonst2*zkdiff(:)*zun(:)
dtauy(:) = dp(:)*zkonst2*zkdiff(:)*zvn(:)
dust3(:) = sqrt(dtaux(:)**2+dtauy(:)**2)*gascon*dt(:,nlep)/dp(:)
dust3(:) = sqrt(dust3(:))
dust3(:) = dust3(:)**3
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  allocate( zprf5(nlon*nlat) )
  allocate( zprf6(nlon*nlat) )
  allocate( zprf7(nlon*nlat) )
  call mpgagp( zprf1,zun,1 )
  call mpgagp( zprf2,zvn,1 )
  call mpgagp( zprf3,du(1,nlev),1 )
  call mpgagp( zprf4,dv(1,nlev),1 )
  call mpgagp( zprf5,dtaux,1 )
  call mpgagp( zprf6,dtauy,1 )
  call mpgagp( zprf7,dust3,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In mkstress:'
    write(unit=nud,fmt=*) 'u-new= ',zprf1(nprhor),' v-new= ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'du/dt (m/s2)= ',(zprf1(nprhor)-zprf3(nprhor))/deltsec2,' dv/dt (m/s2)= ',(zprf2(nprhor)-zprf4(nprhor))/&
&deltsec2
    write(unit=nud,fmt=*) 'taux= ',zprf5(nprhor),' tauy= ',zprf6(nprhor)
    write(unit=nud,fmt=*) 'ust3= ',zprf7(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
  deallocate( zprf5 )
  deallocate( zprf6 )
  deallocate( zprf7 )
endif
if (nentropy > 0) then
  if (nentropy > 2) then
    dentropy(:,31) = -(((zun(:)*zun(:)-du(:,nlev)*du(:,nlev))/deltsec2+(zvn(:)*zvn(:)-dv(:,nlev)*dv(:,nlev))/deltsec2)*0.5*dp(:)/&
&ga*dsigma(nlev)/dt(:,nlev))
  else
    dentropy(:,31) = -(((zun(:)*zun(:)-du(:,nlev)*du(:,nlev))/deltsec2+(zvn(:)*zvn(:)-dv(:,nlev)*dv(:,nlev))/deltsec2)*0.5*&
&dentrop(:)/ga*dsigma(nlev)/dentrot(:,nlev))
  endif
endif
if (nenergy > 0) then
  denergy(:,21) = -(((zun(:)*zun(:)-du(:,nlev)*du(:,nlev))/deltsec2+(zvn(:)*zvn(:)-dv(:,nlev)*dv(:,nlev))/deltsec2)*0.5*dp(:)/ga*&
&dsigma(nlev))
endif
end subroutine mkstress

subroutine surflx_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
real :: zabsu2(nhor)
real :: zabsu2_ad(nhor)
real :: zbz0(nhor)
real :: zbz0_ad(nhor)
real :: zdenom
real :: zdenom_ad
real :: zdenomh
real :: zdenomh_ad
real :: zdth
real :: zdth_ad
real :: zexp
real :: zkblnz2
real :: zkblnz2_ad
real :: zkblnz2h
real :: zlnsig
real :: znl(nhor)
real :: znl_ad(nhor)
real :: zri(nhor)
real :: zri_ad(nhor)
real :: zrifh(nhor)
real :: zrifh_ad(nhor)
real :: zrifm(nhor)
real :: zrifm_ad(nhor)
real :: ztrans
real :: ztrans_ad

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zabsu2_ad(:) = 0.
zbz0_ad(:) = 0.
zdenom_ad = 0.
zdth_ad = 0.
zkblnz2_ad = 0.
znl_ad(:) = 0.
zri_ad(:) = 0.
zrifh_ad(:) = 0.
zrifm_ad(:) = 0.
ztrans_ad = 0.

!$taf INCOMPLETE dtransh,dtransm,zrifh,zrifm
zexp = -akap
zlnsig = alog(sigma(nlev))
if (ntsa == 1) then
  dtsa(:) = dt(:,nlev)*sigma(nlev)**zexp
else if (ntsa == 2) then
  dtsa(:) = dt(:,nlev)*sigma(nlev)**zexp*(1.+(1./rdbrv-1.)*dq(:,nlev))
endif
zabsu2(:) = amax1(zumin,du(:,nlev)*du(:,nlev)+dv(:,nlev)*dv(:,nlev))
znl(:) = -(gascon*0.5*(dt(:,nlev)+dtsa(:))*zlnsig/ga)
zbz0(:) = znl(:)/dz0(:)
if (ntsa == 1) then
  zri(:) = ga*znl(:)*(dtsa(:)-dt(:,nlep))/(zabsu2(:)*dtsa(:))
else if (ntsa == 2) then
  zri(:) = ga*znl(:)/(zabsu2(:)*dtsa(:))*(dtsa(:)-dt(:,nlep)*(1.+(1./rdbrv-1.)*dq(:,nlep)))
endif
do jhor = 1, nhor
  zkblnz2 = (vonkarman/alog(zbz0(jhor)+1.))**2
  if (zri(jhor) <= 0.) then
    zdenom = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri(jhor)*(zbz0(jhor)+1.)))*zkblnz2
    zrifm(jhor) = 1.-2.*vdiff_b*zri(jhor)/zdenom
    if (dls(jhor) < 1.) then
      zdth = -(dtsa(jhor)-dt(jhor,nlep)*(1.+(1./rdbrv-1.)*dq(jhor,nlep)))
      zrifh(jhor) = (1.+(0.0016*zdth**(1./3.)/sqrt(zabsu2(jhor))/zkblnz2)**1.25)**0.8
    else
      zrifh(jhor) = 1.-3.*vdiff_b*zri(jhor)/zdenom
    endif
  else
    zdenom = sqrt(1+vdiff_d*zri(jhor))
    zrifh(jhor) = 1./(1.+3.*vdiff_b*zri(jhor)*zdenom)
    zrifm(jhor) = 1./(1.+2.*vdiff_b*zri(jhor)/zdenom)
  endif
  ztrans = sqrt(zabsu2(jhor))*zkblnz2
  dtransh(jhor) = ztrans*zrifh(jhor)
  dtransm(jhor) = ztrans*zrifm(jhor)
end do
if (nevap > 0) then
  call mkevap_ad
endif
if (nshfl > 0) then
  call mkshfl_ad
endif
if (nstress > 0) then
  call mkstress_ad
endif
do jhor = nhor, 1, -1
!$taf INCOMPLETE zrifh,zrifm
  zkblnz2 = (vonkarman/alog(zbz0(jhor)+1.))**2
  if (zri(jhor) <= 0.) then
    zdenom = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri(jhor)*(zbz0(jhor)+1.)))*zkblnz2
    zrifm(jhor) = 1.-2.*vdiff_b*zri(jhor)/zdenom
    if (dls(jhor) < 1.) then
      zdth = -(dtsa(jhor)-dt(jhor,nlep)*(1.+(1./rdbrv-1.)*dq(jhor,nlep)))
      zrifh(jhor) = (1.+(0.0016*zdth**(1./3.)/sqrt(zabsu2(jhor))/zkblnz2)**1.25)**0.8
    else
      zrifh(jhor) = 1.-3.*vdiff_b*zri(jhor)/zdenom
    endif
  else
    zdenom = sqrt(1+vdiff_d*zri(jhor))
    zrifh(jhor) = 1./(1.+3.*vdiff_b*zri(jhor)*zdenom)
    zrifm(jhor) = 1./(1.+2.*vdiff_b*zri(jhor)/zdenom)
  endif
  ztrans = sqrt(zabsu2(jhor))*zkblnz2
  zrifm_ad(jhor) = zrifm_ad(jhor)+dtransm_ad(jhor)*ztrans
  ztrans_ad = ztrans_ad+dtransm_ad(jhor)*zrifm(jhor)
  dtransm_ad(jhor) = 0.
  zrifh_ad(jhor) = zrifh_ad(jhor)+dtransh_ad(jhor)*ztrans
  ztrans_ad = ztrans_ad+dtransh_ad(jhor)*zrifh(jhor)
  dtransh_ad(jhor) = 0.
  zabsu2_ad(jhor) = zabsu2_ad(jhor)+ztrans_ad*(1./(2.*sqrt(zabsu2(jhor))))*zkblnz2
  zkblnz2_ad = zkblnz2_ad+ztrans_ad*sqrt(zabsu2(jhor))
  ztrans_ad = 0.
  if (zri(jhor) <= 0.) then
    if (dls(jhor) < 1.) then
      zabsu2_ad(jhor) = zabsu2_ad(jhor)-0.8*zrifh_ad(jhor)*(1.25*(0.0016*zdth**0.333333333333333*(1./(2.*sqrt(zabsu2(jhor))))/&
&sqrt(zabsu2(jhor))/sqrt(zabsu2(jhor))/zkblnz2)*(0.0016*zdth**0.333333333333333/sqrt(zabsu2(jhor))/zkblnz2)**0.25)*(1.+&
&(0.0016*zdth**0.333333333333333/sqrt(zabsu2(jhor))/zkblnz2)**1.25)**(-0.2)
      zdth_ad = zdth_ad+0.8*zrifh_ad(jhor)*(1.25*(0.000533333333333333*zdth**(-0.666666666666667)/sqrt(zabsu2(jhor))/zkblnz2)*&
&(0.0016*zdth**0.333333333333333/sqrt(zabsu2(jhor))/zkblnz2)**0.25)*(1.+(0.0016*zdth**0.333333333333333/sqrt(zabsu2(jhor))/&
&zkblnz2)**1.25)**(-0.2)
      zkblnz2_ad = zkblnz2_ad-0.8*zrifh_ad(jhor)*(1.25*(0.0016*zdth**0.333333333333333/sqrt(zabsu2(jhor))/zkblnz2/zkblnz2)*(0.0016*&
&zdth**0.333333333333333/sqrt(zabsu2(jhor))/zkblnz2)**0.25)*(1.+(0.0016*zdth**0.333333333333333/sqrt(zabsu2(jhor))/zkblnz2)**&
&1.25)**(-0.2)
      zrifh_ad(jhor) = 0.
      dq_ad(jhor,nlep) = dq_ad(jhor,nlep)+zdth_ad*dt(jhor,nlep)*((-1)+1./rdbrv)
      dt_ad(jhor,nlep) = dt_ad(jhor,nlep)+zdth_ad*(1.+(1./rdbrv-1.)*dq(jhor,nlep))
      dtsa_ad(jhor) = dtsa_ad(jhor)-zdth_ad
      zdth_ad = 0.
    else
      zdenom_ad = zdenom_ad+zrifh_ad(jhor)*(3.*vdiff_b*zri(jhor)/zdenom/zdenom)
      zri_ad(jhor) = zri_ad(jhor)-zrifh_ad(jhor)*(3*vdiff_b/zdenom)
      zrifh_ad(jhor) = 0.
    endif
    zdenom_ad = zdenom_ad+zrifm_ad(jhor)*(2.*vdiff_b*zri(jhor)/zdenom/zdenom)
    zri_ad(jhor) = zri_ad(jhor)-zrifm_ad(jhor)*(2*vdiff_b/zdenom)
    zrifm_ad(jhor) = 0.
    zdenomh = -(1.*zri(jhor)*(zbz0(jhor)+1.))
    zdenomh_ad = 3.*zdenom_ad*vdiff_c*vdiff_b*(1./(2.*sqrt(zdenomh)))*zkblnz2
    zkblnz2_ad = zkblnz2_ad+3.*zdenom_ad*vdiff_c*vdiff_b*sqrt(zdenomh)
    zbz0_ad(jhor) = zbz0_ad(jhor)-zdenomh_ad*zri(jhor)
    zri_ad(jhor) = zri_ad(jhor)-zdenomh_ad*(1.+zbz0(jhor))
    zdenom_ad = 0.
  else
    zdenom_ad = zdenom_ad+zrifm_ad(jhor)*(1.*(2.*vdiff_b*zri(jhor)/zdenom/zdenom)/(1.+2.*vdiff_b*zri(jhor)/zdenom)/(1.+2.*vdiff_b*&
&zri(jhor)/zdenom))
    zri_ad(jhor) = zri_ad(jhor)-zrifm_ad(jhor)*(1.*(2*vdiff_b/zdenom)/(1.+2.*vdiff_b*zri(jhor)/zdenom)/(1.+2.*vdiff_b*zri(jhor)/&
&zdenom))
    zrifm_ad(jhor) = 0.
    zdenom_ad = zdenom_ad-zrifh_ad(jhor)*(1.*(3.*vdiff_b*zri(jhor))/(1.+3.*vdiff_b*zri(jhor)*zdenom)/(1.+3.*vdiff_b*zri(jhor)*&
&zdenom))
    zri_ad(jhor) = zri_ad(jhor)-zrifh_ad(jhor)*(1.*(3*vdiff_b*zdenom)/(1.+3.*vdiff_b*zri(jhor)*zdenom)/(1.+3.*vdiff_b*zri(jhor)*&
&zdenom))
    zrifh_ad(jhor) = 0.
    zri_ad(jhor) = zri_ad(jhor)+zdenom_ad*(1./(2.*sqrt(1+vdiff_d*zri(jhor))))*vdiff_d
    zdenom_ad = 0.
  endif
  zkblnz2h = zbz0(jhor)+1.
  zbz0_ad(jhor) = zbz0_ad(jhor)-2*zkblnz2_ad*(vonkarman*(1./zkblnz2h)/alog(zkblnz2h)/alog(zkblnz2h))*(vonkarman/alog(zkblnz2h))
  zkblnz2_ad = 0.
end do
if (ntsa == 1) then
  dt_ad(:,nlep) = dt_ad(:,nlep)!-zri_ad(:)*(ga*znl(:)/(zabsu2(:)*dtsa(:)))
  dtsa_ad(:) = dtsa_ad(:)!+zri_ad(:)*((ga*znl(:)-ga*znl(:)*(dtsa(:)-dt(:,nlep))*zabsu2(:)/(zabsu2(:)*dtsa(:)))/(zabsu2(:)*dtsa(:)))
  zabsu2_ad(:) = zabsu2_ad(:)!-zri_ad(:)*(ga*znl(:)*(dtsa(:)-dt(:,nlep))*dtsa(:)/(zabsu2(:)*dtsa(:))/(zabsu2(:)*dtsa(:)))
  znl_ad(:) = znl_ad(:)!+zri_ad(:)*(ga*(dtsa(:)-dt(:,nlep))/(zabsu2(:)*dtsa(:)))
  zri_ad(:) = 0.
else if (ntsa == 2) then
  dq_ad(:,nlep) = dq_ad(:,nlep)!-zri_ad(:)*(ga*znl(:)/(zabsu2(:)*dtsa(:)))*dt(:,nlep)*((-1)+1./rdbrv)
  dt_ad(:,nlep) = dt_ad(:,nlep)!-zri_ad(:)*(ga*znl(:)/(zabsu2(:)*dtsa(:)))*(1.+(1./rdbrv-1.)*dq(:,nlep))
  dtsa_ad(:) = dtsa_ad(:)!+zri_ad(:)*(ga*znl(:)/(zabsu2(:)*dtsa(:))-ga*znl(:)*zabsu2(:)/(zabsu2(:)*dtsa(:))/(zabsu2(:)*dtsa(:))*&
!&(dtsa(:)-dt(:,nlep)*(1.+(1./rdbrv-1.)*dq(:,nlep))))
  zabsu2_ad(:) = zabsu2_ad(:)!-zri_ad(:)*(ga*znl(:)*dtsa(:)/(zabsu2(:)*dtsa(:))/(zabsu2(:)*dtsa(:)))*(dtsa(:)-dt(:,nlep)*(1.+(1./&
!&rdbrv-1.)*dq(:,nlep)))
  znl_ad(:) = znl_ad(:)!+zri_ad(:)*(ga/(zabsu2(:)*dtsa(:)))*(dtsa(:)-dt(:,nlep)*(1.+(1./rdbrv-1.)*dq(:,nlep)))
  zri_ad(:) = 0.
endif
dz0_ad(:) = dz0_ad(:)-zbz0_ad(:)*(znl(:)/dz0(:)/dz0(:))
znl_ad(:) = znl_ad(:)+zbz0_ad(:)/dz0(:)
zbz0_ad(:) = 0.
dt_ad(:,nlev) = dt_ad(:,nlev)-znl_ad(:)*(0.5*gascon*zlnsig/ga)
dtsa_ad(:) = dtsa_ad(:)-znl_ad(:)*(0.5*gascon*zlnsig/ga)
znl_ad(:) = 0.
du_ad(:,nlev) = du_ad(:,nlev)+2*zabsu2_ad(:)*(0.5-sign(0.5,zumin-(du(:,nlev)*du(:,nlev)+dv(:,nlev)*dv(:,nlev))))*du(:,nlev)
dv_ad(:,nlev) = dv_ad(:,nlev)+2*zabsu2_ad(:)*(0.5-sign(0.5,zumin-(du(:,nlev)*du(:,nlev)+dv(:,nlev)*dv(:,nlev))))*dv(:,nlev)
zabsu2_ad(:) = 0.
if (ntsa == 1) then
  dt_ad(:,nlev) = dt_ad(:,nlev)+dtsa_ad(:)*sigma(nlev)**zexp
  dtsa_ad(:) = 0.
else if (ntsa == 2) then
  dq_ad(:,nlev) = dq_ad(:,nlev)+dtsa_ad(:)*dt(:,nlev)*sigma(nlev)**zexp*((-1)+1./rdbrv)
  dt_ad(:,nlev) = dt_ad(:,nlev)+dtsa_ad(:)*sigma(nlev)**zexp*(1.+(1./rdbrv-1.)*dq(:,nlev))
  dtsa_ad(:) = 0.
endif

end subroutine surflx_ad

subroutine surflx()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
real :: zabsu2(nhor)
real :: zbz0(nhor)
real :: zdenom
real :: zdth
real :: zexp
real :: zkblnz2
real :: zlnsig
real :: znl(nhor)
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real, allocatable :: zprf5(:)
real, allocatable :: zprf6(:)
real, allocatable :: zprf7(:)
real :: zri(nhor)
real :: zrifh(nhor)
real :: zrifm(nhor)
real :: zsec
real :: ztrans

if (ntime == 1) then
  call mksecond( zsec,0. )
endif
zexp = -akap
zlnsig = alog(sigma(nlev))
if (ntsa == 1) then
  dtsa(:) = dt(:,nlev)*sigma(nlev)**zexp
else if (ntsa == 2) then
  dtsa(:) = dt(:,nlev)*sigma(nlev)**zexp*(1.+(1./rdbrv-1.)*dq(:,nlev))
else
  write(unit=nud,fmt=*) '!ERROR: wrong ntsa in fluxmod (only 1 or 2 valied)!'
  stop
endif
zabsu2(:) = amax1(zumin,du(:,nlev)*du(:,nlev)+dv(:,nlev)*dv(:,nlev))
znl(:) = -(gascon*0.5*(dt(:,nlev)+dtsa(:))*zlnsig/ga)
zbz0(:) = znl(:)/dz0(:)
if (ntsa == 1) then
  zri(:) = ga*znl(:)*(dtsa(:)-dt(:,nlep))/(zabsu2(:)*dtsa(:))
else if (ntsa == 2) then
  zri(:) = ga*znl(:)/(zabsu2(:)*dtsa(:))*(dtsa(:)-dt(:,nlep)*(1.+(1./rdbrv-1.)*dq(:,nlep)))
endif
do jhor = 1, nhor
  zkblnz2 = (vonkarman/alog(zbz0(jhor)+1.))**2
  if (zri(jhor) <= 0.) then
    zdenom = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri(jhor)*(zbz0(jhor)+1.)))*zkblnz2
    zrifm(jhor) = 1.-2.*vdiff_b*zri(jhor)/zdenom
    if (dls(jhor) < 1.) then
      zdth = -(dtsa(jhor)-dt(jhor,nlep)*(1.+(1./rdbrv-1.)*dq(jhor,nlep)))
      zrifh(jhor) = (1.+(0.0016*zdth**(1./3.)/sqrt(zabsu2(jhor))/zkblnz2)**1.25)**0.8
    else
      zrifh(jhor) = 1.-3.*vdiff_b*zri(jhor)/zdenom
    endif
  else
    zdenom = sqrt(1+vdiff_d*zri(jhor))
    zrifh(jhor) = 1./(1.+3.*vdiff_b*zri(jhor)*zdenom)
    zrifm(jhor) = 1./(1.+2.*vdiff_b*zri(jhor)/zdenom)
  endif
  ztrans = sqrt(zabsu2(jhor))*zkblnz2
  dtransh(jhor) = ztrans*zrifh(jhor)
  dtransm(jhor) = ztrans*zrifm(jhor)
end do
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  allocate( zprf5(nlon*nlat) )
  allocate( zprf6(nlon*nlat) )
  allocate( zprf7(nlon*nlat) )
  call mpgagp( zprf1,zabsu2,1 )
  call mpgagp( zprf2,znl,1 )
  call mpgagp( zprf3,zri,1 )
  call mpgagp( zprf4,zrifh,1 )
  call mpgagp( zprf5,zrifm,1 )
  call mpgagp( zprf6,dtransh,1 )
  call mpgagp( zprf7,dtransm,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In Surflx:'
    write(unit=nud,fmt=*) 'abs(u)= ',sqrt(zprf1(nprhor)),' znl= ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'ri-number= ',zprf3(nprhor)
    write(unit=nud,fmt=*) 'rifh= ',zprf4(nprhor),' rifm= ',zprf5(nprhor)
    write(unit=nud,fmt=*) 'transh= ',zprf6(nprhor),' transm= ',zprf7(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
  deallocate( zprf5 )
  deallocate( zprf6 )
  deallocate( zprf7 )
endif
if (ntime == 1) then
  call mksecond( zsec,zsec )
  time4tr = time4tr+zsec
  call mksecond( zsec,0. )
endif
if (nstress > 0) then
  call mkstress
endif
if (ntime == 1) then
  call mksecond( zsec,zsec )
  time4st = time4st+zsec
  call mksecond( zsec,0. )
endif
if (nshfl > 0) then
  call mkshfl
endif
if (ntime == 1) then
  call mksecond( zsec,zsec )
  time4sh = time4sh+zsec
  call mksecond( zsec,0. )
endif
if (nevap > 0) then
  call mkevap
endif
if (ntime == 1) then
  call mksecond( zsec,zsec )
  time4ev = time4ev+zsec
endif
end subroutine surflx

subroutine vdiff_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare parameters
!==============================================
real, parameter :: ztscal = 250.

!==============================================
! declare local variables
!==============================================
integer :: jhor
integer :: jlem
integer :: jlep
integer :: jlev
integer :: jlp
real :: zabsu(nhor,nlev)
real :: zabsu_ad(nhor,nlev)
real :: zdenom
real :: zdenom_ad
real :: zdenomh
real :: zdenomh_ad
real :: zdenomm
real :: zdenomm_ad
real :: zdqdt_ad(nhor,nlev)
real :: zdtdt_ad(nhor,nlev)
real :: zdthds
real :: zdthds_ad
real :: zdudt_ad(nhor,nlev)
real :: zdvds
real :: zdvds_ad
real :: zdvdsh
real :: zdvdsh_ad
real :: zdvdsi_ad
real :: zdvdt_ad(nhor,nlev)
real :: zdz
real :: zebs(nhor,nlem)
real :: zebs2(nhor,nlem)
real :: zebs2_ad(nhor,nlem)
real :: zebs2h_ad(nhor)
real :: zebs2i_ad(nhor)
real :: zebs3(nhor,nlem)
real :: zebs3_ad(nhor,nlem)
real :: zebs3h_ad(nhor)
real :: zebs_ad(nhor,nlem)
real :: zebsh_ad(nhor)
real :: zfac
real :: zkdiffh(nhor,nlem)
real :: zkdiffh2(nhor,nlem)
real :: zkdiffh2_ad(nhor,nlem)
real :: zkdiffh_ad(nhor,nlem)
real :: zkdiffm(nhor,nlem)
real :: zkdiffm_ad(nhor,nlem)
real :: zke(nhor,nlev)
real :: zke_ad(nhor,nlev)
real :: zken(nhor,nlev)
real :: zken_ad(nhor,nlev)
real :: zkenh_ad(nhor)
real :: zkeni_ad(nhor)
real :: zkonst1
real :: zkonst2
real :: zkonst3
real :: zlamh
real :: zmixh
real :: zmixh2
real :: zmixm
real :: zmixm2
real :: zq(nhor,nlev)
real :: zq_ad(nhor,nlev)
real :: zqf1
real :: zqf1_ad
real :: zqf2
real :: zqf2_ad
real :: zqn(nhor,nlev)
real :: zqn_ad(nhor,nlev)
real :: zqnh_ad(nhor)
real :: zqni_ad(nhor)
real :: zrdsig
real :: zri
real :: zri_ad
real :: zrifh
real :: zrifh_ad
real :: zrifm
real :: zrifm_ad
real :: zrthl
real :: zrthl_ad
real :: zskap(nlev)
real :: zskaph(nlev)
real :: zt(nhor,nlev)
real :: zt_ad(nhor,nlev)
real :: ztn(nhor,nlev)
real :: ztn_ad(nhor,nlev)
real :: ztnh_ad(nhor)
real :: ztni_ad(nhor)
real :: zu(nhor,nlev)
real :: zu_ad(nhor,nlev)
real :: zun(nhor,nlev)
real :: zun_ad(nhor,nlev)
real :: zunh_ad(nhor)
real :: zuni_ad(nhor)
real :: zv(nhor,nlev)
real :: zv_ad(nhor,nlev)
real :: zvn(nhor,nlev)
real :: zvn_ad(nhor,nlev)
real :: zvnh_ad(nhor)
real :: zvni_ad(nhor)
real :: zzkfac
real :: zzlev

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zabsu_ad(:,:) = 0.
zdenom_ad = 0.
zdenomh_ad = 0.
zdenomm_ad = 0.
zdqdt_ad(:,:) = 0.
zdtdt_ad(:,:) = 0.
zdthds_ad = 0.
zdudt_ad(:,:) = 0.
zdvds_ad = 0.
zdvdt_ad(:,:) = 0.
zebs2_ad(:,:) = 0.
zebs3_ad(:,:) = 0.
zebs_ad(:,:) = 0.
zkdiffh2_ad(:,:) = 0.
zkdiffh_ad(:,:) = 0.
zkdiffm_ad(:,:) = 0.
zke_ad(:,:) = 0.
zken_ad(:,:) = 0.
zq_ad(:,:) = 0.
zqf1_ad = 0.
zqf2_ad = 0.
zqn_ad(:,:) = 0.
zri_ad = 0.
zrifh_ad = 0.
zrifm_ad = 0.
zrthl_ad = 0.
zt_ad(:,:) = 0.
ztn_ad(:,:) = 0.
zu_ad(:,:) = 0.
zun_ad(:,:) = 0.
zv_ad(:,:) = 0.
zvn_ad(:,:) = 0.

!$taf INCOMPLETE zebs,zebs2,zebs3,zkdiffh,zkdiffh2,zkdiffm,zqn,zqn_ad,ztn,ztn_ad,zun,zun_ad,zvn
zlamh = vdiff_lamm*sqrt(3.*vdiff_d*0.5)
zkonst1 = ga*deltsec2/gascon
zkonst2 = zkonst1*ga/gascon
zkonst3 = zkonst2*ga/gascon
zskap(:) = sigma(:)**akap
zskaph(:) = sigmah(:)**akap
zt(:,:) = dt(:,1:nlev)+dtdt(:,1:nlev)*deltsec2
zq(:,:) = dq(:,1:nlev)+dqdt(:,1:nlev)*deltsec2
zu(:,:) = du(:,1:nlev)+dudt(:,1:nlev)*deltsec2
zv(:,:) = dv(:,1:nlev)+dvdt(:,1:nlev)*deltsec2
zabsu(:,:) = sqrt(zu(:,1:nlev)**2+zv(:,1:nlev)**2)
do jlev = 1, nlem
  jlp = jlev+1
  zzlev = -(gascon*ztscal*alog(sigmah(jlev))/ga)
  zdz = gascon*ztscal*alog(sigma(jlp)/sigma(jlev))/ga
  zmixh = zlamh*vonkarman*zzlev/(zlamh+vonkarman*zzlev)
  zmixm = vdiff_lamm*vonkarman*zzlev/(vdiff_lamm+vonkarman*zzlev)
  zmixh2 = zmixh*zmixh
  zmixm2 = zmixm*zmixm
  zrdsig = 1./(sigma(jlp)-sigma(jlev))
  zfac = zkonst3*sigmah(jlev)*sigmah(jlev)*sigmah(jlev)*zrdsig
  zzkfac = sqrt(((((zzlev+zdz)/zzlev)**(1./3.)-1.)/zdz)**3/zzlev)
  do jhor = 1, nhor
    zrthl = (dsigma(jlp)+dsigma(jlev))/(zt(jhor,jlev)*dsigma(jlp)+zt(jhor,jlp)*dsigma(jlev))
    zdvds = amax1(zumin,abs(zabsu(jhor,jlev)-zabsu(jhor,jlp)))*zrdsig
    zqf1 = 1.+(1./rdbrv-1.)*zq(jhor,jlev)
    zqf2 = 1.+(1./rdbrv-1.)*zq(jhor,jlp)
    zdthds = (zt(jhor,jlev)*zqf1/zskap(jlev)-zt(jhor,jlp)*zqf2/zskap(jlp))*zrdsig
    zri = zskaph(jlev)*gascon*zdthds/(sigmah(jlev)*zdvds*zdvds)
    if (zri <= 0.) then
      zdenomh = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri))*zzkfac*zmixh2
      zdenomm = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri))*zzkfac*zmixm2
      zrifh = 1.-3.*vdiff_b*zri/zdenomh
      zrifm = 1.-2.*vdiff_b*zri/zdenomm
    else
      zdenom = sqrt(1+vdiff_d*zri)
      zrifh = 1./(1.+3.*vdiff_b*zri*zdenom)
      zrifm = 1./(1.+2.*vdiff_b*zri/zdenom)
    endif
    zkdiffh(jhor,jlev) = zfac*zmixh2*zrifh*zdvds*zrthl*zrthl*zrthl
    zkdiffm(jhor,jlev) = zfac*zmixm2*zrifm*zdvds*zrthl*zrthl*zrthl
  end do
end do
zebs(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
zun(:,1) = dsigma(1)*zu(:,1)/(dsigma(1)+zkdiffm(:,1))
zvn(:,1) = dsigma(1)*zv(:,1)/(dsigma(1)+zkdiffm(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))
  zun(:,jlev) = (zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
  zvn(:,jlev) = (zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
end do
zun(:,nlev) = (zu(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zun(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))
zvn(:,nlev) = (zv(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zvn(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))
do jlev = nlem, 1, -1
  jlep = jlev+1
  zun(:,jlev) = zun(:,jlev)+zebs(:,jlev)*zun(:,jlep)
  zvn(:,jlev) = zvn(:,jlev)+zebs(:,jlev)*zvn(:,jlep)
end do
if (ndheat > 0) then
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
  end do
endif
zebs2(:,1) = zkdiffh(:,1)/(dsigma(1)+zkdiffh(:,1))
zqn(:,1) = dsigma(1)*zq(:,1)/(dsigma(1)+zkdiffh(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs2(:,jlev) = zkdiffh(:,jlev)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem)))
  zqn(:,jlev) = (zq(:,jlev)*dsigma(jlev)+zkdiffh(:,jlem)*zqn(:,jlem))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,&
&jlem)))
end do
zqn(:,nlev) = (zq(:,nlev)*dsigma(nlev)+zkdiffh(:,nlem)*zqn(:,nlem))/(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem)))
do jlev = 1, nlem
  zkdiffh2(:,jlev) = zkdiffh(:,jlev)*zskaph(jlev)
end do
zebs3(:,1) = zkdiffh2(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
ztn(:,1) = dsigma(1)*zt(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs3(:,jlev) = zkdiffh2(:,jlev)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
  ztn(:,jlev) = (zt(:,jlev)*dsigma(jlev)+zkdiffh2(:,jlem)/zskap(jlem)*ztn(:,jlem))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)&
&*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
end do
ztn(:,nlev) = (zt(:,nlev)*dsigma(nlev)+zkdiffh2(:,nlem)*ztn(:,nlem)/zskap(nlem))/(dsigma(nlev)+zkdiffh2(:,nlem)/zskap(nlev)*(1.-&
&zebs3(:,nlem)/zskap(nlem)))
zdtdt_ad(:,1:nlev) = zdtdt_ad(:,1:nlev)+dtdt_ad(:,1:nlev)
zt_ad(:,1:nlev) = zt_ad(:,1:nlev)-zdtdt_ad(:,1:nlev)/deltsec2
ztn_ad(:,1:nlev) = ztn_ad(:,1:nlev)+zdtdt_ad(:,1:nlev)/deltsec2
zdtdt_ad(:,1:nlev) = 0.
!$taf INCOMPLETE ztn_ad
do jlev = nlem, 2, -1
  jlep = jlev+1
  ztn(:,jlev) = ztn(:,jlev)+zebs3(:,jlev)*ztn(:,jlep)/zskap(jlep)
end do
do jlev = 1, nlem
  jlep = jlev+1
  ztnh_ad = ztn_ad(:,jlev)
  zebs3_ad(:,jlev) = zebs3_ad(:,jlev)+ztnh_ad*(ztn(:,jlep)/zskap(jlep))
  ztn_ad(:,jlep) = ztn_ad(:,jlep)+ztnh_ad*(zebs3(:,jlev)/zskap(jlep))
  ztn_ad(:,jlev) = ztnh_ad
end do
zebs3(:,1) = zkdiffh2(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
ztn(:,1) = dsigma(1)*zt(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs3(:,jlev) = zkdiffh2(:,jlev)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
  ztn(:,jlev) = (zt(:,jlev)*dsigma(jlev)+zkdiffh2(:,jlem)/zskap(jlem)*ztn(:,jlem))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)&
&*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
end do
zebs3_ad(:,nlem) = zebs3_ad(:,nlem)+ztn_ad(:,nlev)*((zt(:,nlev)*dsigma(nlev)+zkdiffh2(:,nlem)*ztn(:,nlem)/zskap(nlem))*(zkdiffh2(:,&
&nlem)/zskap(nlev)/zskap(nlem))/(dsigma(nlev)+zkdiffh2(:,nlem)/zskap(nlev)*(1.-zebs3(:,nlem)/zskap(nlem)))/(dsigma(nlev)+zkdiffh2(:&
&,nlem)/zskap(nlev)*(1.-zebs3(:,nlem)/zskap(nlem))))
zkdiffh2_ad(:,nlem) = zkdiffh2_ad(:,nlem)+ztn_ad(:,nlev)*((ztn(:,nlem)/zskap(nlem)-(zt(:,nlev)*dsigma(nlev)+zkdiffh2(:,nlem)*ztn(:,&
&nlem)/zskap(nlem))/zskap(nlev)*(1.-zebs3(:,nlem)/zskap(nlem))/(dsigma(nlev)+zkdiffh2(:,nlem)/zskap(nlev)*(1.-zebs3(:,nlem)/&
&zskap(nlem))))/(dsigma(nlev)+zkdiffh2(:,nlem)/zskap(nlev)*(1.-zebs3(:,nlem)/zskap(nlem))))
zt_ad(:,nlev) = zt_ad(:,nlev)+ztn_ad(:,nlev)*(dsigma(nlev)/(dsigma(nlev)+zkdiffh2(:,nlem)/zskap(nlev)*(1.-zebs3(:,nlem)/zskap(nlem)&
&)))
ztn_ad(:,nlem) = ztn_ad(:,nlem)+ztn_ad(:,nlev)*(zkdiffh2(:,nlem)/zskap(nlem)/(dsigma(nlev)+zkdiffh2(:,nlem)/zskap(nlev)*(1.-zebs3(:&
&,nlem)/zskap(nlem))))
ztn_ad(:,nlev) = 0.
zebs3(:,1) = zkdiffh2(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
ztn(:,1) = dsigma(1)*zt(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
do jlev = 2, nlem-1
  jlem = jlev-1
  zebs3(:,jlev) = zkdiffh2(:,jlev)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
  ztn(:,jlev) = (zt(:,jlev)*dsigma(jlev)+zkdiffh2(:,jlem)/zskap(jlem)*ztn(:,jlem))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)&
&*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
end do
do jlev = nlem, 2, -1
!$taf INCOMPLETE zebs3
  jlem = jlev-1
  zebs3(:,jlev) = zkdiffh2(:,jlev)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
  ztni_ad = ztn_ad(:,jlev)
  ztn_ad(:,jlev) = 0.
  zebs3_ad(:,jlem) = zebs3_ad(:,jlem)+ztni_ad*((zt(:,jlev)*dsigma(jlev)+zkdiffh2(:,jlem)/zskap(jlem)*ztn(:,jlem))*(zkdiffh2(:,jlem)&
&/zskap(jlem)/zskap(jlev))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))/&
&(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev)))
  zkdiffh2_ad(:,jlem) = zkdiffh2_ad(:,jlem)+ztni_ad*((1/zskap(jlem)*ztn(:,jlem)-(zt(:,jlev)*dsigma(jlev)+zkdiffh2(:,jlem)/&
&zskap(jlem)*ztn(:,jlem))*((1.-zebs3(:,jlem)/zskap(jlem))/zskap(jlev))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-&
&zebs3(:,jlem)/zskap(jlem)))/zskap(jlev)))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/&
&zskap(jlev)))
  zkdiffh2_ad(:,jlev) = zkdiffh2_ad(:,jlev)-ztni_ad*((zt(:,jlev)*dsigma(jlev)+zkdiffh2(:,jlem)/zskap(jlem)*ztn(:,jlem))/zskap(jlev)&
&/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))/(dsigma(jlev)+(zkdiffh2(:,jlev)+&
&zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev)))
  zt_ad(:,jlev) = zt_ad(:,jlev)+ztni_ad*(dsigma(jlev)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/&
&zskap(jlem)))/zskap(jlev)))
  ztn_ad(:,jlem) = ztn_ad(:,jlem)+ztni_ad*(zkdiffh2(:,jlem)/zskap(jlem)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-&
&zebs3(:,jlem)/zskap(jlem)))/zskap(jlev)))
  zebs3h_ad = zebs3_ad(:,jlev)
  zebs3_ad(:,jlev) = 0.
  zebs3_ad(:,jlem) = zebs3_ad(:,jlem)+zebs3h_ad*(zkdiffh2(:,jlev)*(zkdiffh2(:,jlem)/zskap(jlem)/zskap(jlev))/(dsigma(jlev)+&
&(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)&
&*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev)))
  zkdiffh2_ad(:,jlem) = zkdiffh2_ad(:,jlem)-zebs3h_ad*(zkdiffh2(:,jlev)*((1.-zebs3(:,jlem)/zskap(jlem))/zskap(jlev))/(dsigma(jlev)+&
&(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)&
&*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev)))
  zkdiffh2_ad(:,jlev) = zkdiffh2_ad(:,jlev)+zebs3h_ad*((1-zkdiffh2(:,jlev)/zskap(jlev)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,&
&jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev)))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/&
&zskap(jlem)))/zskap(jlev)))
end do
zkdiffh2_ad(:,1) = zkdiffh2_ad(:,1)-ztn_ad(:,1)*(dsigma(1)*zt(:,1)/zskap(1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))/(dsigma(1)+&
&zkdiffh2(:,1)/zskap(1)))
zt_ad(:,1) = zt_ad(:,1)+ztn_ad(:,1)*(dsigma(1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1)))
ztn_ad(:,1) = 0.
zkdiffh2_ad(:,1) = zkdiffh2_ad(:,1)+zebs3_ad(:,1)*((1-zkdiffh2(:,1)/zskap(1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1)))/(dsigma(1)+&
&zkdiffh2(:,1)/zskap(1)))
zebs3_ad(:,1) = 0.
do jlev = 1, nlem
  zkdiffh_ad(:,jlev) = zkdiffh_ad(:,jlev)+zkdiffh2_ad(:,jlev)*zskaph(jlev)
  zkdiffh2_ad(:,jlev) = 0.
end do
do jlev = 1, nlev
  zdqdt_ad(:,jlev) = zdqdt_ad(:,jlev)+dqdt_ad(:,jlev)
end do
zq_ad(:,1:nlev) = zq_ad(:,1:nlev)-zdqdt_ad(:,1:nlev)/deltsec2
zqn_ad(:,1:nlev) = zqn_ad(:,1:nlev)+zdqdt_ad(:,1:nlev)/deltsec2
zdqdt_ad(:,1:nlev) = 0.
!$taf INCOMPLETE zqn_ad
do jlev = nlem, 2, -1
  jlep = jlev+1
  zqn(:,jlev) = zqn(:,jlev)+zebs2(:,jlev)*zqn(:,jlep)
end do
do jlev = 1, nlem
  jlep = jlev+1
  zqnh_ad = zqn_ad(:,jlev)
  zebs2_ad(:,jlev) = zebs2_ad(:,jlev)+zqnh_ad*zqn(:,jlep)
  zqn_ad(:,jlep) = zqn_ad(:,jlep)+zqnh_ad*zebs2(:,jlev)
  zqn_ad(:,jlev) = zqnh_ad
end do
if (ndheat > 0) then
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
  end do
endif
zebs2(:,1) = zkdiffh(:,1)/(dsigma(1)+zkdiffh(:,1))
zqn(:,1) = dsigma(1)*zq(:,1)/(dsigma(1)+zkdiffh(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs2(:,jlev) = zkdiffh(:,jlev)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem)))
  zqn(:,jlev) = (zq(:,jlev)*dsigma(jlev)+zkdiffh(:,jlem)*zqn(:,jlem))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,&
&jlem)))
end do
zebs2_ad(:,nlem) = zebs2_ad(:,nlem)+zqn_ad(:,nlev)*((zq(:,nlev)*dsigma(nlev)+zkdiffh(:,nlem)*zqn(:,nlem))*zkdiffh(:,nlem)/&
&(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem)))/(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem))))
zkdiffh_ad(:,nlem) = zkdiffh_ad(:,nlem)+zqn_ad(:,nlev)*((zqn(:,nlem)-(zq(:,nlev)*dsigma(nlev)+zkdiffh(:,nlem)*zqn(:,nlem))*(1.-&
&zebs2(:,nlem))/(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem))))/(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem))))
zq_ad(:,nlev) = zq_ad(:,nlev)+zqn_ad(:,nlev)*(dsigma(nlev)/(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem))))
zqn_ad(:,nlem) = zqn_ad(:,nlem)+zqn_ad(:,nlev)*(zkdiffh(:,nlem)/(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem))))
zqn_ad(:,nlev) = 0.
if (ndheat > 0) then
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
  end do
endif
zebs2(:,1) = zkdiffh(:,1)/(dsigma(1)+zkdiffh(:,1))
zqn(:,1) = dsigma(1)*zq(:,1)/(dsigma(1)+zkdiffh(:,1))
do jlev = 2, nlem-1
  jlem = jlev-1
  zebs2(:,jlev) = zkdiffh(:,jlev)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem)))
  zqn(:,jlev) = (zq(:,jlev)*dsigma(jlev)+zkdiffh(:,jlem)*zqn(:,jlem))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,&
&jlem)))
end do
do jlev = nlem, 2, -1
!$taf INCOMPLETE zebs2
  jlem = jlev-1
  zebs2(:,jlev) = zkdiffh(:,jlev)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem)))
  zqni_ad = zqn_ad(:,jlev)
  zqn_ad(:,jlev) = 0.
  zebs2_ad(:,jlem) = zebs2_ad(:,jlem)+zqni_ad*((zq(:,jlev)*dsigma(jlev)+zkdiffh(:,jlem)*zqn(:,jlem))*zkdiffh(:,jlem)/(dsigma(jlev)+&
&zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem)))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))
  zkdiffh_ad(:,jlem) = zkdiffh_ad(:,jlem)+zqni_ad*((zqn(:,jlem)-(zq(:,jlev)*dsigma(jlev)+zkdiffh(:,jlem)*zqn(:,jlem))*(1.-zebs2(:,&
&jlem))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-&
&zebs2(:,jlem))))
  zkdiffh_ad(:,jlev) = zkdiffh_ad(:,jlev)-zqni_ad*((zq(:,jlev)*dsigma(jlev)+zkdiffh(:,jlem)*zqn(:,jlem))/(dsigma(jlev)+zkdiffh(:,&
&jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem)))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))
  zq_ad(:,jlev) = zq_ad(:,jlev)+zqni_ad*(dsigma(jlev)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))
  zqn_ad(:,jlem) = zqn_ad(:,jlem)+zqni_ad*(zkdiffh(:,jlem)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))
  zebs2h_ad = zebs2_ad(:,jlev)
  zebs2_ad(:,jlev) = 0.
  zebs2_ad(:,jlem) = zebs2_ad(:,jlem)+zebs2h_ad*(zkdiffh(:,jlev)*zkdiffh(:,jlem)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-&
&zebs2(:,jlem)))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))
  zkdiffh_ad(:,jlem) = zkdiffh_ad(:,jlem)-zebs2h_ad*(zkdiffh(:,jlev)*(1.-zebs2(:,jlem))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,&
&jlem)*(1.-zebs2(:,jlem)))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))
  zkdiffh_ad(:,jlev) = zkdiffh_ad(:,jlev)+zebs2h_ad*((1-zkdiffh(:,jlev)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,&
&jlem))))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem))))
end do
zkdiffh_ad(:,1) = zkdiffh_ad(:,1)-zqn_ad(:,1)*(dsigma(1)*zq(:,1)/(dsigma(1)+zkdiffh(:,1))/(dsigma(1)+zkdiffh(:,1)))
zq_ad(:,1) = zq_ad(:,1)+zqn_ad(:,1)*(dsigma(1)/(dsigma(1)+zkdiffh(:,1)))
zqn_ad(:,1) = 0.
zkdiffh_ad(:,1) = zkdiffh_ad(:,1)+zebs2_ad(:,1)*((1-zkdiffh(:,1)/(dsigma(1)+zkdiffh(:,1)))/(dsigma(1)+zkdiffh(:,1)))
zebs2_ad(:,1) = 0.
!$taf INCOMPLETE zebs2,zken,zken_ad
if (ndheat > 0) then
!$taf INCOMPLETE zebs2,zken,zken_ad
  zke(:,:) = 0.5*zabsu(:,:)*zabsu(:,:)
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  zken(:,1) = dsigma(1)*zke(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
    zken(:,jlev) = (zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs2(:,jlem)))
  end do
  zken(:,nlev) = (zke(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zken(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem)))
  do jlev = nlem, 1, -1
    jlep = jlev+1
    zken(:,jlev) = zken(:,jlev)+zebs2(:,jlev)*zken(:,jlep)
  end do
  zdtdt_ad(:,1:nlev) = 0.
  zdtdt_ad(:,1:nlev) = zdtdt_ad(:,1:nlev)+dtdt_ad(:,1:nlev)
  dq_ad(:,1:nlev) = dq_ad(:,1:nlev)+zdtdt_ad(:,1:nlev)*(0.5*((zun(:,1:nlev)*zun(:,1:nlev)-zu(:,1:nlev)*zu(:,1:nlev)+zvn(:,1:nlev)*&
&zvn(:,1:nlev)-zv(:,1:nlev)*zv(:,1:nlev))/deltsec2-(zken(:,1:nlev)-zke(:,1:nlev))/deltsec2)/acpd*adv/(1.+adv*dq(:,1:nlev))/(1.+&
&adv*dq(:,1:nlev)))
  zke_ad(:,1:nlev) = zke_ad(:,1:nlev)+zdtdt_ad(:,1:nlev)*(0.5*((-1)/deltsec2)/acpd/(1.+adv*dq(:,1:nlev)))
  zken_ad(:,1:nlev) = zken_ad(:,1:nlev)+zdtdt_ad(:,1:nlev)*(0.5*(1/deltsec2)/acpd/(1.+adv*dq(:,1:nlev)))
  zu_ad(:,1:nlev) = zu_ad(:,1:nlev)+zdtdt_ad(:,1:nlev)*(0.5*(2*zu(:,1:nlev)/deltsec2)/acpd/(1.+adv*dq(:,1:nlev)))
  zun_ad(:,1:nlev) = zun_ad(:,1:nlev)-zdtdt_ad(:,1:nlev)*(0.5*(2*zun(:,1:nlev)/deltsec2)/acpd/(1.+adv*dq(:,1:nlev)))
  zv_ad(:,1:nlev) = zv_ad(:,1:nlev)+zdtdt_ad(:,1:nlev)*(0.5*(2*zv(:,1:nlev)/deltsec2)/acpd/(1.+adv*dq(:,1:nlev)))
  zvn_ad(:,1:nlev) = zvn_ad(:,1:nlev)-zdtdt_ad(:,1:nlev)*(0.5*(2*zvn(:,1:nlev)/deltsec2)/acpd/(1.+adv*dq(:,1:nlev)))
  zdtdt_ad(:,1:nlev) = 0.
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  zken(:,1) = dsigma(1)*zke(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
    zken(:,jlev) = (zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs2(:,jlem)))
  end do
  zken(:,nlev) = (zke(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zken(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem)))
!$taf INCOMPLETE zken_ad
  do jlev = nlem, 2, -1
    jlep = jlev+1
    zken(:,jlev) = zken(:,jlev)+zebs2(:,jlev)*zken(:,jlep)
  end do
  do jlev = 1, nlem
    jlep = jlev+1
    zkenh_ad = zken_ad(:,jlev)
    zebs2_ad(:,jlev) = zebs2_ad(:,jlev)+zkenh_ad*zken(:,jlep)
    zken_ad(:,jlep) = zken_ad(:,jlep)+zkenh_ad*zebs2(:,jlev)
    zken_ad(:,jlev) = zkenh_ad
  end do
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  zken(:,1) = dsigma(1)*zke(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
    zken(:,jlev) = (zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs2(:,jlem)))
  end do
  zebs2_ad(:,nlem) = zebs2_ad(:,nlem)+zken_ad(:,nlev)*((zke(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zken(:,nlem))*zkdiffm(:,nlem)/&
&(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem)))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem))))
  zkdiffm_ad(:,nlem) = zkdiffm_ad(:,nlem)+zken_ad(:,nlev)*((zken(:,nlem)-(zke(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zken(:,nlem))*&
&(1.-zebs2(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem))))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem))))
  zke_ad(:,nlev) = zke_ad(:,nlev)+zken_ad(:,nlev)*(dsigma(nlev)/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem))))
  zken_ad(:,nlem) = zken_ad(:,nlem)+zken_ad(:,nlev)*(zkdiffm(:,nlem)/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem))))
  zken_ad(:,nlev) = 0.
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  zken(:,1) = dsigma(1)*zke(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem-1
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
    zken(:,jlev) = (zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs2(:,jlem)))
  end do
  do jlev = nlem, 2, -1
!$taf INCOMPLETE zebs2
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
    zkeni_ad = zken_ad(:,jlev)
    zken_ad(:,jlev) = 0.
    zebs2_ad(:,jlem) = zebs2_ad(:,jlem)+zkeni_ad*((zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))*zkdiffm(:,jlem)/&
&(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,&
&jlem))))
    zkdiffm_ad(:,jlem) = zkdiffm_ad(:,jlem)+zkeni_ad*((zken(:,jlem)-(zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))*(1.-&
&zebs2(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem))))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,&
&jlem)*(1.-zebs2(:,jlem))))
    zkdiffm_ad(:,jlev) = zkdiffm_ad(:,jlev)-zkeni_ad*((zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))/(dsigma(jlev)+&
&zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem))))
    zke_ad(:,jlev) = zke_ad(:,jlev)+zkeni_ad*(dsigma(jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem))))
    zken_ad(:,jlem) = zken_ad(:,jlem)+zkeni_ad*(zkdiffm(:,jlem)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem))))
    zebs2i_ad = zebs2_ad(:,jlev)
    zebs2_ad(:,jlev) = 0.
    zebs2_ad(:,jlem) = zebs2_ad(:,jlem)+zebs2i_ad*(zkdiffm(:,jlev)*zkdiffm(:,jlem)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*&
&(1.-zebs2(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem))))
    zkdiffm_ad(:,jlem) = zkdiffm_ad(:,jlem)-zebs2i_ad*(zkdiffm(:,jlev)*(1.-zebs2(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,&
&jlem)*(1.-zebs2(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem))))
    zkdiffm_ad(:,jlev) = zkdiffm_ad(:,jlev)+zebs2i_ad*((1-zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:&
&,jlem))))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem))))
  end do
  zkdiffm_ad(:,1) = zkdiffm_ad(:,1)-zken_ad(:,1)*(dsigma(1)*zke(:,1)/(dsigma(1)+zkdiffm(:,1))/(dsigma(1)+zkdiffm(:,1)))
  zke_ad(:,1) = zke_ad(:,1)+zken_ad(:,1)*(dsigma(1)/(dsigma(1)+zkdiffm(:,1)))
  zken_ad(:,1) = 0.
  zkdiffm_ad(:,1) = zkdiffm_ad(:,1)+zebs2_ad(:,1)*((1-zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1)))/(dsigma(1)+zkdiffm(:,1)))
  zebs2_ad(:,1) = 0.
  zabsu_ad(:,:) = zabsu_ad(:,:)+zke_ad(:,:)*zabsu(:,:)
  zke_ad(:,:) = 0.
endif
zdvdt_ad(:,1:nlev) = zdvdt_ad(:,1:nlev)+dvdt_ad(:,1:nlev)
zdudt_ad(:,1:nlev) = zdudt_ad(:,1:nlev)+dudt_ad(:,1:nlev)
zv_ad(:,1:nlev) = zv_ad(:,1:nlev)-zdvdt_ad(:,1:nlev)/deltsec2
zvn_ad(:,1:nlev) = zvn_ad(:,1:nlev)+zdvdt_ad(:,1:nlev)/deltsec2
zdvdt_ad(:,1:nlev) = 0.
zu_ad(:,1:nlev) = zu_ad(:,1:nlev)-zdudt_ad(:,1:nlev)/deltsec2
zun_ad(:,1:nlev) = zun_ad(:,1:nlev)+zdudt_ad(:,1:nlev)/deltsec2
zdudt_ad(:,1:nlev) = 0.
zebs(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
zun(:,1) = dsigma(1)*zu(:,1)/(dsigma(1)+zkdiffm(:,1))
zvn(:,1) = dsigma(1)*zv(:,1)/(dsigma(1)+zkdiffm(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))
  zun(:,jlev) = (zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
  zvn(:,jlev) = (zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
end do
zun(:,nlev) = (zu(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zun(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))
zvn(:,nlev) = (zv(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zvn(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))
!$taf INCOMPLETE zun_ad
do jlev = nlem, 2, -1
  jlep = jlev+1
  zun(:,jlev) = zun(:,jlev)+zebs(:,jlev)*zun(:,jlep)
  zvn(:,jlev) = zvn(:,jlev)+zebs(:,jlev)*zvn(:,jlep)
end do
do jlev = 1, nlem
  jlep = jlev+1
  zvnh_ad = zvn_ad(:,jlev)
  zebs_ad(:,jlev) = zebs_ad(:,jlev)+zvnh_ad*zvn(:,jlep)
  zvn_ad(:,jlep) = zvn_ad(:,jlep)+zvnh_ad*zebs(:,jlev)
  zvn_ad(:,jlev) = zvnh_ad
  zunh_ad = zun_ad(:,jlev)
  zebs_ad(:,jlev) = zebs_ad(:,jlev)+zunh_ad*zun(:,jlep)
  zun_ad(:,jlep) = zun_ad(:,jlep)+zunh_ad*zebs(:,jlev)
  zun_ad(:,jlev) = zunh_ad
end do
zebs(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
zvn(:,1) = dsigma(1)*zv(:,1)/(dsigma(1)+zkdiffm(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))
  zvn(:,jlev) = (zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
end do
zebs_ad(:,nlem) = zebs_ad(:,nlem)+zvn_ad(:,nlev)*((zv(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zvn(:,nlem))*zkdiffm(:,nlem)/&
&(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zkdiffm_ad(:,nlem) = zkdiffm_ad(:,nlem)+zvn_ad(:,nlev)*((zvn(:,nlem)-(zv(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zvn(:,nlem))*(1.-&
&zebs(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zv_ad(:,nlev) = zv_ad(:,nlev)+zvn_ad(:,nlev)*(dsigma(nlev)/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zvn_ad(:,nlem) = zvn_ad(:,nlem)+zvn_ad(:,nlev)*(zkdiffm(:,nlem)/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zvn_ad(:,nlev) = 0.
zebs(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
zun(:,1) = dsigma(1)*zu(:,1)/(dsigma(1)+zkdiffm(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))
  zun(:,jlev) = (zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
end do
zebs_ad(:,nlem) = zebs_ad(:,nlem)+zun_ad(:,nlev)*((zu(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zun(:,nlem))*zkdiffm(:,nlem)/&
&(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zkdiffm_ad(:,nlem) = zkdiffm_ad(:,nlem)+zun_ad(:,nlev)*((zun(:,nlem)-(zu(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zun(:,nlem))*(1.-&
&zebs(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zu_ad(:,nlev) = zu_ad(:,nlev)+zun_ad(:,nlev)*(dsigma(nlev)/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zun_ad(:,nlem) = zun_ad(:,nlem)+zun_ad(:,nlev)*(zkdiffm(:,nlem)/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem))))
zun_ad(:,nlev) = 0.
zebs(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
zun(:,1) = dsigma(1)*zu(:,1)/(dsigma(1)+zkdiffm(:,1))
zvn(:,1) = dsigma(1)*zv(:,1)/(dsigma(1)+zkdiffm(:,1))
do jlev = 2, nlem-1
  jlem = jlev-1
  zebs(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))
  zun(:,jlev) = (zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
  zvn(:,jlev) = (zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
end do
do jlev = nlem, 2, -1
!$taf INCOMPLETE zebs
  jlem = jlev-1
  zebs(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))
  zvni_ad = zvn_ad(:,jlev)
  zvn_ad(:,jlev) = 0.
  zebs_ad(:,jlem) = zebs_ad(:,jlem)+zvni_ad*((zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))*zkdiffm(:,jlem)/(dsigma(jlev)+&
&zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zkdiffm_ad(:,jlem) = zkdiffm_ad(:,jlem)+zvni_ad*((zvn(:,jlem)-(zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))*(1.-zebs(:,&
&jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs(:,jlem))))
  zkdiffm_ad(:,jlev) = zkdiffm_ad(:,jlev)-zvni_ad*((zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))/(dsigma(jlev)+zkdiffm(:,&
&jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zv_ad(:,jlev) = zv_ad(:,jlev)+zvni_ad*(dsigma(jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zvn_ad(:,jlem) = zvn_ad(:,jlem)+zvni_ad*(zkdiffm(:,jlem)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zuni_ad = zun_ad(:,jlev)
  zun_ad(:,jlev) = 0.
  zebs_ad(:,jlem) = zebs_ad(:,jlem)+zuni_ad*((zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))*zkdiffm(:,jlem)/(dsigma(jlev)+&
&zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zkdiffm_ad(:,jlem) = zkdiffm_ad(:,jlem)+zuni_ad*((zun(:,jlem)-(zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))*(1.-zebs(:,&
&jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs(:,jlem))))
  zkdiffm_ad(:,jlev) = zkdiffm_ad(:,jlev)-zuni_ad*((zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))/(dsigma(jlev)+zkdiffm(:,&
&jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zu_ad(:,jlev) = zu_ad(:,jlev)+zuni_ad*(dsigma(jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zun_ad(:,jlem) = zun_ad(:,jlem)+zuni_ad*(zkdiffm(:,jlem)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zebsh_ad = zebs_ad(:,jlev)
  zebs_ad(:,jlev) = 0.
  zebs_ad(:,jlem) = zebs_ad(:,jlem)+zebsh_ad*(zkdiffm(:,jlev)*zkdiffm(:,jlem)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zkdiffm_ad(:,jlem) = zkdiffm_ad(:,jlem)-zebsh_ad*(zkdiffm(:,jlev)*(1.-zebs(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)&
&*(1.-zebs(:,jlem)))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
  zkdiffm_ad(:,jlev) = zkdiffm_ad(:,jlev)+zebsh_ad*((1-zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem))))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem))))
end do
zkdiffm_ad(:,1) = zkdiffm_ad(:,1)-zvn_ad(:,1)*(dsigma(1)*zv(:,1)/(dsigma(1)+zkdiffm(:,1))/(dsigma(1)+zkdiffm(:,1)))
zv_ad(:,1) = zv_ad(:,1)+zvn_ad(:,1)*(dsigma(1)/(dsigma(1)+zkdiffm(:,1)))
zvn_ad(:,1) = 0.
zkdiffm_ad(:,1) = zkdiffm_ad(:,1)-zun_ad(:,1)*(dsigma(1)*zu(:,1)/(dsigma(1)+zkdiffm(:,1))/(dsigma(1)+zkdiffm(:,1)))
zu_ad(:,1) = zu_ad(:,1)+zun_ad(:,1)*(dsigma(1)/(dsigma(1)+zkdiffm(:,1)))
zun_ad(:,1) = 0.
zkdiffm_ad(:,1) = zkdiffm_ad(:,1)+zebs_ad(:,1)*((1-zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1)))/(dsigma(1)+zkdiffm(:,1)))
zebs_ad(:,1) = 0.
do jlev = 1, nlem
  zdenom_ad = 0.
  zdenomh_ad = 0.
  zdenomm_ad = 0.
  zdthds_ad = 0.
  zdvds_ad = 0.
  zqf1_ad = 0.
  zqf2_ad = 0.
  zri_ad = 0.
  zrifh_ad = 0.
  zrifm_ad = 0.
  zrthl_ad = 0.
  jlp = jlev+1
  zzlev = -(gascon*ztscal*alog(sigmah(jlev))/ga)
  zdz = gascon*ztscal*alog(sigma(jlp)/sigma(jlev))/ga
  zmixh = zlamh*vonkarman*zzlev/(zlamh+vonkarman*zzlev)
  zmixm = vdiff_lamm*vonkarman*zzlev/(vdiff_lamm+vonkarman*zzlev)
  zmixh2 = zmixh*zmixh
  zmixm2 = zmixm*zmixm
  zrdsig = 1./(sigma(jlp)-sigma(jlev))
  zfac = zkonst3*sigmah(jlev)*sigmah(jlev)*sigmah(jlev)*zrdsig
  zzkfac = sqrt(((((zzlev+zdz)/zzlev)**(1./3.)-1.)/zdz)**3/zzlev)
  do jhor = 1, nhor
    zdenom_ad = 0.
    zdenomh_ad = 0.
    zdenomm_ad = 0.
    zdthds_ad = 0.
    zdvds_ad = 0.
    zqf1_ad = 0.
    zqf2_ad = 0.
    zri_ad = 0.
    zrifh_ad = 0.
    zrifm_ad = 0.
    zrthl_ad = 0.
    zrthl = (dsigma(jlp)+dsigma(jlev))/(zt(jhor,jlev)*dsigma(jlp)+zt(jhor,jlp)*dsigma(jlev))
    zdvds = amax1(zumin,abs(zabsu(jhor,jlev)-zabsu(jhor,jlp)))*zrdsig
    zqf1 = 1.+(1./rdbrv-1.)*zq(jhor,jlev)
    zqf2 = 1.+(1./rdbrv-1.)*zq(jhor,jlp)
    zdthds = (zt(jhor,jlev)*zqf1/zskap(jlev)-zt(jhor,jlp)*zqf2/zskap(jlp))*zrdsig
    zri = zskaph(jlev)*gascon*zdthds/(sigmah(jlev)*zdvds*zdvds)
    if (zri <= 0.) then
      zdenomh = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri))*zzkfac*zmixh2
      zdenomm = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri))*zzkfac*zmixm2
      zrifh = 1.-3.*vdiff_b*zri/zdenomh
      zrifm = 1.-2.*vdiff_b*zri/zdenomm
    else
      zdenom = sqrt(1+vdiff_d*zri)
      zrifh = 1./(1.+3.*vdiff_b*zri*zdenom)
      zrifm = 1./(1.+2.*vdiff_b*zri/zdenom)
    endif
    zdvds_ad = zdvds_ad+zkdiffm_ad(jhor,jlev)*zfac*zmixm2*zrifm*zrthl*zrthl*zrthl
    zrifm_ad = zrifm_ad+zkdiffm_ad(jhor,jlev)*zfac*zmixm2*zdvds*zrthl*zrthl*zrthl
    zrthl_ad = zrthl_ad+3*zkdiffm_ad(jhor,jlev)*(zfac*zmixm2*zrifm*zdvds*zrthl)*zrthl
    zkdiffm_ad(jhor,jlev) = 0.
    zdvds_ad = zdvds_ad+zkdiffh_ad(jhor,jlev)*zfac*zmixh2*zrifh*zrthl*zrthl*zrthl
    zrifh_ad = zrifh_ad+zkdiffh_ad(jhor,jlev)*zfac*zmixh2*zdvds*zrthl*zrthl*zrthl
    zrthl_ad = zrthl_ad+3*zkdiffh_ad(jhor,jlev)*(zfac*zmixh2*zrifh*zdvds*zrthl)*zrthl
    zkdiffh_ad(jhor,jlev) = 0.
    if (zri <= 0.) then
      zdenomm_ad = zdenomm_ad+zrifm_ad*(2.*vdiff_b*zri/zdenomm/zdenomm)
      zri_ad = zri_ad-zrifm_ad*(2*vdiff_b/zdenomm)
      zrifm_ad = 0.
      zdenomh_ad = zdenomh_ad+zrifh_ad*(3.*vdiff_b*zri/zdenomh/zdenomh)
      zri_ad = zri_ad-zrifh_ad*(3*vdiff_b/zdenomh)
      zrifh_ad = 0.
      zri_ad = zri_ad-3.*zdenomm_ad*vdiff_c*vdiff_b*(1./(2.*sqrt(-(1.*zri))))*zzkfac*zmixm2
      zdenomm_ad = 0.
      zri_ad = zri_ad-3.*zdenomh_ad*vdiff_c*vdiff_b*(1./(2.*sqrt(-(1.*zri))))*zzkfac*zmixh2
      zdenomh_ad = 0.
    else
      zdenom_ad = zdenom_ad+zrifm_ad*(1.*(2.*vdiff_b*zri/zdenom/zdenom)/(1.+2.*vdiff_b*zri/zdenom)/(1.+2.*vdiff_b*zri/zdenom))
      zri_ad = zri_ad-zrifm_ad*(1.*(2*vdiff_b/zdenom)/(1.+2.*vdiff_b*zri/zdenom)/(1.+2.*vdiff_b*zri/zdenom))
      zrifm_ad = 0.
      zdenom_ad = zdenom_ad-zrifh_ad*(1.*(3.*vdiff_b*zri)/(1.+3.*vdiff_b*zri*zdenom)/(1.+3.*vdiff_b*zri*zdenom))
      zri_ad = zri_ad-zrifh_ad*(1.*(3*vdiff_b*zdenom)/(1.+3.*vdiff_b*zri*zdenom)/(1.+3.*vdiff_b*zri*zdenom))
      zrifh_ad = 0.
      zri_ad = zri_ad+zdenom_ad*(1./(2.*sqrt(1+vdiff_d*zri)))*vdiff_d
      zdenom_ad = 0.
    endif
    zdthds_ad = zdthds_ad !+zri_ad*(zskaph(jlev)*gascon/(sigmah(jlev)*zdvds*zdvds))
    zdvds_ad = zdvds_ad!-zri_ad*(2*(zskaph(jlev)*gascon*zdthds)*sigmah(jlev)*zdvds/(sigmah(jlev)*zdvds*zdvds)/(sigmah(jlev)*zdvds*&
!&zdvds))
    zri_ad = 0.
    zqf1_ad = zqf1_ad+zdthds_ad*(zt(jhor,jlev)/zskap(jlev))*zrdsig
    zqf2_ad = zqf2_ad-zdthds_ad*(zt(jhor,jlp)/zskap(jlp))*zrdsig
    zt_ad(jhor,jlev) = zt_ad(jhor,jlev)+zdthds_ad*(zqf1/zskap(jlev))*zrdsig
    zt_ad(jhor,jlp) = zt_ad(jhor,jlp)-zdthds_ad*(zqf2/zskap(jlp))*zrdsig
    zdthds_ad = 0.
    zq_ad(jhor,jlp) = zq_ad(jhor,jlp)+zqf2_ad*((-1)+1./rdbrv)
    zqf2_ad = 0.
    zq_ad(jhor,jlev) = zq_ad(jhor,jlev)+zqf1_ad*((-1)+1./rdbrv)
    zqf1_ad = 0.
    zdvdsh = zabsu(jhor,jlev)-zabsu(jhor,jlp)
    zdvdsh_ad = 0._8
    zdvdsi_ad = 0._8
    zdvdsi_ad = zdvds_ad*zrdsig*(0.5-sign(0.5,zumin-abs(zdvdsh)))
    zdvdsh_ad = zdvdsi_ad*sign(1.,zdvdsh)
    zabsu_ad(jhor,jlev) = zabsu_ad(jhor,jlev)+zdvdsh_ad
    zabsu_ad(jhor,jlp) = zabsu_ad(jhor,jlp)-zdvdsh_ad
    zdvds_ad = 0.
    zt_ad(jhor,jlev) = zt_ad(jhor,jlev)-zrthl_ad*((dsigma(jlp)+dsigma(jlev))*dsigma(jlp)/(zt(jhor,jlev)*dsigma(jlp)+zt(jhor,jlp)*&
&dsigma(jlev))/(zt(jhor,jlev)*dsigma(jlp)+zt(jhor,jlp)*dsigma(jlev)))
    zt_ad(jhor,jlp) = zt_ad(jhor,jlp)-zrthl_ad*((dsigma(jlp)+dsigma(jlev))*dsigma(jlev)/(zt(jhor,jlev)*dsigma(jlp)+zt(jhor,jlp)*&
&dsigma(jlev))/(zt(jhor,jlev)*dsigma(jlp)+zt(jhor,jlp)*dsigma(jlev)))
    zrthl_ad = 0.
  end do
end do
zu_ad(:,1:nlev) = zu_ad(:,1:nlev)+2*zabsu_ad(:,:)*(1./(2.*sqrt(zu(:,1:nlev)**2+zv(:,1:nlev)**2)))*zu(:,1:nlev)
zv_ad(:,1:nlev) = zv_ad(:,1:nlev)+2*zabsu_ad(:,:)*(1./(2.*sqrt(zu(:,1:nlev)**2+zv(:,1:nlev)**2)))*zv(:,1:nlev)
zabsu_ad(:,:) = 0.
dv_ad(:,1:nlev) = dv_ad(:,1:nlev)+zv_ad(:,:)
dvdt_ad(:,1:nlev) = dvdt_ad(:,1:nlev)+zv_ad(:,:)*deltsec2
zv_ad(:,:) = 0.
du_ad(:,1:nlev) = du_ad(:,1:nlev)+zu_ad(:,:)
dudt_ad(:,1:nlev) = dudt_ad(:,1:nlev)+zu_ad(:,:)*deltsec2
zu_ad(:,:) = 0.
dq_ad(:,1:nlev) = dq_ad(:,1:nlev)+zq_ad(:,:)
dqdt_ad(:,1:nlev) = dqdt_ad(:,1:nlev)+zq_ad(:,:)*deltsec2
zq_ad(:,:) = 0.
dt_ad(:,1:nlev) = dt_ad(:,1:nlev)+zt_ad(:,:)
dtdt_ad(:,1:nlev) = dtdt_ad(:,1:nlev)+zt_ad(:,:)*deltsec2
zt_ad(:,:) = 0.

end subroutine vdiff_ad

subroutine vdiff()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use fluxmod

implicit none

!==============================================
! declare parameters
!==============================================
real, parameter :: ztscal = 250.

!==============================================
! declare local variables
!==============================================
integer :: jhor
integer :: jlem
integer :: jlep
integer :: jlev
integer :: jlp
real :: zabsu(nhor,nlev)
real :: zdenom
real :: zdenomh
real :: zdenomm
real :: zdqdt(nhor,nlev)
real :: zdtdt(nhor,nlev)
real :: zdthds
real :: zdudt(nhor,nlev)
real :: zdvds
real :: zdvdt(nhor,nlev)
real :: zdz
real :: zebs(nhor,nlem)
real :: zebs2(nhor,nlem)
real :: zebs3(nhor,nlem)
real :: zfac
real :: zkdiffh(nhor,nlem)
real :: zkdiffh2(nhor,nlem)
real :: zkdiffm(nhor,nlem)
real :: zke(nhor,nlev)
real :: zken(nhor,nlev)
real :: zkonst1
real :: zkonst2
real :: zkonst3
real :: zlamh
real :: zmixh
real :: zmixh2
real :: zmixm
real :: zmixm2
real :: zq(nhor,nlev)
real :: zqf1
real :: zqf2
real :: zqn(nhor,nlev)
real :: zrdsig
real :: zri
real :: zrifh
real :: zrifm
real :: zrthl
real :: zskap(nlev)
real :: zskaph(nlev)
real :: zt(nhor,nlev)
real :: ztn(nhor,nlev)
real :: zu(nhor,nlev)
real :: zun(nhor,nlev)
real :: zv(nhor,nlev)
real :: zvn(nhor,nlev)
real :: zzkfac
real :: zzlev

zlamh = vdiff_lamm*sqrt(3.*vdiff_d*0.5)
zkonst1 = ga*deltsec2/gascon
zkonst2 = zkonst1*ga/gascon
zkonst3 = zkonst2*ga/gascon
zskap(:) = sigma(:)**akap
zskaph(:) = sigmah(:)**akap
zt(:,:) = dt(:,1:nlev)+dtdt(:,1:nlev)*deltsec2
zq(:,:) = dq(:,1:nlev)+dqdt(:,1:nlev)*deltsec2
zu(:,:) = du(:,1:nlev)+dudt(:,1:nlev)*deltsec2
zv(:,:) = dv(:,1:nlev)+dvdt(:,1:nlev)*deltsec2
zabsu(:,:) = sqrt(zu(:,1:nlev)**2+zv(:,1:nlev)**2)
do jlev = 1, nlem
  jlp = jlev+1
  zzlev = -(gascon*ztscal*alog(sigmah(jlev))/ga)
  zdz = gascon*ztscal*alog(sigma(jlp)/sigma(jlev))/ga
  zmixh = zlamh*vonkarman*zzlev/(zlamh+vonkarman*zzlev)
  zmixm = vdiff_lamm*vonkarman*zzlev/(vdiff_lamm+vonkarman*zzlev)
  zmixh2 = zmixh*zmixh
  zmixm2 = zmixm*zmixm
  zrdsig = 1./(sigma(jlp)-sigma(jlev))
  zfac = zkonst3*sigmah(jlev)*sigmah(jlev)*sigmah(jlev)*zrdsig
  zzkfac = sqrt(((((zzlev+zdz)/zzlev)**(1./3.)-1.)/zdz)**3/zzlev)
  do jhor = 1, nhor
    zrthl = (dsigma(jlp)+dsigma(jlev))/(zt(jhor,jlev)*dsigma(jlp)+zt(jhor,jlp)*dsigma(jlev))
    zdvds = amax1(zumin,abs(zabsu(jhor,jlev)-zabsu(jhor,jlp)))*zrdsig
    zqf1 = 1.+(1./rdbrv-1.)*zq(jhor,jlev)
    zqf2 = 1.+(1./rdbrv-1.)*zq(jhor,jlp)
    zdthds = (zt(jhor,jlev)*zqf1/zskap(jlev)-zt(jhor,jlp)*zqf2/zskap(jlp))*zrdsig
    zri = zskaph(jlev)*gascon*zdthds/(sigmah(jlev)*zdvds*zdvds)
    if (zri <= 0.) then
      zdenomh = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri))*zzkfac*zmixh2
      zdenomm = 1.+3.*vdiff_c*vdiff_b*sqrt(-(1.*zri))*zzkfac*zmixm2
      zrifh = 1.-3.*vdiff_b*zri/zdenomh
      zrifm = 1.-2.*vdiff_b*zri/zdenomm
    else
      zdenom = sqrt(1+vdiff_d*zri)
      zrifh = 1./(1.+3.*vdiff_b*zri*zdenom)
      zrifm = 1./(1.+2.*vdiff_b*zri/zdenom)
    endif
    zkdiffh(jhor,jlev) = zfac*zmixh2*zrifh*zdvds*zrthl*zrthl*zrthl
    zkdiffm(jhor,jlev) = zfac*zmixm2*zrifm*zdvds*zrthl*zrthl*zrthl
  end do
end do
zebs(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
zun(:,1) = dsigma(1)*zu(:,1)/(dsigma(1)+zkdiffm(:,1))
zvn(:,1) = dsigma(1)*zv(:,1)/(dsigma(1)+zkdiffm(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,jlem)))
  zun(:,jlev) = (zu(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zun(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
  zvn(:,jlev) = (zv(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zvn(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs(:,&
&jlem)))
end do
zun(:,nlev) = (zu(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zun(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))
zvn(:,nlev) = (zv(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zvn(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs(:,nlem)))
!$taf INCOMPLETE zun
do jlev = nlem, 1, -1
  jlep = jlev+1
  zun(:,jlev) = zun(:,jlev)+zebs(:,jlev)*zun(:,jlep)
  zvn(:,jlev) = zvn(:,jlev)+zebs(:,jlev)*zvn(:,jlep)
end do
zdudt(:,1:nlev) = (zun(:,1:nlev)-zu(:,1:nlev))/deltsec2
zdvdt(:,1:nlev) = (zvn(:,1:nlev)-zv(:,1:nlev))/deltsec2
dudt(:,1:nlev) = dudt(:,1:nlev)+zdudt(:,1:nlev)
dvdt(:,1:nlev) = dvdt(:,1:nlev)+zdvdt(:,1:nlev)
if (ndheat > 0) then
  zke(:,:) = 0.5*zabsu(:,:)*zabsu(:,:)
  zebs2(:,1) = zkdiffm(:,1)/(dsigma(1)+zkdiffm(:,1))
  zken(:,1) = dsigma(1)*zke(:,1)/(dsigma(1)+zkdiffm(:,1))
  do jlev = 2, nlem
    jlem = jlev-1
    zebs2(:,jlev) = zkdiffm(:,jlev)/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-zebs2(:,jlem)))
    zken(:,jlev) = (zke(:,jlev)*dsigma(jlev)+zkdiffm(:,jlem)*zken(:,jlem))/(dsigma(jlev)+zkdiffm(:,jlev)+zkdiffm(:,jlem)*(1.-&
&zebs2(:,jlem)))
  end do
  zken(:,nlev) = (zke(:,nlev)*dsigma(nlev)+zkdiffm(:,nlem)*zken(:,nlem))/(dsigma(nlev)+zkdiffm(:,nlem)*(1.-zebs2(:,nlem)))
!$taf INCOMPLETE zken
  do jlev = nlem, 1, -1
    jlep = jlev+1
    zken(:,jlev) = zken(:,jlev)+zebs2(:,jlev)*zken(:,jlep)
  end do
  zdtdt(:,1:nlev) = -(((zun(:,1:nlev)*zun(:,1:nlev)-zu(:,1:nlev)*zu(:,1:nlev)+zvn(:,1:nlev)*zvn(:,1:nlev)-zv(:,1:nlev)*zv(:,1:nlev)&
&)/deltsec2-(zken(:,1:nlev)-zke(:,1:nlev))/deltsec2)*0.5/acpd/(1.+adv*dq(:,1:nlev)))
  dtdt(:,1:nlev) = dtdt(:,1:nlev)+zdtdt(:,1:nlev)
  zdtdt(:,1:nlev) = 0.
endif
zebs2(:,1) = zkdiffh(:,1)/(dsigma(1)+zkdiffh(:,1))
zqn(:,1) = dsigma(1)*zq(:,1)/(dsigma(1)+zkdiffh(:,1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs2(:,jlev) = zkdiffh(:,jlev)/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,jlem)))
  zqn(:,jlev) = (zq(:,jlev)*dsigma(jlev)+zkdiffh(:,jlem)*zqn(:,jlem))/(dsigma(jlev)+zkdiffh(:,jlev)+zkdiffh(:,jlem)*(1.-zebs2(:,&
&jlem)))
end do
zqn(:,nlev) = (zq(:,nlev)*dsigma(nlev)+zkdiffh(:,nlem)*zqn(:,nlem))/(dsigma(nlev)+zkdiffh(:,nlem)*(1.-zebs2(:,nlem)))
!$taf INCOMPLETE zqn
do jlev = nlem, 1, -1
  jlep = jlev+1
  zqn(:,jlev) = zqn(:,jlev)+zebs2(:,jlev)*zqn(:,jlep)
end do
zdqdt(:,1:nlev) = (zqn(:,1:nlev)-zq(:,1:nlev))/deltsec2
do jlev = 1, nlev
  dqdt(:,jlev) = dqdt(:,jlev)+zdqdt(:,jlev)
end do
do jlev = 1, nlem
  zkdiffh2(:,jlev) = zkdiffh(:,jlev)*zskaph(jlev)
end do
zebs3(:,1) = zkdiffh2(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
ztn(:,1) = dsigma(1)*zt(:,1)/(dsigma(1)+zkdiffh2(:,1)/zskap(1))
do jlev = 2, nlem
  jlem = jlev-1
  zebs3(:,jlev) = zkdiffh2(:,jlev)/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
  ztn(:,jlev) = (zt(:,jlev)*dsigma(jlev)+zkdiffh2(:,jlem)/zskap(jlem)*ztn(:,jlem))/(dsigma(jlev)+(zkdiffh2(:,jlev)+zkdiffh2(:,jlem)&
&*(1.-zebs3(:,jlem)/zskap(jlem)))/zskap(jlev))
end do
ztn(:,nlev) = (zt(:,nlev)*dsigma(nlev)+zkdiffh2(:,nlem)*ztn(:,nlem)/zskap(nlem))/(dsigma(nlev)+zkdiffh2(:,nlem)/zskap(nlev)*(1.-&
&zebs3(:,nlem)/zskap(nlem)))
!$taf INCOMPLETE ztn
do jlev = nlem, 1, -1
  jlep = jlev+1
  ztn(:,jlev) = ztn(:,jlev)+zebs3(:,jlev)*ztn(:,jlep)/zskap(jlep)
end do
zdtdt(:,1:nlev) = (ztn(:,1:nlev)-zt(:,1:nlev))/deltsec2
dtdt(:,1:nlev) = dtdt(:,1:nlev)+zdtdt(:,1:nlev)
if (ndiaggp == 1) then
  dgp3d(:,1:nlev,4) = zdtdt(:,1:nlev)
  do jlev = 1, nlev
    dgp3d(:,jlev,14) = zdqdt(:,jlev)*dp(:)*dsigma(jlev)/ga/1000.
  end do
endif
if (nentropy > 0) then
  dentropy(:,8) = 0.
  dentropy(:,32) = 0.
  do jlev = 1, nlev
    if (nentropy > 2) then
      dentropy(:,8) = dentropy(:,8)+zdtdt(:,jlev)/dt(:,jlev)*acpd*(1.+adv*dq(:,jlev))*dp(:)/ga*dsigma(jlev)
      dentropy(:,32) = dentropy(:,32)-((zun(:,jlev)*zun(:,jlev)-zu(:,jlev)*zu(:,jlev)+zvn(:,jlev)*zvn(:,jlev)-zv(:,jlev)*zv(:,jlev)&
&)/deltsec2-(zken(:,jlev)-zke(:,jlev))/deltsec2)*0.5*dp(:)/ga*dsigma(jlev)/dt(:,jlev)
    else
      dentropy(:,8) = dentropy(:,8)+zdtdt(:,jlev)/dentrot(:,jlev)*acpd*(1.+adv*dentroq(:,jlev))*dentrop(:)/ga*dsigma(jlev)
      dentropy(:,32) = dentropy(:,32)-((zun(:,jlev)*zun(:,jlev)-zu(:,jlev)*zu(:,jlev)+zvn(:,jlev)*zvn(:,jlev)-zv(:,jlev)*zv(:,jlev)&
&)/deltsec2-(zken(:,jlev)-zke(:,jlev))/deltsec2)*0.5*dentrop(:)/ga*dsigma(jlev)/dentrot(:,jlev)
    endif
  end do
endif
if (nenergy > 0) then
  denergy(:,8) = 0.
  denergy(:,22) = 0.
  do jlev = 1, nlev
    denergy(:,8) = denergy(:,8)+zdtdt(:,jlev)*acpd*(1.+adv*dq(:,jlev))*dp(:)/ga*dsigma(jlev)
    denergy(:,22) = denergy(:,22)-((zun(:,jlev)*zun(:,jlev)-zu(:,jlev)*zu(:,jlev)+zvn(:,jlev)*zvn(:,jlev)-zv(:,jlev)*zv(:,jlev))/&
&deltsec2-(zken(:,jlev)-zke(:,jlev))/deltsec2)*0.5*dp(:)/ga*dsigma(jlev)
  end do
endif
end subroutine vdiff
