!                           DISCLAIMER
! 
!   This file was generated by TAF version 5.9.12
! 
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
! 
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
! 
module     icemod
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use resmod

implicit none

!==============================================
! declare parameters
!==============================================
real, parameter :: ckapi = 2.03
real, parameter :: ckapsn = 0.31
real, parameter :: clfi = 3.28e5
real, parameter :: clfsn = 3.337e5
real, parameter :: cpi = 2070.
real, parameter :: cps = 4180.
real, parameter :: cpsn = 2090.
real, parameter :: crhof = 1003.8
real, parameter :: crhoi = 920.
real, parameter :: crhos = 1030.
real, parameter :: crhosn = 330.
integer, parameter :: nlat = nlat_atm
integer, parameter :: nlon = nlat+nlat
integer, parameter :: npro = npro_atm
integer, parameter :: nlpp = nlat/npro
integer, parameter :: nhor = nlon*nlpp
integer, parameter :: nroot = 0
real, parameter :: tfreeze = 271.25
real, parameter :: tmelt = 273.16

!==============================================
! declare local variables
!==============================================
real :: cheat(nhor) = 0.
real :: cheat_ad(nhor)
real :: cicemin = 0.5
real :: cpme(nhor) = 0.
real :: croff(nhor) = 0.
real :: csnow(nhor) = 0.
real :: ctaux(nhor) = 0.
real :: ctauy(nhor) = 0.
real :: cust3(nhor) = 0.
real :: dcool = 50.00
real :: deglat(nlpp) = 0.0
integer :: mpinfo = 0
integer :: mypid = 0
integer :: myworld = 0
integer :: naccuo = 0
integer :: naccuout = 0
integer :: naout = 0
integer :: ncpl_ice_ocean = 1
integer :: nentropy = 0
integer :: newsurf = 0
integer :: nfluko = 0
integer :: ngui = 0
integer :: nice = 1
integer :: nicec2d = 0
integer :: nmit = 0
integer :: nout = 32
integer :: noutput = 1
integer :: nperpetual_ice = 0
integer :: nprhor = 0
integer :: nprint = 0
integer :: nproc = npro
integer :: nrestart = 0
integer :: nsnow = 1
integer :: nstep = 0
integer :: ntskin = 1
integer :: ntspd = 32
integer :: nud = 106
real :: osss(nhor) = 0.
real :: osst(nhor) = 0.
real :: osst_ae(nhor)
real :: solar_day = 86400.0
real :: stotf = 0.054
real :: taunc = 0.
real :: thicec = 0.5
character(len=80) :: version = 'MIT 03.04.2014 by Larry'
real :: xaheat(nhor) = 0.
real :: xaheat_ad(nhor)
real, allocatable :: xaout(:,:)
real :: xcflux(nhor) = 0.
real :: xcflux_ad(nhor)
real :: xcfluxa(nhor) = 0.
real :: xcfluxf(nhor) = 0.
real :: xcfluxf_ad(nhor)
real :: xcfluxn(nhor) = 0.
real :: xcfluxna(nhor) = 0.
real :: xcfluxr(nhor) = 0.
real :: xcfluxr_ad(nhor)
real :: xcfluxra(nhor) = 0.
real :: xclicec(nhor,0:13) = -999.
real :: xclicec2(nhor) = 0.
real :: xcliced(nhor,0:13) = -999.
real :: xcliced2(nhor) = 0.
real :: xclsst(nhor,0:13) = -999.
real :: xclsst2(nhor) = 0.
real :: xclssto(nhor) = 0.
real :: xcpmea(nhor) = 0.
real :: xcroffa(nhor) = 0.
real :: xdt = 0.
real, allocatable :: xentro(:,:)
real :: xfluxc(nhor) = 0.
real :: xfluxc_ad(nhor)
real :: xfluxca(nhor) = 0.
real :: xflxice(nhor,0:13) = 0.
real :: xflxice2(nhor) = 0.
real :: xflxice2_ad(nhor)
real :: xflxicea(nhor) = 0.
real :: xgw(nhor) = 0.
real :: xheat(nhor) = 0.
real :: xheat_ad(nhor)
real :: xheata(nhor) = 0.
real :: xicec(nhor) = 0.
real :: xicec_ad(nhor)
real :: xicecc(nhor) = 0.
real :: xicecc_ad(nhor)
real :: xiced(nhor) = 0.
real :: xiced_ad(nhor)
real :: ximelt(nhor) = 0.
real :: ximelt_ad(nhor)
real :: ximelta(nhor) = 0.
real :: xlhdt(nhor) = 0.
real :: xlhfl(nhor) = 0.
real :: xls(nhor) = 0.
real :: xlwfl(nhor) = 0.
real :: xmaxd = 9.0
real :: xmind = 0.1
real :: xmld(nhor) = 0.
real :: xoflux(nhor) = 0.
real :: xoflux_ad(nhor)
real :: xofluxa(nhor) = 0.
real :: xoheat(nhor) = 0.
real :: xoheat_ad(nhor)
real :: xpme(nhor) = 0.
real :: xpme_ad(nhor)
real :: xprs(nhor) = 0.
real :: xprs_ad(nhor)
real :: xps(nhor) = 0.
real :: xqmelt(nhor) = 0.
real :: xqmelt_ad(nhor)
real :: xqmelta(nhor) = 0.
real :: xroff(nhor) = 0.
real :: xroff_ad(nhor)
real :: xsaltflx(nhor) = 0.
real :: xscflx(nhor) = 0.
real :: xscflx_ad(nhor)
real :: xscflxa(nhor) = 0.
real :: xshdt(nhor) = 0.
real :: xshfl(nhor) = 0.
real :: xsmelt(nhor) = 0.
real :: xsmelta(nhor) = 0.
real :: xsmflx(nhor) = 0.
real :: xsndch(nhor) = 0.
real :: xsnow(nhor) = 0.
real :: xsnow_ad(nhor)
real :: xsss(nhor) = 35.
real :: xsst(nhor) = 0.
real :: xsst_ad(nhor)
real :: xstoi(nhor) = 0.
real :: xstoia(nhor) = 0.
real :: xswfl(nhor) = 0.
real :: xswfl_ad(nhor)
real :: xtaux(nhor) = 0.
real :: xtaux_ad(nhor)
real :: xtauy(nhor) = 0.
real :: xtauy_ad(nhor)
real :: xtfreeze(nhor) = 0.
real :: xts(nhor) = 0.
real :: xts_ad(nhor)
real :: xtsflux(nhor) = 0.
real :: xtsfluxa(nhor) = 0.
real :: xust3(nhor) = 0.

contains
subroutine icemod_constructor_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
implicit none

!----------------------------------------------
! RESET ADJOINT MODULE VARIABLES
!----------------------------------------------
cheat_ad(:) = 0.
osst_ae(:) = 0.
xaheat_ad(:) = 0.
xcflux_ad(:) = 0.
xcfluxf_ad(:) = 0.
xcfluxr_ad(:) = 0.
xfluxc_ad(:) = 0.
xflxice2_ad(:) = 0.
xheat_ad(:) = 0.
xicec_ad(:) = 0.
xicecc_ad(:) = 0.
xiced_ad(:) = 0.
ximelt_ad(:) = 0.
xoflux_ad(:) = 0.
xoheat_ad(:) = 0.
xpme_ad(:) = 0.
xprs_ad(:) = 0.
xqmelt_ad(:) = 0.
xroff_ad(:) = 0.
xscflx_ad(:) = 0.
xsnow_ad(:) = 0.
xsst_ad(:) = 0.
xswfl_ad(:) = 0.
xtaux_ad(:) = 0.
xtauy_ad(:) = 0.
xts_ad(:) = 0.

end subroutine icemod_constructor_ad
end module     icemod

subroutine addfci_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
logical :: whcondh(nhor)
logical :: whcondi(nhor)
real :: xicedh(lbound(xiced,1):ubound(xiced,1))
real :: zflr_ad(nhor)
real :: zmelt(nhor) = 0.
real :: zmelt_ad(nhor)
real :: zrhoilfdt

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
xicedh(:) = xiced

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zflr_ad(:) = 0.
zmelt_ad(:) = 0.

!$taf INCOMPLETE xiced,zmelt
zrhoilfdt = crhoi*clfi/xdt
do jhor = 1, nhor
  if (xls(jhor) < 1.) then
    if (xsst(jhor) <= tfreeze .or. xiced(jhor) > 0. .or. xcliced2(jhor) > 0. .and. xsst(jhor) <= xclssto(jhor)) then
      zmelt(jhor) = xcflux(jhor)+xflxice2(jhor)
      xiced(jhor) = xiced(jhor)-zmelt(jhor)/zrhoilfdt
    endif
  endif
end do
where (xiced(:) <= 0.)
  xiced(:) = 0.
end where
whcondh = abs(xiced(:)) < 1.e-9
where (whcondh)
  xiced_ad(:) = 0.
end where
xiced = xicedh(:)
do jhor = 1, nhor
  if (xls(jhor) < 1.) then
    if (xsst(jhor) <= tfreeze .or. xiced(jhor) > 0. .or. xcliced2(jhor) > 0. .and. xsst(jhor) <= xclssto(jhor)) then
      zmelt(jhor) = xcflux(jhor)+xflxice2(jhor)
      xiced(jhor) = xiced(jhor)-zmelt(jhor)/zrhoilfdt
    endif
  endif
end do
whcondi = xiced(:) <= 0.
where (whcondi)
  xiced_ad(:) = 0.
  xiced_ad(:) = xiced_ad(:)-xcflux_ad(:)*zrhoilfdt
end where
where (xls(:) < 1.)
  zflr_ad(:) = zflr_ad(:)+xcflux_ad(:)
end where
xiced = xicedh(:)
do jhor = 1, nhor
  if (xls(jhor) < 1.) then
    if (xsst(jhor) <= tfreeze .or. xiced(jhor) > 0. .or. xcliced2(jhor) > 0. .and. xsst(jhor) <= xclssto(jhor)) then
      xcflux_ad(jhor) = 0.
      zmelt_ad(jhor) = zmelt_ad(jhor)-xiced_ad(jhor)/zrhoilfdt
      xcflux_ad(jhor) = xcflux_ad(jhor)+zmelt_ad(jhor)
      xflxice2_ad(jhor) = xflxice2_ad(jhor)+zmelt_ad(jhor)
      zmelt_ad(jhor) = 0.
    else
      xflxice2_ad(jhor) = xflxice2_ad(jhor)+zflr_ad(jhor)
      zflr_ad(jhor) = 0.
    endif
  endif
end do

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine addfci_ad

subroutine addfci()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
real :: zflr(nhor) = 0.
real :: zmelt(nhor) = 0.
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real :: zrhoilfdt

zrhoilfdt = crhoi*clfi/xdt
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  call mpgagp( zprf1,xflxice2,1 )
  call mpgagp( zprf2,xclsst2,1 )
  call mpgagp( zprf3,xcliced2,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In addfci:'
    write(unit=nud,fmt=*) 'fluko: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'clsst: ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'cliced: ',zprf3(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
endif
zflr(:) = 0.
do jhor = 1, nhor
  if (xls(jhor) < 1.) then
    if (xsst(jhor) <= tfreeze .or. xiced(jhor) > 0. .or. xcliced2(jhor) > 0. .and. xsst(jhor) <= xclssto(jhor)) then
      zmelt(jhor) = xcflux(jhor)+xflxice2(jhor)
      xiced(jhor) = xiced(jhor)-zmelt(jhor)/zrhoilfdt
      ximelt(jhor) = ximelt(jhor)+zmelt(jhor)
      xcflux(jhor) = 0.
    else
      zflr(jhor) = xflxice2(jhor)
    endif
  endif
end do
where (xls(:) < 1.)
  xcflux(:) = xcflux(:)+zflr(:)
end where
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  call mpgagp( zprf1,zmelt,1 )
  call mpgagp( zprf2,xiced,1 )
  call mpgagp( zprf3,xcflux,1 )
  call mpgagp( zprf4,zflr,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'new ice and flux for ice: ',zprf2(nprhor),zprf1(nprhor)
    write(unit=nud,fmt=*) 'residual flux correction: ',zprf4(nprhor)
    write(unit=nud,fmt=*) 'new flux into ocean: ',zprf3(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
endif
where (xiced(:) <= 0.)
  xcflux(:) = xcflux(:)-xiced(:)*zrhoilfdt
  ximelt(:) = ximelt(:)+xiced(:)*zrhoilfdt
  xcfluxn(:) = xcfluxn(:)-xiced(:)*zrhoilfdt
  xiced(:) = 0.
end where
where (abs(xiced(:)) < 1.e-9)
  xiced(:) = 0.
end where
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  call mpgagp( zprf1,xcflux,1 )
  call mpgagp( zprf2,xiced,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'final ice: ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'final conductive hf: ',zprf1(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
endif
end subroutine addfci

subroutine getflx_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

xflxice2_ad(:) = 0.

end subroutine getflx_ad

subroutine getflx()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: help_h
integer :: jm1
integer :: jm2
real :: zgw

help_h = nstep+1
call momint( nperpetual_ice,help_h,jm1,jm2,zgw )
xflxice2(:) = (1.0-zgw)*xflxice(:,jm1)+zgw*xflxice(:,jm2)
end subroutine getflx

subroutine getiflx_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zfac
real :: zfac_ad
real :: zflx(nhor) = 0.
real :: zflx_ad(nhor)
real :: zflxh_ad(nhor)
real :: zrhoilfdt
real :: zsum(2)
real :: zsum_ad(2)
logical :: zsumh(nhor)
real :: zsumi_ad(nhor)
logical :: zsumj(nhor)
real :: zsumk_ad(nhor)

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zfac_ad = 0.
zflx_ad(:) = 0.
zsum_ad(:) = 0.

!$taf INCOMPLETE zflx,zsum
zrhoilfdt = crhoi*clfi/xdt
where (xls(:) < 1.)
  zflx(:) = amax1(0.,xmaxd-xiced(:))*zrhoilfdt
end where
zsum(1) = sum(xcfluxr(:)*xgw(:),mask=xls(:) < 1.)
zsum(2) = sum(zflx(:)*xgw(:),mask=xls(:) < 1.)
call mpsumbcr( zsum,2 )
if (zsum(1) > 0. .and. zsum(2) > 0.) then
  zfac = zsum(1)/zsum(2)
  where (xls(:) < 1.)
    zflx_ad(:) = zflx_ad(:)-xcflux_ad(:)
  end where
  if (zfac <= 1.) then
    zfac_ad = zfac_ad+sum(zflx_ad(:)*zflx(:),mask=xls(:) < 1.)
    where (xls(:) < 1.)
      zflx_ad(:) = zflx_ad(:)*zfac
    end where
  endif
  zsum_ad(2) = zsum_ad(2)-zfac_ad*(zsum(1)/zsum(2)/zsum(2))
  zsum_ad(1) = zsum_ad(1)+zfac_ad/zsum(2)
  zfac_ad = 0.
endif
call mpsumbcr_ad( zsum_ad,2 )
zsumh = xls(:) < 1.
zsumi_ad(:) = 0._8
where (zsumh)
  zsumi_ad = zsum_ad(2)
end where
where ( .not. zsumh)
  zsumi_ad = 0._8
end where
where (zsumh)
  zflx_ad(:) = zflx_ad(:)+zsumi_ad*xgw(:)
  zsumi_ad = 0._8
end where
zsum_ad(2) = 0.
zsumj = xls(:) < 1.
zsumk_ad(:) = 0._8
where (zsumj)
  zsumk_ad = zsum_ad(1)
end where
where ( .not. zsumj)
  zsumk_ad = 0._8
end where
where (zsumj)
  xcfluxr_ad(:) = xcfluxr_ad(:)+zsumk_ad*xgw(:)
  zsumk_ad = 0._8
end where
zsum_ad(1) = 0.
where (xls(:) < 1.)
  zflxh_ad(:) = 0._8
  zflxh_ad = zflx_ad(:)*zrhoilfdt*(0.5-sign(0.5,0.-(xmaxd-xiced(:))))
  xiced_ad(:) = xiced_ad(:)-zflxh_ad
  zflx_ad(:) = 0.
end where

end subroutine getiflx_ad

subroutine getiflx()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zfac
real :: zflx(nhor) = 0.
real :: zrhoilfdt
real :: zsum(2)

zrhoilfdt = crhoi*clfi/xdt
where (xls(:) < 1.)
  zflx(:) = amax1(0.,xmaxd-xiced(:))*zrhoilfdt
end where
zsum(1) = sum(xcfluxr(:)*xgw(:),mask=xls(:) < 1.)
zsum(2) = sum(zflx(:)*xgw(:),mask=xls(:) < 1.)
call mpsumbcr( zsum,2 )
if (zsum(1) > 0. .and. zsum(2) > 0.) then
  zfac = zsum(1)/zsum(2)
  if (zfac <= 1.) then
    where (xls(:) < 1.)
      zflx(:) = zflx(:)*zfac
    end where
  endif
  where (xls(:) < 1.)
    xcfluxr(:) = xcfluxr(:)-zflx(:)
    xcflux(:) = xcflux(:)-zflx(:)
  end where
endif
end subroutine getiflx

subroutine iceget()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: help_h
integer :: jm1
integer :: jm2
real :: zgw1
real :: zgw2

call momint( nperpetual_ice,nstep,jm1,jm2,zgw2 )
zgw1 = 1.0-zgw2
xclssto(:) = zgw1*xclsst(:,jm1)+zgw2*xclsst(:,jm2)
help_h = nstep+1
call momint( nperpetual_ice,help_h,jm1,jm2,zgw2 )
zgw1 = 1.0-zgw2
xclsst2(:) = zgw1*xclsst(:,jm1)+zgw2*xclsst(:,jm2)
xcliced2(:) = zgw1*xcliced(:,jm1)+zgw2*xcliced(:,jm2)
xclicec2(:) = zgw1*xclicec(:,jm1)+zgw2*xclicec(:,jm2)
xclicec2(:) = amax1(xclicec2(:),0.)
xcliced2(:) = amax1(xcliced2(:),0.)
where (xcliced2(:) <= 0.)
  xclicec2(:) = 0.
end where
if (nprint == 2) then
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In iceget:'
    write(unit=nud,fmt=*) ' jm1,jm2= ',jm1,jm2,' gw1,gw2= ',zgw1,zgw2
  endif
endif
end subroutine iceget

subroutine iceini( kstep, krestart, koutput, kdpy, kgui, pts, psst, pmld, picec, piced, psnow, ktspd, psolday, pdeglat, &
&icemod_namelist, oceanmod_namelist, ice_output, ocean_output )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare arguments
!==============================================
character(len=*), intent(in) :: ice_output
character(len=*), intent(in) :: icemod_namelist
integer, intent(in) :: kdpy
integer, intent(in) :: kgui
integer, intent(in) :: koutput
integer, intent(in) :: krestart
integer, intent(in) :: kstep
integer, intent(in) :: ktspd
character(len=*), intent(in) :: ocean_output
character(len=*), intent(in) :: oceanmod_namelist
real, intent(in) :: pdeglat(nlpp)
real, intent(inout) :: picec(nhor)
real, intent(inout) :: piced(nhor)
real, intent(inout) :: pmld(nhor)
real, intent(inout) :: psnow(nhor)
real, intent(in) :: psolday
real, intent(inout) :: psst(nhor)
real, intent(inout) :: pts(nhor)

!==============================================
! declare local variables
!==============================================
integer :: jlat
real(kind=8) :: zgw(nlat)
real :: zgw2(nlon,nlat)
real :: zls(nlon,nlat)
real(kind=8) :: zsi(nlat)

!==============================================
! declare namelists
!==============================================
namelist /icemod_nl/ nout,nfluko,nperpetual_ice,ntspd,nprint,nprhor,nentropy,nice,nsnow,ntskin,ncpl_ice_ocean,taunc,xmind,xmaxd,&
&thicec,newsurf,naout,nmit,stotf,dcool

nstep = kstep
nrestart = krestart
noutput = koutput
ngui = kgui
ntspd = ktspd
solar_day = psolday
deglat(:) = pdeglat(:)
if (mypid == nroot) then
  call inigau( nlat,zsi,zgw )
  do jlat = 1, nlat
    zgw2(:,jlat) = zgw(jlat)
  end do
endif
call mpscgp( zgw2,xgw,1 )
call mpi_info( nproc,mypid )
if (mypid == nroot) then
  open(unit=11,file=icemod_namelist)
  read(unit=11,nml=icemod_nl)
  close(unit=11)
  write(unit=nud,fmt='(/," *********************************************")')
  write(unit=nud,fmt='(" * ICEMOD ",a34," *")') trim(version)
  write(unit=nud,fmt='(" *********************************************")')
  write(unit=nud,fmt='(" * Namelist ICEMOD_NL from <",a15,"> *")') trim(icemod_namelist)
  write(unit=nud,fmt='(" *********************************************")')
  write(unit=nud,nml=icemod_nl)
endif
call mpbci( nout )
call mpbci( nfluko )
call mpbci( nice )
call mpbci( newsurf )
call mpbci( nsnow )
call mpbci( ntskin )
call mpbci( ntspd )
call mpbci( nperpetual_ice )
call mpbci( ncpl_ice_ocean )
call mpbci( nprint )
call mpbci( nprhor )
call mpbci( nentropy )
call mpbci( naout )
call mpbcr( taunc )
call mpbcr( xmind )
call mpbcr( xmaxd )
call mpbcr( thicec )
call mpbcr( stotf )
call mpbcr( dcool )
call mpbci( nmit )
xdt = solar_day/real(ntspd)
taunc = solar_day*taunc
if (nrestart == 0) then
  call read_ice_surface
  call iceget
  xiced(:) = xcliced2(:)
  xicec(:) = xclicec2(:)
  xicecc(:) = xicec(:)
  where (xicec(:) >= thicec)
    xicec(:) = 1.
  elsewhere
    xicec(:) = 0.
  end where
else
  if (mypid == nroot) then
    call get_restart_integer( 'nstep',nstep )
    call get_restart_integer( 'naccuice',naccuout )
    call get_restart_integer( 'naccuo',naccuo )
    call get_restart_integer( 'nicec2d',nicec2d )
  endif
  call mpbci( nstep )
  call mpbci( naccuout )
  call mpbci( naccuo )
  call mpbci( nicec2d )
  call mpgetgp( 'xls',xls,nhor,1 )
  call mpgetgp( 'xts',xts,nhor,1 )
  call mpgetgp( 'xicec',xicec,nhor,1 )
  call mpgetgp( 'xiced',xiced,nhor,1 )
  call mpgetgp( 'xsnow',xsnow,nhor,1 )
  call mpgetgp( 'cheat',cheat,nhor,1 )
  call mpgetgp( 'cpme',cpme,nhor,1 )
  call mpgetgp( 'croff',croff,nhor,1 )
  call mpgetgp( 'ctaux',ctaux,nhor,1 )
  call mpgetgp( 'ctauy',ctauy,nhor,1 )
  call mpgetgp( 'cust3',cust3,nhor,1 )
  call mpgetgp( 'csnow',csnow,nhor,1 )
  call mpgetgp( 'xflxicea',xflxicea,nhor,1 )
  call mpgetgp( 'xheata',xheata,nhor,1 )
  call mpgetgp( 'xofluxa',xofluxa,nhor,1 )
  call mpgetgp( 'xqmelta',xqmelta,nhor,1 )
  call mpgetgp( 'xcfluxa',xcfluxa,nhor,1 )
  call mpgetgp( 'xcfluxra',xcfluxra,nhor,1 )
  call mpgetgp( 'xcfluxna',xcfluxna,nhor,1 )
  call mpgetgp( 'xsmelta',xsmelta,nhor,1 )
  call mpgetgp( 'ximelta',ximelta,nhor,1 )
  call mpgetgp( 'xtsfluxa',xtsfluxa,nhor,1 )
  call mpgetgp( 'xfluxca',xfluxca,nhor,1 )
  call mpgetgp( 'xscflxa',xscflxa,nhor,1 )
  call mpgetgp( 'xcpmea',xcpmea,nhor,1 )
  call mpgetgp( 'xcroffa',xcroffa,nhor,1 )
  call mpgetgp( 'xstoia',xstoia,nhor,1 )
  call mpgetgp( 'xicecc',xicecc,nhor,1 )
  if (nmit < 99) then
    call mpgetgp( 'osst',osst,nhor,1 )
    call mpgetgp( 'osss',osss,nhor,1 )
  endif
  if (newsurf == 1) then
    call read_ice_surface
  else
    call mpgetgp( 'xclicec',xclicec,nhor,14 )
    call mpgetgp( 'xcliced',xcliced,nhor,14 )
    call mpgetgp( 'xclsst',xclsst,nhor,14 )
  endif
endif
xtfreeze(:) = tfreeze
if (nfluko == 1) then
  call mpsurfgp( 'xflxice',xflxice,nhor,14 )
endif
if (mypid == nroot .and. noutput > 0) then
  open(unit=71,file=ice_output,form='unformatted')
endif
call oceanini( nstep,nrestart,noutput,kdpy,ngui,xsst,xmld,xoheat,ntspd,solar_day,oceanmod_namelist,ocean_output )
xoflux(:) = xoheat(:)
if (nmit > 0) then
  call mpgagp( zls,xls,1 )
  if (mypid == nroot) then
    call cplatmini( zls,nlon,nlat )
  endif
  if (nrestart /= 0) then
    if (nmit < 99) then
      where (xls(:) < 1.)
        xsst(:) = osst(:)
        xsss(:) = osss(:)
        xoflux(:) = 0.
      end where
    endif
  endif
endif
if (nrestart == 0) then
  xts(:) = xsst(:)
endif
pts(:) = xts(:)
psst(:) = xsst(:)
pmld(:) = xmld(:)
picec(:) = xicec(:)
piced(:) = xiced(:)
psnow(:) = xsnow(:)
if (nentropy > 0) then
  allocate( xentro(nhor,1) )
  xentro(:,:) = 0.
endif
if (naout > 0) then
  allocate( xaout(nhor,naout) )
endif
end subroutine iceini

subroutine iceout()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: ih(8)
integer :: ja
integer :: nday
integer :: nhour
integer :: nmin
integer :: nmonth
integer :: nyear
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real :: zsnow(nhor) = 0.

where (xls(:) < 0.5)
  zsnow(:) = 1000./crhosn*xsnow(:)
end where
call ntomin( nstep,nmin,nhour,nday,nmonth,nyear )
ih(2) = 0
ih(3) = nyear*10000+nmonth*100+nday
ih(4) = nhour*100+nmin
ih(5) = nlon
ih(6) = nlat
ih(7) = 0
ih(8) = 0
ih(1) = 701
call mpwritegph( 71,xheata,nhor,1,ih )
ih(1) = 702
call mpwritegph( 71,xofluxa,nhor,1,ih )
ih(1) = 703
call mpwritegph( 71,xtsfluxa,nhor,1,ih )
ih(1) = 704
call mpwritegph( 71,xsmelta,nhor,1,ih )
ih(1) = 705
call mpwritegph( 71,ximelta,nhor,1,ih )
ih(1) = 706
call mpwritegph( 71,xcfluxa,nhor,1,ih )
ih(1) = 707
call mpwritegph( 71,xfluxca,nhor,1,ih )
ih(1) = 708
call mpwritegph( 71,xqmelta,nhor,1,ih )
ih(1) = 709
call mpwritegph( 71,xflxicea,nhor,1,ih )
ih(1) = 710
call mpwritegph( 71,xicec,nhor,1,ih )
ih(1) = 711
call mpwritegph( 71,xiced,nhor,1,ih )
ih(1) = 712
call mpwritegph( 71,xscflxa,nhor,1,ih )
ih(1) = 713
call mpwritegph( 71,xcfluxra,nhor,1,ih )
ih(1) = 714
call mpwritegph( 71,xcfluxna,nhor,1,ih )
ih(1) = 739
call mpwritegph( 71,xts,nhor,1,ih )
ih(1) = 741
call mpwritegph( 71,zsnow,nhor,1,ih )
ih(1) = 769
call mpwritegph( 71,xsst,nhor,1,ih )
ih(1) = 772
call mpwritegph( 71,xls,nhor,1,ih )
ih(1) = 790
call mpwritegph( 71,xclicec2,nhor,1,ih )
ih(1) = 791
call mpwritegph( 71,xcliced2,nhor,1,ih )
ih(1) = 792
call mpwritegph( 71,xicecc,nhor,1,ih )
ih(1) = 794
call mpwritegph( 71,xcpmea,nhor,1,ih )
ih(1) = 795
call mpwritegph( 71,xcroffa,nhor,1,ih )
ih(1) = 796
call mpwritegph( 71,xstoia,nhor,1,ih )
if (nentropy > 0) then
  ih(1) = 797
  call mpwritegph( 71,xentro,nhor,1,ih )
endif
if (naout > 0) then
  do ja = 1, naout
    ih(1) = 750+ja
    call mpwritegph( 71,xaout(:,ja),nhor,1,ih )
  end do
endif
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  call mpgagp( zprf1,xicec,1 )
  call mpgagp( zprf2,xiced,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In iceout:'
    write(unit=nud,fmt=*) 'ice compactness: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'ice thickness:   ',zprf2(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
endif
end subroutine iceout

subroutine icestep_ad( pheat, pheat_ad, pswfl, pswfl_ad, ppme_ad, proff_ad, pprs, pprs_ad, ptaux, ptaux_ad, ptauy, ptauy_ad, &
&pts_ad, picec_ad, piced_ad, psnow_ad, psst_ad )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare arguments
!==============================================
real, intent(in) :: pheat(nhor)
real, intent(inout) :: pheat_ad(nhor)
real, intent(inout) :: picec_ad(nhor)
real, intent(inout) :: piced_ad(nhor)
real, intent(inout) :: ppme_ad(nhor)
real, intent(in) :: pprs(nhor)
real, intent(inout) :: pprs_ad(nhor)
real, intent(inout) :: proff_ad(nhor)
real, intent(inout) :: psnow_ad(nhor)
real, intent(inout) :: psst_ad(nhor)
real, intent(in) :: pswfl(nhor)
real, intent(inout) :: pswfl_ad(nhor)
real, intent(in) :: ptaux(nhor)
real, intent(inout) :: ptaux_ad(nhor)
real, intent(in) :: ptauy(nhor)
real, intent(inout) :: ptauy_ad(nhor)
real, intent(inout) :: pts_ad(nhor)

!==============================================
! declare local variables
!==============================================
real :: icestep_cheat_10h(nhor,1)
real :: icestep_xcflux_1h(nhor,1)
real :: icestep_xcflux_3h(nhor,1)
real :: icestep_xicec_6h(nhor,1)
real :: icestep_xiced_4h(nhor,1)
real :: icestep_xiced_5h(nhor,1)
real :: icestep_xscflx_2h(nhor,1)
logical :: whcondl(nhor)
logical :: whcondm(nhor)
logical :: whcondn(nhor)
logical :: whcondo(nhor)
real :: xicecch(lbound(xicecc,1):ubound(xicecc,1))
real :: xicech(lbound(xicec,1):ubound(xicec,1))
real :: xiceci(nhor) = 0.
real :: xicedh(lbound(xiced,1):ubound(xiced,1))
real :: xprsh(lbound(xprs,1):ubound(xprs,1))
real :: xsnowh(lbound(xsnow,1):ubound(xsnow,1))
real :: xtsh(lbound(xts,1):ubound(xts,1))
real :: zcflux(nhor)
real :: zcflux2(nhor)
real :: zcflux2_ad(nhor)
real :: zcflux_ad(nhor)
real :: zfresh_ad(nlon,nlat)
real :: zfreshp_ad(nhor)
real :: zheat_ad(nlon,nlat)
real :: zicedold(nhor)
real :: zicedold_ad(nhor)
real :: zrhoilfdt
real :: zroff_ad(nlon,nlat)
real :: zsnowold_ad(nhor)
real :: zswr_ad(nlon,nlat)
real :: zswrp_ad(nhor)
real :: ztaux_ad(nlon,nlat)
real :: ztauxp_ad(nhor)
real :: ztauy_ad(nlon,nlat)
real :: ztauyp_ad(nhor)

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
xtsh(:) = xts
xsnowh(:) = xsnow
xprsh(:) = xprs
xicedh(:) = xiced
xicecch(:) = xicecc
xicech(:) = xicec

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zcflux2_ad(:) = 0.
zcflux_ad(:) = 0.
zfresh_ad(:,:) = 0.
zfreshp_ad(:) = 0.
zheat_ad(:,:) = 0.
zicedold_ad(:) = 0.
zroff_ad(:,:) = 0.
zsnowold_ad(:) = 0.
zswr_ad(:,:) = 0.
zswrp_ad(:) = 0.
ztaux_ad(:,:) = 0.
ztauxp_ad(:) = 0.
ztauy_ad(:,:) = 0.
ztauyp_ad(:) = 0.

!----------------------------------------------
! TAPE COMPUTATIONS
!----------------------------------------------
zrhoilfdt = crhoi*clfi/xdt
zicedold(:) = 0.0
xscflx(:) = 0.
xcfluxr(:) = 0.
where (xls(:) < 1.)
  xaheat(:) = pheat(:)
  xheat(:) = xaheat(:)
  xprs(:) = pprs(:)
end where
call iceget
where (xls(:) < 0.5)
  zicedold(:) = xiced(:)
end where
if (nsnow == 1) then
  where (xicec(:) >= cicemin)
    xsnow(:) = xsnow(:)+xprs(:)*xdt
    xprs(:) = 0.
  end where
endif
if (ntskin == 1) then
  call skintemp
else
  where (xiced(:)+1.e3/crhosn*xsnow(:) >= 0.1)
    xts(:) = xclsst2(:)
  elsewhere
    xts(:) = xsst(:)
  end where
endif
call mkcflux
if (nsnow == 1) then
  call subsnow
else
  xsnow(:) = 0.
endif
!$taf INCOMPLETE icestep_xscflx_2h
icestep_xscflx_2h(:,1) = xscflx
!$taf INCOMPLETE icestep_xcflux_1h
icestep_xcflux_1h(:,1) = xcflux
call mkice
!$taf INCOMPLETE icestep_xiced_4h
icestep_xiced_4h(:,1) = xiced
!$taf INCOMPLETE icestep_xcflux_3h
icestep_xcflux_3h(:,1) = xcflux
call mkicec( zicedold,xiced,xicecc )
if (nice == 0) then
  where (xiced(:) > 0. .or. xcliced2(:) > 0.)
    xcflux(:) = 0.
    xiced(:) = xcliced2(:)
    xicec(:) = xclicec2(:)
  elsewhere
    xicec(:) = 0.
  end where
else
  xicec(:) = xicecc(:)
  if (nfluko == 0) then
  else if (nfluko == 1) then
    call getflx
    call addfci
    where (xiced(:) > 0. .and. xcliced2(:) > 0)
      xicec(:) = xclicec2(:)
    end where
    where (xcliced2(:) > 0. .and. xicecc(:) > 0.999 .or. xcliced2(:) > 0. .and. xmaxd > 0. .and. xiced(:) > 0.9*xmaxd)
      xicec(:) = 1.
    end where
  else if (nfluko == 2) then
    call mkflukoi
    call addfci
  endif
endif
!$taf INCOMPLETE icestep_xicec_6h
icestep_xicec_6h(:,1) = xicec
!$taf INCOMPLETE icestep_xiced_5h
icestep_xiced_5h(:,1) = xiced
zcflux(:) = 0.
if (xmaxd >= 0.) then
  where (xiced(:) > xmaxd)
    zcflux(:) = (xiced(:)-xmaxd)*zrhoilfdt
    xiced(:) = xmaxd
    xcfluxr(:) = xcfluxr(:)+zcflux(:)
  end where
  call getiflx
endif
where (xicec(:) >= thicec)
  xicec(:) = 1.
elsewhere
  xicec(:) = 0.
end where
zcflux2(:) = 0.
where (xiced(:) <= 0. .and. xsnow(:) > 0.)
  zcflux2(:) = xsnow(:)*1000.*clfsn/xdt
  xcflux(:) = xcflux(:)-zcflux2(:)
end where
where (xls(:) < 0.5)
  cheat(:) = cheat(:)+xcflux(:)
end where
naccuo = naccuo+1
if (mod(nstep,ncpl_ice_ocean) == 0) then
  where (xls(:) < 0.5)
    cheat(:) = cheat(:)/real(naccuo)
  end where
!$taf INCOMPLETE icestep_cheat_10h
  icestep_cheat_10h(:,1) = cheat
endif

!----------------------------------------------
! ADJOINT COMPUTATIONS
!----------------------------------------------
xicec = xicech(:)
xprs = xprsh(:)
xiceci(:) = xicec(:)
xcfluxr(:) = 0.
where (xls(:) < 1.)
  xswfl(:) = pswfl(:)
  xprs(:) = pprs(:)
  xtaux(:) = ptaux(:)
  xtauy(:) = ptauy(:)
end where
if (nsnow == 1) then
  where (xicec(:) >= cicemin)
    xprs(:) = 0.
  end where
endif
xicec(:) = xiceci(:)
xscflx = icestep_xscflx_2h(:,1)
xcflux = icestep_xcflux_3h(:,1)
xsst_ad(:) = xsst_ad(:)+psst_ad(:)
psst_ad(:) = 0.
xsnow_ad(:) = xsnow_ad(:)+psnow_ad(:)
psnow_ad(:) = 0.
xiced_ad(:) = xiced_ad(:)+piced_ad(:)
piced_ad(:) = 0.
xicec_ad(:) = xicec_ad(:)+picec_ad(:)
picec_ad(:) = 0.
xts_ad(:) = xts_ad(:)+pts_ad(:)
pts_ad(:) = 0.
!$taf INCOMPLETE xoflux_ad,xsst_ad
if (nmit > 0) then
!$taf INCOMPLETE xoflux_ad,xsst_ad
!$taf INCOMPLETE xoflux_ad,xsst_ad
  if (nmit < 99) then
    where (xls(:) < 1.)
      xoflux_ad(:) = 0.
      osst_ae(:) = osst_ae(:)+xsst_ad(:)
      xsst_ad(:) = 0.
    end where
  endif
  if (mypid == nroot) then
    call cputtaua_ad( ztaux_ad,ztauy_ad )
    call cputroffa_ad( zroff_ad )
    call cputpmea_ad( zfresh_ad )
    call cputswra_ad( zswr_ad )
    call cputhfla_ad( zheat_ad )
  endif
  call mpgagp_ad( ztauy_ad,ztauyp_ad,1 )
  call mpgagp_ad( ztaux_ad,ztauxp_ad,1 )
  call mpgagp_ad( zroff_ad,xroff_ad,1 )
  call mpgagp_ad( zfresh_ad,zfreshp_ad,1 )
  call mpgagp_ad( zswr_ad,zswrp_ad,1 )
  call mpgagp_ad( zheat_ad,xcflux_ad,1 )
  where (xls(:) < 1.)
    xiced_ad(:) = xiced_ad(:)-zfreshp_ad(:)*(1/xdt*crhoi/1.e3)
    xpme_ad(:) = xpme_ad(:)+zfreshp_ad(:)
    xsnow_ad(:) = xsnow_ad(:)-zfreshp_ad(:)/xdt
    zicedold_ad(:) = zicedold_ad(:)-zfreshp_ad(:)*((-1)/xdt*crhoi/1.e3)
    zsnowold_ad(:) = zsnowold_ad(:)+zfreshp_ad(:)/xdt
    zfreshp_ad(:) = 0.
    xicec_ad(:) = xicec_ad(:)-zswrp_ad(:)*xswfl(:)
    xswfl_ad(:) = xswfl_ad(:)+zswrp_ad(:)*(1.-xicec(:))
    zswrp_ad(:) = 0.
    xicec_ad(:) = xicec_ad(:)-ztauyp_ad(:)*xtauy(:)
    xtauy_ad(:) = xtauy_ad(:)+ztauyp_ad(:)*(1.-xicec(:))
    ztauyp_ad(:) = 0.
    xicec_ad(:) = xicec_ad(:)-ztauxp_ad(:)*xtaux(:)
    xtaux_ad(:) = xtaux_ad(:)+ztauxp_ad(:)*(1.-xicec(:))
    ztauxp_ad(:) = 0.
  end where
endif
if (mod(nstep,ncpl_ice_ocean) == 0) then
  cheat = icestep_cheat_10h(:,1)
  where (xls(:) < 0.5)
    cheat_ad(:) = 0.
  end where
  xoheat_ad(:) = xoheat_ad(:)+xoflux_ad(:)
  xoflux_ad(:) = 0.
  call oceanstep_ad( xiced,xiced_ad,cheat,cheat_ad,xsst_ad,xoheat_ad,xcliced2 )
  where (xls(:) < 0.5)
    cheat_ad(:) = cheat_ad(:)/real(naccuo)
  end where
endif
where (xls(:) < 0.5)
  xcflux_ad(:) = xcflux_ad(:)+cheat_ad(:)
end where
whcondl = xiced(:) <= 0. .and. xsnow(:) > 0.
where (whcondl)
  xsnow_ad(:) = 0.
  zcflux2_ad(:) = zcflux2_ad(:)-xcflux_ad(:)
  xsnow_ad(:) = xsnow_ad(:)+zcflux2_ad(:)*(1000*clfsn/xdt)
  zcflux2_ad(:) = 0.
end where
xicec = icestep_xicec_6h(:,1)
whcondm = xicec(:) >= thicec
where (whcondm)
  xicec_ad(:) = 0.
end where
where ( .not. whcondm)
  xicec_ad(:) = 0.
end where
xiced = icestep_xiced_5h(:,1)
!$taf INCOMPLETE xcfluxr
if (xmaxd >= 0.) then
!$taf INCOMPLETE xcfluxr
  where (xiced(:) > xmaxd)
    xcfluxr(:) = xcfluxr(:)+zcflux(:)
  end where
  call getiflx_ad
  xiced = icestep_xiced_5h(:,1)
  whcondn = xiced(:) > xmaxd
  where (whcondn)
    zcflux_ad(:) = zcflux_ad(:)+xcfluxr_ad(:)
    xiced_ad(:) = 0.
    xiced_ad(:) = xiced_ad(:)+zcflux_ad(:)*zrhoilfdt
    zcflux_ad(:) = 0.
  end where
endif
xiced = icestep_xiced_4h(:,1)
if (nice == 0) then
  whcondo = xiced(:) > 0. .or. xcliced2(:) > 0.
  where (whcondo)
    xicec_ad(:) = 0.
    xiced_ad(:) = 0.
    xcflux_ad(:) = 0.
  end where
  where ( .not. whcondo)
    xicec_ad(:) = 0.
  end where
else
  if (nfluko == 0) then
  else if (nfluko == 1) then
    call addfci
    where (xcliced2(:) > 0. .and. xicecc(:) > 0.999 .or. xcliced2(:) > 0. .and. xmaxd > 0. .and. xiced(:) > 0.9*xmaxd)
      xicec_ad(:) = 0.
    end where
    where (xiced(:) > 0. .and. xcliced2(:) > 0)
      xicec_ad(:) = 0.
    end where
    xcfluxr(:) = 0.
    xiced = icestep_xiced_4h(:,1)
    xcflux = icestep_xcflux_3h(:,1)
    call addfci_ad
    call getflx_ad
  else if (nfluko == 2) then
    call addfci_ad
    call mkflukoi_ad
  endif
  xicecc_ad(:) = xicecc_ad(:)+xicec_ad(:)
  xicec_ad(:) = 0.
endif
xicecc = xicecch(:)
xiced = icestep_xiced_4h(:,1)
call mkicec_ad( zicedold,zicedold_ad,xiced,xiced_ad,xicecc,xicecc_ad )
xiced = xicedh(:)
xcflux = icestep_xcflux_1h(:,1)
!call mkice_ad
xicec = xicech(:)
xiced = xicedh(:)
xsnow = xsnowh(:)
if (nsnow == 1) then
  where (xicec(:) >= cicemin)
    xsnow(:) = xsnow(:)+xprs(:)*xdt
  end where
endif
if (nsnow == 1) then
  !call subsnow_ad
else
  xsnow_ad(:) = 0.
endif
xicec = xicech(:)
xiced = xicedh(:)
xprs = xprsh(:)
xsnow = xsnowh(:)
where (xls(:) < 1.)
  xprs(:) = pprs(:)
end where
if (nsnow == 1) then
  where (xicec(:) >= cicemin)
    xsnow(:) = xsnow(:)+xprs(:)*xdt
  end where
endif
call mkcflux_ad
xicec = xicech(:)
xiced = xicedh(:)
xprs = xprsh(:)
xsnow = xsnowh(:)
xts = xtsh(:)
where (xls(:) < 1.)
  xprs(:) = pprs(:)
end where
if (nsnow == 1) then
  where (xicec(:) >= cicemin)
    xsnow(:) = xsnow(:)+xprs(:)*xdt
  end where
endif
if (ntskin == 1) then
  call skintemp_ad
else
  where (xiced(:)+1.e3/crhosn*xsnow(:) >= 0.1)
    xts_ad(:) = 0.
  end where
  where (xiced(:)+1.e3/crhosn*xsnow(:) < 0.1)
    xsst_ad(:) = xsst_ad(:)+xts_ad(:)
    xts_ad(:) = 0.
  end where
endif
xicec = xicech(:)
if (nsnow == 1) then
  where (xicec(:) >= cicemin)
    xprs_ad(:) = 0.
    xprs_ad(:) = xprs_ad(:)+xsnow_ad(:)*xdt
  end where
endif
where (xls(:) < 0.5)
  xiced_ad(:) = xiced_ad(:)+zicedold_ad(:)
  zicedold_ad(:) = 0.
  xsnow_ad(:) = xsnow_ad(:)+zsnowold_ad(:)
  zsnowold_ad(:) = 0.
end where
where (xls(:) < 1.)
  ptauy_ad(:) = ptauy_ad(:)+xtauy_ad(:)
  xtauy_ad(:) = 0.
  ptaux_ad(:) = ptaux_ad(:)+xtaux_ad(:)
  xtaux_ad(:) = 0.
  pprs_ad(:) = pprs_ad(:)+xprs_ad(:)
  xprs_ad(:) = 0.
  proff_ad(:) = proff_ad(:)+xroff_ad(:)
  xroff_ad(:) = 0.
  ppme_ad(:) = ppme_ad(:)+xpme_ad(:)
  xpme_ad(:) = 0.
  pswfl_ad(:) = pswfl_ad(:)+xswfl_ad(:)
  xswfl_ad(:) = 0.
  xaheat_ad(:) = xaheat_ad(:)+xheat_ad(:)
  xheat_ad(:) = 0.
  pheat_ad(:) = pheat_ad(:)+xaheat_ad(:)
  xaheat_ad(:) = 0.
end where
xcfluxr_ad(:) = 0.
xscflx_ad(:) = 0.

!----------------------------------------------
! CLOSE TAPE icestep
!----------------------------------------------

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine icestep_ad

subroutine icestep( pheat, pshfl, pshdt, plhfl, plhdt, plwfl, pswfl, ppme, proff, pprs, ptaux, ptauy, pust3, pts, picec, piced, &
&psnow, psmelt, psndch, psst, pmld, pps )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare arguments
!==============================================
real, intent(in) :: pheat(nhor)
real, intent(inout) :: picec(nhor)
real, intent(inout) :: piced(nhor)
real, intent(in) :: plhdt(nhor)
real, intent(in) :: plhfl(nhor)
real, intent(in) :: plwfl(nhor)
real, intent(inout) :: pmld(nhor)
real, intent(in) :: ppme(nhor)
real, intent(in) :: pprs(nhor)
real, intent(in) :: pps(nhor)
real, intent(in) :: proff(nhor)
real, intent(in) :: pshdt(nhor)
real, intent(in) :: pshfl(nhor)
real, intent(inout) :: psmelt(nhor)
real, intent(inout) :: psndch(nhor)
real, intent(inout) :: psnow(nhor)
real, intent(inout) :: psst(nhor)
real, intent(in) :: pswfl(nhor)
real, intent(in) :: ptaux(nhor)
real, intent(in) :: ptauy(nhor)
real, intent(inout) :: pts(nhor)
real, intent(in) :: pust3(nhor)

!==============================================
! declare local variables
!==============================================
real :: zcflux(nhor)
real :: zcflux2(nhor)
real :: zfresh(nlon,nlat) = 0.
real :: zfreshp(nhor) = 0.
real :: zheat(nlon,nlat) = 0.
real :: zicedold(nhor)
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real, allocatable :: zprf5(:)
real, allocatable :: zprf6(:)
real, allocatable :: zprf7(:)
real :: zrhoilfdt
real :: zroff(nlon,nlat) = 0.
real :: zsnowold(nhor)
real :: zswr(nlon,nlat) = 0.
real :: zswrp(nhor) = 0.
real :: ztaux(nlon,nlat) = 0.
real :: ztauxp(nhor) = 0.
real :: ztauy(nlon,nlat) = 0.
real :: ztauyp(nhor) = 0.
real :: zzz

zrhoilfdt = crhoi*clfi/xdt
zicedold(:) = 0.0
ximelt(:) = 0.
xsmelt(:) = 0.
xsmflx(:) = 0.
xtsflux(:) = 0.
xfluxc(:) = 0.
xscflx(:) = 0.
xcfluxn(:) = 0.
xsndch(:) = 0.
xcfluxr(:) = 0.
where (xls(:) < 1.)
  xaheat(:) = pheat(:)
  xheat(:) = xaheat(:)
  xshfl(:) = pshfl(:)
  xshdt(:) = pshdt(:)
  xlhfl(:) = plhfl(:)
  xlhdt(:) = plhdt(:)
  xlwfl(:) = plwfl(:)
  xswfl(:) = pswfl(:)
  xpme(:) = ppme(:)
  xroff(:) = proff(:)
  xprs(:) = pprs(:)
  xtaux(:) = ptaux(:)
  xtauy(:) = ptauy(:)
  xust3(:) = pust3(:)
end where
call iceget
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  allocate( zprf5(nlon*nlat) )
  allocate( zprf6(nlon*nlat) )
  allocate( zprf7(nlon*nlat) )
  call mpgagp( zprf1,xheat,1 )
  call mpgagp( zprf7,xoflux,1 )
  call mpgagp( zprf2,xclicec2,1 )
  call mpgagp( zprf3,xcliced2,1 )
  call mpgagp( zprf4,xsst,1 )
  call mpgagp( zprf5,xicec,1 )
  call mpgagp( zprf6,xiced,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In icestep: nstep= ',nstep
    write(unit=nud,fmt=*) 'sst (old time step): ',zprf4(nprhor)
    write(unit=nud,fmt=*) 'heatflx from atm: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'heatflx from oce: ',zprf7(nprhor)
    write(unit=nud,fmt=*) 'clim. ice c and d: ',zprf2(nprhor),zprf3(nprhor)
    write(unit=nud,fmt=*) 'actual ice c and d: ',zprf5(nprhor),zprf6(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
  deallocate( zprf5 )
  deallocate( zprf6 )
  deallocate( zprf7 )
endif
where (xls(:) < 0.5)
  zsnowold(:) = xsnow(:)
  zicedold(:) = xiced(:)
end where
if (nsnow == 1) then
  where (xicec(:) >= cicemin)
    xsnow(:) = xsnow(:)+xprs(:)*xdt
    xprs(:) = 0.
  end where
endif
if (ntskin == 1) then
  call skintemp
else
  where (xiced(:)+1.e3/crhosn*xsnow(:) >= 0.1)
    xts(:) = xclsst2(:)
  elsewhere
    xts(:) = xsst(:)
  end where
endif
call mkcflux
if (nsnow == 1) then
  call subsnow
else
  xsnow(:) = 0.
endif
call mkice
call mkicec( zicedold,xiced,xicecc )
if (nice == 0) then
  where (xiced(:) > 0. .or. xcliced2(:) > 0.)
    xflxice2(:) = (xiced(:)-xcliced2(:))*zrhoilfdt-xcflux(:)
    xcflux(:) = 0.
    xiced(:) = xcliced2(:)
    xicec(:) = xclicec2(:)
  elsewhere
    xflxice2(:) = 0.
    xicec(:) = 0.
  end where
  if (nprint == 2) then
    allocate( zprf1(nlon*nlat) )
    allocate( zprf2(nlon*nlat) )
    call mpgagp( zprf1,xflxice2,1 )
    call mpgagp( zprf2,xiced,1 )
    if (mypid == nroot) then
      write(unit=nud,fmt=*) 'diagnose flux correction:'
      write(unit=nud,fmt=*) 'heat for correction: ',zprf1(nprhor)
      write(unit=nud,fmt=*) 'new iced: ',zprf2(nprhor)
    endif
    deallocate( zprf1 )
    deallocate( zprf2 )
  endif
else
  xicec(:) = xicecc(:)
  if (nfluko == 0) then
    xflxice2(:) = 0.
  else if (nfluko == 1) then
    call getflx
    call addfci
    where (xiced(:) > 0. .and. xcliced2(:) > 0)
      xicec(:) = xclicec2(:)
    end where
    where (xcliced2(:) > 0. .and. xicecc(:) > 0.999 .or. xcliced2(:) > 0. .and. xmaxd > 0. .and. xiced(:) > 0.9*xmaxd)
      xicec(:) = 1.
    end where
  else if (nfluko == 2) then
    call mkflukoi
    call addfci
  endif
endif
zcflux(:) = 0.
if (xmaxd >= 0.) then
  where (xiced(:) > xmaxd)
    zcflux(:) = (xiced(:)-xmaxd)*zrhoilfdt
    xiced(:) = xmaxd
    xcfluxr(:) = xcfluxr(:)+zcflux(:)
    ximelt(:) = ximelt(:)+zcflux(:)
    xsndch(:) = xsndch(:)+zcflux(:)*1000./crhoi/zrhoilfdt/xdt
  end where
  call getiflx
endif
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  call mpgagp( zprf1,zcflux,1 )
  call mpgagp( zprf2,xcfluxr,1 )
  call mpgagp( zprf3,xcflux,1 )
  call mpgagp( zprf4,xiced,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'limit ice thickness (if > xmaxd):'
    write(unit=nud,fmt=*) 'heat for local correction: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'res. heat flux (after global adj.): ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'new iced: ',zprf4(nprhor)
    write(unit=nud,fmt=*) 'new cflux: ',zprf3(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
endif
where (xicec(:) >= thicec)
  xicec(:) = 1.
elsewhere
  xicec(:) = 0.
end where
zcflux2(:) = 0.
where (xiced(:) <= 0. .and. xsnow(:) > 0.)
  zcflux2(:) = xsnow(:)*1000.*clfsn/xdt
  xsmelt(:) = xsmelt(:)+xsnow(:)/xdt
  xsmflx(:) = xsmflx(:)+zcflux2(:)
  xcflux(:) = xcflux(:)-zcflux2(:)
  xsnow(:) = 0.
end where
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  call mpgagp( zprf1,zcflux2,1 )
  call mpgagp( zprf2,xcflux,1 )
  call mpgagp( zprf3,xsmflx,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'correct snow with new ice mask:'
    write(unit=nud,fmt=*) 'heat for correction: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'new flux for snow melt: ',zprf3(nprhor)
    write(unit=nud,fmt=*) 'new flux into ocean: ',zprf2(nprhor)
  endif
  zcflux2(:) = xaheat(:)+xoheat(:)-xtsflux(:)-xsmflx(:)-ximelt(:)-xcflux(:)+xcfluxr(:)
  call mpgagp( zprf1,zcflux2,1 )
  call mpgagp( zprf2,xflxice2,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'final check for balance :'
    write(unit=nud,fmt=*) 'uncoupled: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'coupled without flux correction: ',zprf1(nprhor)
    zzz = zprf1(nprhor)+zprf2(nprhor)
    write(unit=nud,fmt=*) 'coupled with flux correction: ',zzz
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
endif
xflxicea(:) = xflxicea(:)+xflxice2(:)
xheata(:) = xheata(:)+xaheat(:)
xofluxa(:) = xofluxa(:)+xoheat(:)
xqmelta(:) = xqmelta(:)+xqmelt(:)
ximelta(:) = ximelta(:)+ximelt(:)
xsmelta(:) = xsmelta(:)+xsmflx(:)
xcfluxa(:) = xcfluxa(:)+xcflux(:)
xcfluxra(:) = xcfluxra(:)+xcfluxr(:)
xcfluxna(:) = xcfluxna(:)+xcfluxn(:)
xtsfluxa(:) = xtsfluxa(:)+xtsflux(:)
xfluxca(:) = xfluxca(:)+xfluxc(:)
xscflxa(:) = xscflxa(:)+xscflx(:)
xcpmea(:) = xcpmea(:)+xpme(:)
xcroffa(:) = xcroffa(:)+xroff(:)
xstoia(:) = xstoia(:)+xstoi(:)
naccuout = naccuout+1
if (nout > 0) then
  if (mod(nstep,nout) == 0) then
    xflxicea(:) = xflxicea(:)/real(naccuout)
    xheata(:) = xheata(:)/real(naccuout)
    xofluxa(:) = xofluxa(:)/real(naccuout)
    xqmelta(:) = xqmelta(:)/real(naccuout)
    xcfluxa(:) = xcfluxa(:)/real(naccuout)
    xcfluxra(:) = xcfluxra(:)/real(naccuout)
    xcfluxna(:) = xcfluxna(:)/real(naccuout)
    ximelta(:) = ximelta(:)/real(naccuout)
    xsmelta(:) = xsmelta(:)/real(naccuout)
    xtsfluxa(:) = xtsfluxa(:)/real(naccuout)
    xfluxca(:) = xfluxca(:)/real(naccuout)
    xscflxa(:) = xscflxa(:)/real(naccuout)
    xcpmea(:) = xcpmea(:)/real(naccuout)
    xcroffa(:) = xcroffa(:)/real(naccuout)
    xstoia(:) = xstoia(:)/real(naccuout)
    if (noutput > 0) then
      call iceout
    endif
    xflxicea(:) = 0.
    xheata(:) = 0.
    xofluxa(:) = 0.
    xqmelta(:) = 0.
    xcfluxa(:) = 0.
    xcfluxra(:) = 0.
    xcfluxna(:) = 0.
    ximelta(:) = 0.
    xsmelta(:) = 0.
    xtsfluxa(:) = 0.
    xfluxca(:) = 0.
    xscflxa(:) = 0.
    xcpmea(:) = 0.
    xcroffa(:) = 0.
    xstoia(:) = 0.
    naccuout = 0
  endif
endif
where (xls(:) < 0.5)
  cheat(:) = cheat(:)+xcflux(:)
  cpme(:) = cpme(:)+xpme(:)
  croff(:) = croff(:)+xroff(:)
  ctaux(:) = ctaux(:)+xtaux(:)
  ctauy(:) = ctauy(:)+xtauy(:)
  cust3(:) = cust3(:)+xust3(:)
  csnow(:) = csnow(:)+xsnow(:)
end where
naccuo = naccuo+1
if (mod(nstep,ncpl_ice_ocean) == 0) then
  where (xls(:) < 0.5)
    cheat(:) = cheat(:)/real(naccuo)
    cpme(:) = cpme(:)/real(naccuo)
    croff(:) = croff(:)/real(naccuo)
    ctaux(:) = ctaux(:)/real(naccuo)
    ctauy(:) = ctauy(:)/real(naccuo)
    cust3(:) = cust3(:)/real(naccuo)
    csnow(:) = csnow(:)/real(naccuo)
  end where
  call oceanstep( xicec,xiced,cheat,cpme,croff,ctaux,ctauy,cust3,csnow,xsst,xmld,xoheat,xcliced2 )
  xoflux(:) = xoheat(:)
  where (xls(:) < 0.5)
    cheat(:) = 0.
    cpme(:) = 0.
    croff(:) = 0.
    ctaux(:) = 0.
    ctauy(:) = 0.
    cust3(:) = 0.
    csnow(:) = 0.
  end where
  naccuo = 0
endif
if (nmit > 0) then
  where (xls(:) < 1.)
    ztauxp(:) = xtaux(:)*(1.-xicec(:))
    ztauyp(:) = xtauy(:)*(1.-xicec(:))
    zswrp(:) = xswfl(:)*(1.-xicec(:))
    zfreshp(:) = xpme(:)-(xsnow(:)-zsnowold(:))/xdt-(xiced(:)-zicedold(:))/xdt*crhoi/1.e3
  end where
  call mpgagp( zheat,xcflux,1 )
  call mpgagp( zswr,zswrp,1 )
  call mpgagp( zfresh,zfreshp,1 )
  call mpgagp( zroff,xroff,1 )
  call mpgagp( ztaux,ztauxp,1 )
  call mpgagp( ztauy,ztauyp,1 )
  if (mypid == nroot) then
    call cputhfla( zheat )
    call cputswra( zswr )
    call cputpmea( zfresh )
    call cputroffa( zroff )
    call cputtaua( ztaux,ztauy )
  endif
!$taf INCOMPLETE xoflux,xsst
  if (nmit < 99) then
    where (xls(:) < 1.)
      xsst(:) = osst(:)
      xsss(:) = osss(:)
      xoflux(:) = 0.
      xtfreeze(:) = tfreeze
    end where
  endif
endif
where (xls(:) < 0.5)
  xsndch(:) = xsndch(:)+(xsnow(:)-zsnowold(:))/xdt
end where
pts(:) = xts(:)
picec(:) = xicec(:)
piced(:) = xiced(:)
psnow(:) = xsnow(:)
psmelt(:) = xsmelt(:)
psndch(:) = xsndch(:)
psst(:) = xsst(:)
pmld(:) = xmld(:)
nstep = nstep+1
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  call mpgagp( zprf1,xoflux,1 )
  call mpgagp( zprf2,xicec,1 )
  call mpgagp( zprf3,xiced,1 )
  call mpgagp( zprf4,xsst,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'final ice c and d to atm and oce: ',zprf2(nprhor),zprf3(nprhor)
    write(unit=nud,fmt=*) 'heatflx and sst from ocean: ',zprf1(nprhor),zprf4(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
endif
end subroutine icestep

subroutine icestop()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

if (mypid == nroot) then
  close(unit=71)
endif
if (mypid == nroot) then
  call put_restart_integer( 'naccuice',naccuout )
  call put_restart_integer( 'naccuo',naccuo )
  call put_restart_integer( 'nicec2d',nicec2d )
endif
call mpputgp( 'xls',xls,nhor,1 )
call mpputgp( 'xts',xts,nhor,1 )
call mpputgp( 'xicec',xicec,nhor,1 )
call mpputgp( 'xiced',xiced,nhor,1 )
call mpputgp( 'xsnow',xsnow,nhor,1 )
call mpputgp( 'xclicec',xclicec,nhor,14 )
call mpputgp( 'xcliced',xcliced,nhor,14 )
call mpputgp( 'xclsst',xclsst,nhor,14 )
call mpputgp( 'cheat',cheat,nhor,1 )
call mpputgp( 'cpme',cpme,nhor,1 )
call mpputgp( 'croff',croff,nhor,1 )
call mpputgp( 'ctaux',ctaux,nhor,1 )
call mpputgp( 'ctauy',ctauy,nhor,1 )
call mpputgp( 'cust3',cust3,nhor,1 )
call mpputgp( 'csnow',csnow,nhor,1 )
call mpputgp( 'xflxicea',xflxicea,nhor,1 )
call mpputgp( 'xheata',xheata,nhor,1 )
call mpputgp( 'xofluxa',xofluxa,nhor,1 )
call mpputgp( 'xqmelta',xqmelta,nhor,1 )
call mpputgp( 'xcfluxa',xcfluxa,nhor,1 )
call mpputgp( 'xcfluxra',xcfluxra,nhor,1 )
call mpputgp( 'xcfluxna',xcfluxna,nhor,1 )
call mpputgp( 'xsmelta',xsmelta,nhor,1 )
call mpputgp( 'ximelta',ximelta,nhor,1 )
call mpputgp( 'xtsfluxa',xtsfluxa,nhor,1 )
call mpputgp( 'xfluxca',xfluxca,nhor,1 )
call mpputgp( 'xscflxa',xscflxa,nhor,1 )
call mpputgp( 'xcpmea',xcpmea,nhor,1 )
call mpputgp( 'xcroffa',xcroffa,nhor,1 )
call mpputgp( 'xstoia',xstoia,nhor,1 )
call mpputgp( 'xicecc',xicecc,nhor,1 )
if (nmit < 99) then
  call mpputgp( 'osst',osst,nhor,1 )
  call mpputgp( 'osss',osss,nhor,1 )
endif
call oceanstop
if (nentropy > 0) then
  deallocate( xentro )
endif
if (naout > 0) then
  deallocate( xaout )
endif
end subroutine icestop

subroutine make_ice_thickness()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare parameters
!==============================================
real, parameter :: cmaxn = 0.9
real, parameter :: cminn = 0.1
real, parameter :: cmins = 0.25
real, parameter :: hmaxn = 3.0
real, parameter :: hmaxs = 0.50
real, parameter :: hminn = 0.25
real, parameter :: hmins = 0.25

!==============================================
! declare local variables
!==============================================
integer :: jlat
integer :: jm
real :: zc(nlon,nlat,0:13)
real :: zd(nlon,nlat,0:13)
real :: zhfac(0:13) = (/ 0.912,0.942,1.,1.058,1.124,1.161,1.175,1.058,0.931,0.883,0.88,0.876,0.912,0.942 /)

call mpgagp( zc,xclicec,14 )
zd(:,:,:) = 0.0
if (mypid == nroot) then
  do jm = 0, 13
    do jlat = 1, nlat/2
      where (zc(:,jlat,jm) >= cmaxn)
        zd(:,jlat,jm) = hmaxn*zhfac(jm)
      elsewhere (zc(:,jlat,jm) >= cminn)
        zd(:,jlat,jm) = (hminn+(hmaxn-hminn)*(zc(:,jlat,jm)-cminn)/(cmaxn-cminn))*zhfac(jm)
      elsewhere (zc(:,jlat,jm) > 0.0)
        zd(:,jlat,jm) = hminn*zhfac(jm)
      end where
    end do
    do jlat = nlat/2+1, nlat
      where (zc(:,jlat,jm) >= cmins)
        zd(:,jlat,jm) = hmaxs
      elsewhere (zc(:,jlat,jm) > 0.0)
        zd(:,jlat,jm) = hmins+zc(:,jlat,jm)
      end where
    end do
  end do
endif
call mpscgp( zd,xcliced,14 )
end subroutine make_ice_thickness

subroutine mkcflux_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zckap(nhor) = 0.
real :: zckap_ad(nhor)
real :: zhsnow(nhor) = 0.
real :: zhsnow_ad(nhor)

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zckap_ad(:) = 0.
zhsnow_ad(:) = 0.

!$taf INCOMPLETE zckap,zhsnow
where (xiced(:) >= xmind)
  zhsnow(:) = 1.e3/crhosn*xsnow(:)
  zckap(:) = (ckapsn*zhsnow(:)+ckapi*xiced(:))/(zhsnow(:)+xiced(:))
end where
if (xmaxd >= 0.) then
  where (xiced(:) >= xmaxd)
    zckap(:) = 0.
  end where
endif
if (nmit > 0) then
  xcfluxf_ad(:) = 0.
endif
if (nfluko > 0. .or. nice == 0) then
  xcfluxf_ad(:) = 0.
endif
where (xiced(:) >= xmind)
  xiced_ad(:) = xiced_ad(:)-xcfluxf_ad(:)*(zckap(:)*(tfreeze-xsst(:))/(zhsnow(:)+xiced(:))/(zhsnow(:)+xiced(:)))
  xsst_ad(:) = xsst_ad(:)-xcfluxf_ad(:)*(zckap(:)/(zhsnow(:)+xiced(:)))
  zckap_ad(:) = zckap_ad(:)+xcfluxf_ad(:)*((tfreeze-xsst(:))/(zhsnow(:)+xiced(:)))
  zhsnow_ad(:) = zhsnow_ad(:)-xcfluxf_ad(:)*(zckap(:)*(tfreeze-xsst(:))/(zhsnow(:)+xiced(:))/(zhsnow(:)+xiced(:)))
  xcfluxf_ad(:) = 0.
  xfluxc_ad(:) = xfluxc_ad(:)+xcflux_ad(:)
  xcflux_ad(:) = 0.
  xiced_ad(:) = xiced_ad(:)-xfluxc_ad(:)*(zckap(:)*(xts(:)-xsst(:))/(zhsnow(:)+xiced(:))/(zhsnow(:)+xiced(:)))
  xsst_ad(:) = xsst_ad(:)-xfluxc_ad(:)*(zckap(:)/(zhsnow(:)+xiced(:)))
  xts_ad(:) = xts_ad(:)+xfluxc_ad(:)*(zckap(:)/(zhsnow(:)+xiced(:)))
  zckap_ad(:) = zckap_ad(:)+xfluxc_ad(:)*((xts(:)-xsst(:))/(zhsnow(:)+xiced(:)))
  zhsnow_ad(:) = zhsnow_ad(:)-xfluxc_ad(:)*(zckap(:)*(xts(:)-xsst(:))/(zhsnow(:)+xiced(:))/(zhsnow(:)+xiced(:)))
  xfluxc_ad(:) = 0.
end where
if (xmaxd >= 0.) then
  where (xiced(:) >= xmaxd)
    zckap_ad(:) = 0.
  end where
endif
where (xiced(:) >= xmind)
  zhsnow(:) = 1.e3/crhosn*xsnow(:)
  xiced_ad(:) = xiced_ad(:)+zckap_ad(:)*((ckapi-(ckapsn*zhsnow(:)+ckapi*xiced(:))/(zhsnow(:)+xiced(:)))/(zhsnow(:)+xiced(:)))
  zhsnow_ad(:) = zhsnow_ad(:)+zckap_ad(:)*((ckapsn-(ckapsn*zhsnow(:)+ckapi*xiced(:))/(zhsnow(:)+xiced(:)))/(zhsnow(:)+xiced(:)))
  zckap_ad(:) = 0.
  xsnow_ad(:) = xsnow_ad(:)+zhsnow_ad(:)*(1.e3/crhosn)
  zhsnow_ad(:) = 0.
end where
where (xiced(:) < xmind)
  xcfluxf_ad(:) = 0.
  xheat_ad(:) = xheat_ad(:)+xcflux_ad(:)
  xcflux_ad(:) = 0.
end where

end subroutine mkcflux_ad

subroutine mkcflux()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zckap(nhor) = 0.
real :: zhsnow(nhor) = 0.
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)

where (xiced(:) < xmind)
  xcflux(:) = xheat(:)
  xcfluxf(:) = 0.
end where
where (xiced(:) >= xmind)
  zhsnow(:) = 1.e3/crhosn*xsnow(:)
  zckap(:) = (ckapsn*zhsnow(:)+ckapi*xiced(:))/(zhsnow(:)+xiced(:))
end where
if (xmaxd >= 0.) then
  where (xiced(:) >= xmaxd)
    zckap(:) = 0.
  end where
endif
where (xiced(:) >= xmind)
  xfluxc(:) = zckap(:)*(xts(:)-xsst(:))/(zhsnow(:)+xiced(:))
  xcflux(:) = xfluxc(:)
  xcfluxf(:) = zckap(:)*(tfreeze-xsst(:))/(zhsnow(:)+xiced(:))
end where
if (nfluko > 0. .or. nice == 0) then
  xcfluxf(:) = 0.
endif
if (nmit > 0) then
  xcfluxf(:) = 0.
endif
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  call mpgagp( zprf1,zhsnow,1 )
  call mpgagp( zprf2,zckap,1 )
  call mpgagp( zprf3,xcflux,1 )
  call mpgagp( zprf4,xcfluxf,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'in mkcflux: '
    write(unit=nud,fmt=*) 'snow depth (in m snow): ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'kappa and conductive hf: ',zprf2(nprhor),zprf3(nprhor)
    write(unit=nud,fmt=*) 'flux to adjust water temp. below ice: ',zprf4(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
endif
end subroutine mkcflux

subroutine mkflukoi_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zrhoilf

zrhoilf = crhoi*clfi
if (taunc > 0.) then
  where (xls(:) < 0.5)
    xiced_ad(:) = xiced_ad(:)+xflxice2_ad(:)*(zrhoilf/taunc)
    xflxice2_ad(:) = 0.
  end where
else
  where (xls(:) < 0.5)
    xiced_ad(:) = xiced_ad(:)+xflxice2_ad(:)*(zrhoilf/xdt)
    xflxice2_ad(:) = 0.
  end where
endif
xflxice2_ad(:) = 0.

end subroutine mkflukoi_ad

subroutine mkflukoi()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zrhoilf

zrhoilf = crhoi*clfi
xflxice2(:) = 0.
if (taunc > 0.) then
  where (xls(:) < 0.5)
    xflxice2(:) = (xiced(:)-xcliced2(:))*zrhoilf/taunc
  end where
else
  where (xls(:) < 0.5)
    xflxice2(:) = (xiced(:)-xcliced2(:))*zrhoilf/xdt
  end where
endif
end subroutine mkflukoi

subroutine mkice_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
logical :: whcondh(nhor)
logical :: whcondi(nhor)
logical :: whcondj(nhor)
logical :: whcondk(nhor)
real :: xcfluxh(lbound(xcflux,1):ubound(xcflux,1))
real :: xicedh(lbound(xiced,1):ubound(xiced,1))
real :: zmelt(nhor) = 0.
real :: zmelt_ad(nhor)
real :: zrhoilfdt

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
xicedh(:) = xiced
xcfluxh(:) = xcflux

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zmelt_ad(:) = 0.

!$taf INCOMPLETE xcflux,xiced,ximelt
zrhoilfdt = crhoi*clfi/xdt
where (xls(:) < 0.5)
  xcflux(:) = xcflux(:)+xoflux(:)
end where
where (xsst(:) <= xtfreeze(:) .or. xiced(:) > 0.)
  ximelt(:) = xcflux(:)+xscflx(:)-xcfluxf(:)
  xiced(:) = xiced(:)-ximelt(:)/zrhoilfdt
end where
if (nmit > 0) then
  zmelt(:) = 0.
  where (xiced(:) > 0. .and. xsst(:) > xtfreeze(:))
    zmelt(:) = (xsst(:)-xtfreeze(:))*crhos*dcool*cps/xdt
    xiced(:) = xiced(:)-zmelt(:)/zrhoilfdt
  end where
endif
where (xiced(:) <= 0.)
  xiced(:) = 0.
end where
whcondh = abs(xiced(:)) < 1.e-9
where (whcondh)
  xiced_ad(:) = 0.
end where
xcflux = xcfluxh(:)
xiced = xicedh(:)
where (xls(:) < 0.5)
  xcflux(:) = xcflux(:)+xoflux(:)
end where
where (xsst(:) <= xtfreeze(:) .or. xiced(:) > 0.)
  ximelt(:) = xcflux(:)+xscflx(:)-xcfluxf(:)
  xiced(:) = xiced(:)-ximelt(:)/zrhoilfdt
end where
if (nmit > 0) then
  zmelt(:) = 0.
  where (xiced(:) > 0. .and. xsst(:) > xtfreeze(:))
    zmelt(:) = (xsst(:)-xtfreeze(:))*crhos*dcool*cps/xdt
    xiced(:) = xiced(:)-zmelt(:)/zrhoilfdt
  end where
endif
whcondi = xiced(:) <= 0.
where (whcondi)
  xiced_ad(:) = 0.
  xiced_ad(:) = xiced_ad(:)!-xcflux_ad(:)*zrhoilfdt
end where
xcflux = xcfluxh(:)
xiced = xicedh(:)
where (xls(:) < 0.5)
  xcflux(:) = xcflux(:)+xoflux(:)
end where
where (xsst(:) <= xtfreeze(:) .or. xiced(:) > 0.)
  ximelt(:) = xcflux(:)+xscflx(:)-xcfluxf(:)
  xiced(:) = xiced(:)-ximelt(:)/zrhoilfdt
end where
if (nmit > 0) then
  whcondj = xiced(:) > 0. .and. xsst(:) > xtfreeze(:)
  where (whcondj)
    zmelt_ad(:) = zmelt_ad(:)-xiced_ad(:)/zrhoilfdt
    zmelt_ad(:) = zmelt_ad(:)-xcflux_ad(:)
    xsst_ad(:) = xsst_ad(:)+zmelt_ad(:)*(crhos*dcool*cps/xdt)
    zmelt_ad(:) = 0.
  end where
endif
xiced = xicedh(:)
whcondk = xsst(:) <= xtfreeze(:) .or. xiced(:) > 0.
where (whcondk)
  xcfluxf_ad(:) = xcfluxf_ad(:)+xcflux_ad(:)
  xcflux_ad(:) = 0.
  ximelt_ad(:) = ximelt_ad(:)-xiced_ad(:)/zrhoilfdt
  xcflux_ad(:) = xcflux_ad(:)+ximelt_ad(:)
  xcfluxf_ad(:) = xcfluxf_ad(:)-ximelt_ad(:)
  xscflx_ad(:) = xscflx_ad(:)+ximelt_ad(:)
  ximelt_ad(:) = 0.
end where
where (xls(:) < 0.5)
  xoflux_ad(:) = xoflux_ad(:)+xcflux_ad(:)
end where

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine mkice_ad

subroutine mkice()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
real :: zmelt(nhor) = 0.
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real, allocatable :: zprf5(:)
real :: zrhoilfdt

zrhoilfdt = crhoi*clfi/xdt
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  call mpgagp( zprf1,xcflux,1 )
  call mpgagp( zprf2,xoflux,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In mkice:'
    write(unit=nud,fmt=*) 'conductive hf and oce fl: ',zprf1(nprhor),zprf2(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
endif
where (xls(:) < 0.5)
  xcflux(:) = xcflux(:)+xoflux(:)
end where
where (xsst(:) <= xtfreeze(:) .or. xiced(:) > 0.)
  ximelt(:) = xcflux(:)+xscflx(:)-xcfluxf(:)
  xiced(:) = xiced(:)-ximelt(:)/zrhoilfdt
  xcflux(:) = xcfluxf(:)
end where
if (nmit > 0) then
  zmelt(:) = 0.
  where (xiced(:) > 0. .and. xsst(:) > xtfreeze(:))
    zmelt(:) = (xsst(:)-xtfreeze(:))*crhos*dcool*cps/xdt
    ximelt(:) = ximelt(:)+zmelt(:)
    xcflux(:) = xcflux(:)-zmelt(:)
    xiced(:) = xiced(:)-zmelt(:)/zrhoilfdt
  end where
endif
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  call mpgagp( zprf1,xcflux,1 )
  call mpgagp( zprf2,ximelt,1 )
  call mpgagp( zprf3,xiced,1 )
  allocate( zprf4(nlon*nlat) )
  allocate( zprf5(nlon*nlat) )
  call mpgagp( zprf4,zmelt,1 )
  call mpgagp( zprf5,xtfreeze,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'tfreeze: ',zprf5(nprhor)
    write(unit=nud,fmt=*) 'flux from ocean because t > tf: ',zprf4(nprhor)
    write(unit=nud,fmt=*) 'new ice and flux for ice: ',zprf3(nprhor),zprf2(nprhor)
    write(unit=nud,fmt=*) 'new (residual) conductive hf: ',zprf1(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
  deallocate( zprf5 )
endif
where (xiced(:) <= 0.)
  xcflux(:) = xcflux(:)-xiced(:)*zrhoilfdt
  ximelt(:) = ximelt(:)+xiced(:)*zrhoilfdt
  xcfluxn(:) = xcfluxn(:)-xiced(:)*zrhoilfdt
  xiced(:) = 0.
end where
where (abs(xiced(:)) < 1.e-9)
  xiced(:) = 0.
end where
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  call mpgagp( zprf1,xcflux,1 )
  call mpgagp( zprf2,ximelt,1 )
  call mpgagp( zprf3,xiced,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'final ice thickness: ',zprf3(nprhor)
    write(unit=nud,fmt=*) 'final flux for ice: ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'final conductive hf: ',zprf1(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
endif
end subroutine mkice

subroutine mkicec_ad( picedo, picedo_ad, picedn, picedn_ad, picec, picec_ad )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare arguments
!==============================================
real, intent(inout) :: picec(nhor)
real, intent(inout) :: picec_ad(nhor)
real, intent(in) :: picedn(nhor)
real, intent(inout) :: picedn_ad(nhor)
real, intent(in) :: picedo(nhor)
real, intent(inout) :: picedo_ad(nhor)

!==============================================
! declare local variables
!==============================================
real :: picech(lbound(picec,1):ubound(picec,1))
real :: zh0 = 0.5

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
picech(:) = picec

!$taf INCOMPLETE picec
where (picedn(:) > picedo(:))
  picec(:) = picec(:)+(1.-picec(:))*(picedn(:)-picedo(:))/zh0
  picec(:) = amin1(picec(:),1.)
end where
where (picedn(:) <= 0.)
  picec_ad(:) = 0.
end where
where (picedn(:) < picedo(:))
  picec(:) = picec(:)+picec(:)*(picedn(:)-picedo(:))/(2.*picedo(:))
  picec_ad(:) = picec_ad(:)*(0.5+sign(0.5,picec(:)-0.))
  picec = picech(:)
  where (picedn(:) > picedo(:))
    picec(:) = picec(:)+(1.-picec(:))*(picedn(:)-picedo(:))/zh0
    picec(:) = amin1(picec(:),1.)
  end where
  picedn_ad(:) = picedn_ad(:)+picec_ad(:)*(picec(:)/(2.*picedo(:)))
  picedo_ad(:) = picedo_ad(:)-picec_ad(:)*((picec(:)+2*(picec(:)*(picedn(:)-picedo(:)))/(2.*picedo(:)))/(2.*picedo(:)))
  picec_ad(:) = picec_ad(:)*(1+(picedn(:)-picedo(:))/(2.*picedo(:)))
end where
picec = picech(:)
where (picedn(:) > picedo(:))
  picec(:) = picec(:)+(1.-picec(:))*(picedn(:)-picedo(:))/zh0
  picec_ad(:) = picec_ad(:)*(0.5+sign(0.5,1.-picec(:)))
  picec = picech(:)
  picedn_ad(:) = picedn_ad(:)+picec_ad(:)*((1.-picec(:))/zh0)
  picedo_ad(:) = picedo_ad(:)-picec_ad(:)*((1.-picec(:))/zh0)
  picec_ad(:) = picec_ad(:)*(1-(picedn(:)-picedo(:))/zh0)
end where

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine mkicec_ad

subroutine mkicec( picedo, picedn, picec )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare arguments
!==============================================
real, intent(inout) :: picec(nhor)
real, intent(in) :: picedn(nhor)
real, intent(in) :: picedo(nhor)

!==============================================
! declare local variables
!==============================================
real :: zh0 = 0.5
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)

where (picedn(:) > picedo(:))
  picec(:) = picec(:)+(1.-picec(:))*(picedn(:)-picedo(:))/zh0
  picec(:) = amin1(picec(:),1.)
end where
where (picedn(:) < picedo(:))
  picec(:) = picec(:)+picec(:)*(picedn(:)-picedo(:))/(2.*picedo(:))
  picec(:) = amax1(picec(:),0.)
end where
where (picedn(:) <= 0.)
  picec(:) = 0.
end where
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  call mpgagp( zprf1,picedo,1 )
  call mpgagp( zprf2,picedn,1 )
  call mpgagp( zprf3,picec,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In mkicec: '
    write(unit=nud,fmt=*) 'old ice thickness: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'new ice thickness: ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'new ice compactness: ',zprf3(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
endif
end subroutine mkicec

subroutine mkicecf( picedc, piced, picec )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare arguments
!==============================================
real :: picec(nhor)
real :: piced(nhor)
real :: picedc(nhor)

!==============================================
! declare local variables
!==============================================
integer :: jhor
real :: zdice
real :: zh0 = 0.5
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)

do jhor = 1, nhor
  if (piced(jhor) > 0. .and. picedc(jhor) > 0) then
    zdice = piced(jhor)-picedc(jhor)
    if (zdice > 0.) then
      picec(jhor) = 1.-(1.-xclicec2(jhor))*exp(-(zdice/zh0))
    else
      picec(jhor) = xclicec2(jhor)*sqrt(piced(jhor)/picedc(jhor))
    endif
  endif
end do
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  call mpgagp( zprf1,picedc,1 )
  call mpgagp( zprf2,piced,1 )
  call mpgagp( zprf3,picec,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'In mkicecf: '
    write(unit=nud,fmt=*) 'clim. ice thickness: ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'act.  ice thickness: ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'new ice compactness: ',zprf3(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
endif
end subroutine mkicecf

subroutine read_ice_surface()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jm
real :: zmax

call mpsurfgp( 'xls',xls,nhor,1 )
call mpsurfgp( 'xclsst',xclsst,nhor,14 )
call mpsurfgp( 'xclicec',xclicec,nhor,14 )
call mpsurfgp( 'xcliced',xcliced,nhor,14 )
where (xls(:) > 0.5)
  xls(:) = 1.0
elsewhere
  xls(:) = 0.0
end where
call mpmaxval( xclicec,nhor,14,zmax )
if (zmax > 5.0) then
  xclicec(:,:) = xclicec(:,:)*0.01
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'ice cover {xclicec} converted from % to fraction'
  endif
endif
if (zmax < 0.0) then
  xclicec(:,:) = 0.0
  where (xclsst(:,:) <= tfreeze)
    xclicec(:,:) = 1.0
  end where
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'ice cover {xclicec} constructed from SST'
  endif
endif
if (xcliced(1,1) < 0.0) then
  nicec2d = 1
  call make_ice_thickness
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'ice thickness {xcliced} computed from ice cover'
  endif
endif
do jm = 0, 13
  where (xls(:) >= 1.0)
    xclicec(:,jm) = 0.0
    xcliced(:,jm) = 0.0
  end where
end do
end subroutine read_ice_surface

subroutine skintemp_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
real :: xtsh(lbound(xts,1):ubound(xts,1))
real :: zckap_mean(nhor)
real :: zckap_mean_ad(nhor)
real :: zcpdt
real :: zflx
real :: zflx_ad
real :: zhsnow(nhor)
real :: zhsnow_ad(nhor)
real :: zkapz
real :: zkapz_ad
real :: zrcpl
real :: ztso(nhor)
real :: ztso_ad(nhor)

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
xtsh(:) = xts

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zckap_mean_ad(:) = 0.
zflx_ad = 0.
zhsnow_ad(:) = 0.
zkapz_ad = 0.
ztso_ad(:) = 0.
call filter_margin(xts_ad, 1, 10. )
zrcpl = xmind*crhoi*cpi
ztso(:) = amin1(tmelt,xts(:))
do jhor = nhor, 1, -1
!$taf INCOMPLETE xts,zckap_mean,zhsnow
  zhsnow(jhor) = 1.e3/crhosn*xsnow(jhor)
!$taf INCOMPLETE xts,zckap_mean
  if (xiced(jhor) >= xmind) then
!$taf INCOMPLETE xts,zckap_mean
    zcpdt = zrcpl/xdt
    zckap_mean(jhor) = (ckapsn*zhsnow(jhor)+ckapi*xiced(jhor))/(zhsnow(jhor)+xiced(jhor))
    zkapz = zckap_mean(jhor)/(xiced(jhor)+zhsnow(jhor))
    if (xiced(jhor) >= xmaxd .and. xmaxd >= 0.) then
      zkapz = 0.
    endif
    zflx = xheat(jhor)+zkapz*xsst(jhor)
    xts(jhor) = (zcpdt*ztso(jhor)+zflx)/(zcpdt+zkapz)
    if (xts(jhor) > tmelt) then
      xts_ad(jhor) = 0.
      xheat_ad(jhor) = xheat_ad(jhor)+xqmelt_ad(jhor)
      xsst_ad(jhor) = xsst_ad(jhor)+xqmelt_ad(jhor)*zkapz
      zkapz_ad = zkapz_ad+xqmelt_ad(jhor)*(xsst(jhor)-tmelt)
      ztso_ad(jhor) = ztso_ad(jhor)+xqmelt_ad(jhor)*zcpdt
      xqmelt_ad(jhor) = 0.
    endif
    zflx_ad = zflx_ad+xts_ad(jhor)/(zcpdt+zkapz)
    zkapz_ad = zkapz_ad-xts_ad(jhor)*((zcpdt*ztso(jhor)+zflx)/(zcpdt+zkapz)/(zcpdt+zkapz))
    ztso_ad(jhor) = ztso_ad(jhor)+xts_ad(jhor)*(zcpdt/(zcpdt+zkapz))
    xts_ad(jhor) = 0.
    xheat_ad(jhor) = xheat_ad(jhor)+zflx_ad
    xsst_ad(jhor) = xsst_ad(jhor)+zflx_ad*zkapz
    zkapz_ad = zkapz_ad+zflx_ad*xsst(jhor)
    zflx_ad = 0.
    if (xiced(jhor) >= xmaxd .and. xmaxd >= 0.) then
      zkapz_ad = 0.
    endif
    xiced_ad(jhor) = xiced_ad(jhor)-zkapz_ad*(zckap_mean(jhor)/(xiced(jhor)+zhsnow(jhor))/(xiced(jhor)+zhsnow(jhor)))
    zckap_mean_ad(jhor) = zckap_mean_ad(jhor)+zkapz_ad/(xiced(jhor)+zhsnow(jhor))
    zhsnow_ad(jhor) = zhsnow_ad(jhor)-zkapz_ad*(zckap_mean(jhor)/(xiced(jhor)+zhsnow(jhor))/(xiced(jhor)+zhsnow(jhor)))
    zkapz_ad = 0.
    xiced_ad(jhor) = xiced_ad(jhor)+zckap_mean_ad(jhor)*((ckapi-(ckapsn*zhsnow(jhor)+ckapi*xiced(jhor))/(zhsnow(jhor)+xiced(jhor)))&
&/(zhsnow(jhor)+xiced(jhor)))
    zhsnow_ad(jhor) = zhsnow_ad(jhor)+zckap_mean_ad(jhor)*((ckapsn-(ckapsn*zhsnow(jhor)+ckapi*xiced(jhor))/(zhsnow(jhor)+&
&xiced(jhor)))/(zhsnow(jhor)+xiced(jhor)))
    zckap_mean_ad(jhor) = 0.
  else
    if (xiced(jhor) > 0.) then
      xheat_ad(jhor) = xheat_ad(jhor)+xqmelt_ad(jhor)
      xqmelt_ad(jhor) = 0.
    endif
    xsst_ad(jhor) = xsst_ad(jhor)+xts_ad(jhor)
    xts_ad(jhor) = 0.
  endif
  xsnow_ad(jhor) = xsnow_ad(jhor)+zhsnow_ad(jhor)*(1.e3/crhosn)
  zhsnow_ad(jhor) = 0.
end do
xts = xtsh(:)
xts_ad(:) = xts_ad(:)+ztso_ad(:)*(0.5-sign(0.5,xts(:)-tmelt))
ztso_ad(:) = 0.
xqmelt_ad(:) = 0.

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine skintemp_ad

subroutine skintemp()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
real :: zcflux(nhor)
real :: zckap_mean(nhor)
real :: zcpdt
real :: zflx
real :: zhsnow(nhor)
real :: zkapz
real, allocatable :: zprf1(:)
real, allocatable :: zprf10(:)
real, allocatable :: zprf11(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real, allocatable :: zprf5(:)
real, allocatable :: zprf6(:)
real, allocatable :: zprf7(:)
real, allocatable :: zprf8(:)
real, allocatable :: zprf9(:)
real :: zrcpl
real :: ztso(nhor)

zrcpl = xmind*crhoi*cpi
zcflux(:) = xheat(:)
xtsflux(:) = 0.
xqmelt(:) = 0.
ztso(:) = amin1(tmelt,xts(:))
do jhor = 1, nhor
  zhsnow(jhor) = 1.e3/crhosn*xsnow(jhor)
  if (xiced(jhor) >= xmind) then
    zcpdt = zrcpl/xdt
    zckap_mean(jhor) = (ckapsn*zhsnow(jhor)+ckapi*xiced(jhor))/(zhsnow(jhor)+xiced(jhor))
    zkapz = zckap_mean(jhor)/(xiced(jhor)+zhsnow(jhor))
    if (xiced(jhor) >= xmaxd .and. xmaxd >= 0.) then
      zkapz = 0.
    endif
    zflx = xheat(jhor)+zkapz*xsst(jhor)
    xts(jhor) = (zcpdt*ztso(jhor)+zflx)/(zcpdt+zkapz)
    if (xts(jhor) > tmelt) then
      xqmelt(jhor) = xheat(jhor)+zkapz*(xsst(jhor)-tmelt)-zcpdt*(tmelt-ztso(jhor))
      xts(jhor) = tmelt
    endif
    zcflux(jhor) = zkapz*(xts(jhor)-xsst(jhor))
    xtsflux(jhor) = zcpdt*(xts(jhor)-ztso(jhor))
  else
    xts(jhor) = xsst(jhor)
    if (xiced(jhor) > 0.) then
      xqmelt(jhor) = xheat(jhor)
    endif
  endif
end do
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  allocate( zprf5(nlon*nlat) )
  allocate( zprf6(nlon*nlat) )
  allocate( zprf7(nlon*nlat) )
  allocate( zprf8(nlon*nlat) )
  allocate( zprf9(nlon*nlat) )
  allocate( zprf10(nlon*nlat) )
  allocate( zprf11(nlon*nlat) )
  call mpgagp( zprf1,zhsnow,1 )
  call mpgagp( zprf2,zckap_mean,1 )
  call mpgagp( zprf5,ztso,1 )
  call mpgagp( zprf6,xts,1 )
  call mpgagp( zprf7,xheat,1 )
  call mpgagp( zprf8,xtsflux,1 )
  call mpgagp( zprf9,xqmelt,1 )
  call mpgagp( zprf10,zcflux,1 )
  call mpgagp( zprf11,xoflux,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'in skintemp: '
    write(unit=nud,fmt=*) 'modified atm. heat flux: ',zprf7(nprhor)
    write(unit=nud,fmt=*) 'modified oce. heat flux: ',zprf11(nprhor)
    write(unit=nud,fmt=*) 'snow depth (in m snow): ',zprf1(nprhor)
    write(unit=nud,fmt=*) 'kappa: ',zprf2(nprhor)
    write(unit=nud,fmt=*) 'old and new Ts: ',zprf5(nprhor),zprf6(nprhor)
    write(unit=nud,fmt=*) 'global min Ts: ',minval(zprf6)
    write(unit=nud,fmt=*) 'conductive heat flux (w. new ts): ',zprf10(nprhor)
    write(unit=nud,fmt=*) 'heat flux used to warm/cool ice: ',zprf8(nprhor)
    write(unit=nud,fmt=*) 'res. flux to melt snow/ice (T>TM): ',zprf9(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
  deallocate( zprf5 )
  deallocate( zprf6 )
  deallocate( zprf7 )
  deallocate( zprf8 )
  deallocate( zprf9 )
  deallocate( zprf10 )
  deallocate( zprf11 )
endif
if (nentropy > 0) then
  xentro(:,1) = xtsflux(:)/ztso(:)
endif
end subroutine skintemp

subroutine subsnow_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
logical :: whcondh(nhor)
logical :: whcondi(nhor)
real :: xsnowh(lbound(xsnow,1):ubound(xsnow,1))
real :: zdice_ad(nhor)
real :: zdsnow_ad(nhor)
real :: zhice_ad(nhor)
real :: zqmelt_ad(nhor)

!----------------------------------------------
! SAVE REQUIRED INPUT VARIABLES
!----------------------------------------------
xsnowh(:) = xsnow

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
zdice_ad(:) = 0.
zdsnow_ad(:) = 0.
zhice_ad(:) = 0.
zqmelt_ad(:) = 0.

!$taf INCOMPLETE xsnow
do jhor = 1, nhor
  if (xiced(jhor) > 0.) then
    if (xqmelt(jhor) > xsnow(jhor)*1000.*clfsn/xdt) then
      xsnow(jhor) = 0.
    else if (xqmelt(jhor) > 0. .and. xsnow(jhor) > 0.) then
      xsnow(jhor) = xsnow(jhor)-xqmelt(jhor)*xdt/clfsn/1000.
    endif
  else
    xsnow(jhor) = 0.
  endif
end do
whcondh = xls(:) < 0.5 .and. 1.e3*xsnow(:) > (crhos-crhoi)*xiced(:)
where (whcondh)
  zdsnow_ad = zdsnow_ad+xscflx_ad(:)*(1000*clfsn/xdt)
  xscflx_ad(:) = 0.
  zdsnow_ad(:) = zdsnow_ad(:)+xsnow_ad(:)
  zdice_ad(:) = zdice_ad(:)-zdsnow_ad(:)*(crhoi/1.e3)
  zdsnow_ad(:) = 0.
  xiced_ad(:) = xiced_ad(:)-zdice_ad(:)
  zhice_ad(:) = zhice_ad(:)+zdice_ad(:)
  zdice_ad(:) = 0.
  xiced_ad(:) = xiced_ad(:)+zhice_ad(:)*(crhoi/crhos)
  xsnow_ad(:) = xsnow_ad(:)+zhice_ad(:)*(1000/crhos)
  zhice_ad(:) = 0.
end where
xsnow = xsnowh(:)
do jhor = 1, nhor
  if (xiced(jhor) > 0.) then
    zqmelt_ad(jhor) = zqmelt_ad(jhor)+xcflux_ad(jhor)
    if (xqmelt(jhor) > xsnow(jhor)*1000.*clfsn/xdt) then
      xsnow_ad(jhor) = 0.
      xqmelt_ad(jhor) = xqmelt_ad(jhor)+zqmelt_ad(jhor)
      xsnow_ad(jhor) = xsnow_ad(jhor)-zqmelt_ad(jhor)*(1000*clfsn/xdt)
      zqmelt_ad(jhor) = 0.
    else if (xqmelt(jhor) > 0. .and. xsnow(jhor) > 0.) then
      zqmelt_ad(jhor) = 0.
      xqmelt_ad(jhor) = xqmelt_ad(jhor)-xsnow_ad(jhor)*(xdt/clfsn/1000.)
    endif
  else
    xsnow_ad(jhor) = 0.
    xsnow_ad(jhor) = xsnow_ad(jhor)-xcflux_ad(jhor)*(1000*clfsn/xdt)
  endif
end do
xqmelt_ad(:) = xqmelt_ad(:)+zqmelt_ad(:)
zqmelt_ad(:) = 0.
whcondi = xicec(:) < cicemin .and. xprs(:) > 0.
where (whcondi)
  xprs_ad(:) = 0.
  xprs_ad(:) = xprs_ad(:)-1000*xcflux_ad(:)*clfsn
end where

!----------------------------------------------
! FREE DYNAMIC MEMORY
!----------------------------------------------

end subroutine subsnow_ad

subroutine subsnow()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use icemod

implicit none

!==============================================
! declare local variables
!==============================================
integer :: jhor
real :: zdfl
real :: zdice(nhor) = 0.
real :: zdsnow(nhor) = 0.
real :: zhice(nhor) = 0.
real, allocatable :: zprf1(:)
real, allocatable :: zprf2(:)
real, allocatable :: zprf3(:)
real, allocatable :: zprf4(:)
real :: zqmelt(nhor) = 0.
real :: zzfli
real :: zzfls

where (xicec(:) < cicemin .and. xprs(:) > 0.)
  xcflux(:) = xcflux(:)-xprs(:)*1000.*clfsn
  xsmelt(:) = xprs(:)+xsmelt(:)
  xsmflx(:) = xsmflx(:)+xprs(:)*1000.*clfsn
  xprs(:) = 0.
end where
zqmelt(:) = xqmelt(:)
do jhor = 1, nhor
  if (xiced(jhor) > 0.) then
    if (xqmelt(jhor) > xsnow(jhor)*1000.*clfsn/xdt) then
      xsmelt(jhor) = xsmelt(jhor)+xsnow(jhor)/xdt
      xsmflx(jhor) = xsmflx(jhor)+xsnow(jhor)*1000.*clfsn/xdt
      zqmelt(jhor) = xqmelt(jhor)-xsnow(jhor)*1000.*clfsn/xdt
      xsnow(jhor) = 0.
    else if (xqmelt(jhor) > 0. .and. xsnow(jhor) > 0.) then
      xsmelt(jhor) = xsmelt(jhor)+xqmelt(jhor)/clfsn/1000.
      xsnow(jhor) = xsnow(jhor)-xqmelt(jhor)*xdt/clfsn/1000.
      xsmflx(jhor) = xsmflx(jhor)+xqmelt(jhor)
      zqmelt(jhor) = 0.
    endif
    xcflux(jhor) = xcflux(jhor)+zqmelt(jhor)
  else
    xsmelt(jhor) = xsmelt(jhor)+xsnow(jhor)/xdt
    xcflux(jhor) = xcflux(jhor)-xsnow(jhor)*1000.*clfsn/xdt
    xsmflx(jhor) = xsmflx(jhor)+xsnow(jhor)*1000.*clfsn/xdt
    xsnow(jhor) = 0.
  endif
end do
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  call mpgagp( zprf1,xsmelt,1 )
  call mpgagp( zprf2,xsnow,1 )
  call mpgagp( zprf3,xsmflx,1 )
  call mpgagp( zprf4,xcflux,1 )
  if (mypid == nroot) then
    write(unit=nud,fmt=*) 'in subsnow:'
    write(unit=nud,fmt=*) 'snow melt, and flx used for melting: ',zprf1(nprhor),zprf3(nprhor)
    write(unit=nud,fmt=*) 'new snow (m_snow): ',zprf2(nprhor)*1.e3/crhosn
    write(unit=nud,fmt=*) 'new conductive heat flux: ',zprf4(nprhor)
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
endif
xstoi(:) = 0.
zdice(:) = 0.
zdsnow(:) = 0.
where (xls(:) < 0.5 .and. 1.e3*xsnow(:) > (crhos-crhoi)*xiced(:))
  zhice(:) = (1.e3*xsnow(:)+crhoi*xiced(:))/crhos
  zdice(:) = zhice(:)-xiced(:)
  zdsnow(:) = -(zdice(:)*crhoi/1.e3)
  xsnow(:) = xsnow(:)+zdsnow(:)
  xscflx(:) = zdsnow*1.e3*clfsn/xdt
  xstoi(:) = zdice(:)*crhoi/1000./xdt
  xsmelt(:) = xsmelt(:)-zdsnow/xdt
  xsmflx(:) = xsmflx(:)-zdsnow*1.e3*clfsn/xdt
end where
if (nprint == 2) then
  allocate( zprf1(nlon*nlat) )
  allocate( zprf2(nlon*nlat) )
  allocate( zprf3(nlon*nlat) )
  allocate( zprf4(nlon*nlat) )
  call mpgagp( zprf1,zdice,1 )
  call mpgagp( zprf2,zdsnow,1 )
  call mpgagp( zprf3,xsnow,1 )
  call mpgagp( zprf4,xscflx,1 )
  if (mypid == nroot) then
    zzfli = zprf1(nprhor)*crhoi*clfi/xdt
    zzfls = zprf2(nprhor)*1000.*clfsn/xdt
    zdfl = zzfli+zzfls
    write(unit=nud,fmt=*) 'snow change by snow -> ice conv. (m/s,W): ',zprf2(nprhor),zzfls
    write(unit=nud,fmt=*) 'ice change by snow -> ice conv. (m/s,W): ',zprf1(nprhor),zzfli
    write(unit=nud,fmt=*) 'new snow (m_snow): ',zprf3(nprhor)*1.e3/crhosn
    write(unit=nud,fmt=*) 'flux to build ice (total, residual): ',zprf4(nprhor),zdfl
  endif
  deallocate( zprf1 )
  deallocate( zprf2 )
  deallocate( zprf3 )
  deallocate( zprf4 )
endif
end subroutine subsnow
